### ISSUE TITLE
OMV didn't hide kernel unsupported FS type  when creating filesystem

### ISSUE THREAD

**Issue by edwardwong80** [openmediavault/openmediavault#1010]
I am installing OMV 5.6.4-1 to my ARM based device. Created a RAID5 volume and then go  to "Filesystem" to make a new FS for my storage.
From the pull down menu I was presented with a number of filesystem types, I picked "BTRFS" and then pressed "create".
Then the system stuck, from the UI everything regarding my new FS is "n/a", I can't mount (mount failed) nor delete it from UI (no response). I went to console and checked /proc/filesystem, figured out that my kernel has no BTRFS support, eventually I have to use "dd if=/dev/zero of=/dev/md0 bs=512 count=10000" to clear out signature on my /dev/md0, after that the "ghost BTRFS filesystem" has gone from UI and I am able to re-create a new EXT4 from there. I hope the UI can grab a supported list before presenting to user, thanks.

**Comment by ryecoaaron** [comment]
What ARM system?  Maybe the btrfs module just wasn't loaded?

**Comment by edwardwong80** [comment]
> What ARM system? Maybe the btrfs module just wasn't loaded?

It's Marvell Armada 385, the actual device is a Linksys WRT1900AC v2, the kernel come with the built doesn't have BTRFS, not even the module (I might try to re-compile later to see if it works), but I think the system should hide something that doesn't work.

**Comment by ryecoaaron** [comment]
btrfs is a dependency of the openmediavault package itself which shouldn't be an issue on most systems since it is in the kernel.  Armbian, Raspios, and Debian all have it in there which is probably 99.99% of OMV installs.  It would be a big change to make the filesystem list dynamic since it is hard coded - https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/var/www/openmediavault/js/omv/module/admin/storage/filesystem/Filesystem.js#L123.  Big changes to the web interface like that are unlikely to happen to OMV 5.x since work on OMV 6.x is well on its way.  But that isn't my decision.  You could try submitting a pull request.

**Comment by edwardwong80** [comment]
OK noted, it's probably because the firmware I am using was built with custom kernel that stripped BTRFS support.
