### ISSUE TITLE
Datatable column header and column data do not align on column resize OMV6

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#1017]
**Describe the bug**

When you resize a column in a datatable you expect the data column to expand or stretch accordingly this is not happening.

**To Reproduce**
Go to standard datatable (filesystem section for example) drag the column resizer and observe the data columns not expanding 
Please see attached video

https://user-images.githubusercontent.com/7058119/115980304-08d62f80-a5cf-11eb-9ec2-b67d349b366e.mp4

**Expected behavior**

The column header and column data should stay align

**Screenshots**

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- openmediavault version: 6.0.5

**Client (please complete the following information):**

- Device: PC x86
- OS: Ubuntu 20.04
- Browser chrome 
- Version 89.0.4389.114

**Additional context**

**Comment by votdev** [comment]
By default the column mode is set to `flex` which does not support column resizing. You need to use `force`. In this mode you need to remove the `flexGrow` properties in the column config.

Mode `flex` is the default because it adapts the column width dynamically. The behavior of the column header is specified by the used [table component](https://github.com/swimlane/ngx-datatable) and cannot be influenced.

See:
* https://swimlane.gitbook.io/ngx-datatable/api/table/inputs#columnmode
* https://swimlane.gitbook.io/ngx-datatable/api/column/inputs#flexgrow-number
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/core/components/limn-ui/models/datatable-page-config.type.ts#L20

**Comment by votdev** [comment]
Column resizing is disabled by default for `columnMode === 'flex'`. See db1b1eab70ae38a4307fafd05c581f928c6b2374.

**Comment by subzero79** [comment]
I’ll explore those those options see if is better to disable resize or not
