### ISSUE TITLE
Add upload component omv6

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#1018]
**Is your feature request related to a problem? Please describe.**
Trying to replicate features of omv6. We need an upload file component, this is used for keyfiles in device encryption

**Describe the solution you'd like**
We need a form-input-file component that allows uploading files to the backend

**Describe alternatives you've considered**
Haven't considered anything, other than actually dropping the keyfile feature feature

**Additional context**

**Comment by votdev** [comment]
This type of form field has not been implemented by intention because it does not fit into the form processing and how the UI communicates with the backend.

This is the reason why the SSL/SSH import forms has text fields for the public/private keys instead of file upload fields.

**Comment by votdev** [comment]
What i can do is implementing a form field that supports the JavaScript `File API` to upload a file into the browser. The form field will place the file content into a hidden input field which is finally transferred to the backend via RPC.
A direct communication with the RPC backend will not be supported anymore because there is no generic solution doing that.
In the meantime simply use a `textarea` form field to allow the user to set the content.

**Comment by subzero79** [comment]
Otherwise just convert the file buffer to base64 and will pass it as text parameter. From there we can handle it in the backend.
