### ISSUE TITLE
Unable to backup OS via rsync or raid

### ISSUE THREAD

**Issue by fscii** [openmediavault/openmediavault#1050]
I'm uncertain if this is a bug, feature request or I'm just doing it wrong as I'm new to OMV.

I'm running Armbian on an odroidhc4 with omv5 with flash plugin.
I'm booting from an sd card (aka mmcblk0 - ext4).
I added a usb hub with a usb sd card reader with the same size sd card and omv picks that up fine under disks and format it the same to ext4.

However, it won't let me RAID mirror the OS to the sd card reader.  It says usb RAID unsupported ( ugh ),
 so as a last resort I went to try rsync.

Steps to reproduce:
Rsync->Add->Source Shared folder (click +)->Select Device

Nothing populates.  I'm hoping to backup root folder of mmcblk0 to sda.

Am I missing something? I'd really like at least one of these two ways to work to backup the OS, so I don't have to power down, remove sd card, back up manually, and so forth.

**Comment by votdev** [comment]
> However, it won't let me RAID mirror the OS to the sd card reader. It says 
> usb RAID unsupported ( ugh ),

OMV does not allow users to create a mdadm software RAID on USB devices because this always produces problems and data loss in the worst case.

This wouldn't help you either because you have to create the RAID that contains the OMV OS before it is installed. You need to do that on your own somehow.

> Steps to reproduce:
> Rsync->Add->Source Shared folder (click +)->Select Device

You need to create a [shared folder](https://openmediavault.readthedocs.io/en/5.x/new_user_guide/newuserguide.html#setting-up-a-sf) first to be able to use it in a service.

But this does not help you if you want to backup the root file system (OS) because OMV does not allow you to access this partition because of security issues.
