### ISSUE TITLE
add a variable for "mynetworks " in postfix

### ISSUE THREAD

**Issue by WBJUO** [openmediavault/openmediavault#1064]
**Is your feature request related to a problem? Please describe.**
Yes each time I add "mynetworks" to /etc/postfix/main.cf it is overwritten on update.
mynetworks = 127.0.0.0/8,192.168.1.10/32,192.168.1.5/32,192.168.1.200/32
This would allow me and others to configure persistent relaying from other machines on our networks.

**Describe the solution you'd like**
add a variable for "mynetworks" to postfix

**Describe alternatives you've considered**
I wrote a script to add "mynetworks" to main.cf and restart postfix however when updates happen via cronapt main.cf is overwritten. Adding a variable to OMV config would solve this.
Example
OMV_POSTFIX_MAIN_MYNETWORKS=127.0.0.0/8,192.168.1.10/32,192.168.1.5/32,192.168.1.200/32

Thanks.
William

**Comment by votdev** [comment]
It does not make sense to add configuration options (and env variables) for things that do not need to be managed by OMV. Because of that i added a documentation how to add custom Salt states. With this it is easily possible to add custom configuration that is applied whenever OMV rebuilds the configuration.

See https://openmediavault.readthedocs.io/en/5.x/various/advset.html#add-custom-states

**Comment by WBJUO** [comment]
I am very sorry to have bothered you, this is a much better solution, thanks for your help.

This works perfectly.

William

**Comment by votdev** [comment]
No worries, this was a good opportunity to update the documentation.
