### ISSUE TITLE
Improve use of buttons in dialogs

### ISSUE THREAD

**Issue by Tschoepler** [openmediavault/openmediavault#1082]
hi,

i'd like to propose to consider updating the use of buttons in dialogs. currently all buttons are primary action buttons (blue) making all actions equally important which usually is not the case. the primary action in a dialog should only be one if possible. the rest can be visualized using secondary action buttons (sometimes referred to as ghost buttons). and then there is also no easy way to distinguish which button has focus > the subtle shift in blue is not enough i'd say.

maybe consider the following:
- make primary actions like "Save" the only blue buttons
- change the other buttons to outlined/secondary buttons
- add a proper focus style to the buttons (bright blue outline for example > just look at the buttons here in github)
- its best practice and a strong pattern to have the "save" button (or any primary action button) on the very right side. if placed otherwise this begs for misunderstandings (currently it is on the left side). also the "cancel" button then is usually on the left of the "save" button.

current implementation
<img width="275" alt="image" src="https://user-images.githubusercontent.com/2727803/131261552-0f527209-7fe1-447b-9656-5db2e7da011f.png">

example save dialog of firefox on macos
<img width="594" alt="image" src="https://user-images.githubusercontent.com/2727803/131261563-5d5dfb89-4ca2-4dbb-bd19-a87b86ad85d7.png">

best,
jakob

**Comment by votdev** [comment]
Thanks for the suggestions, but OMV5 will not get any code changes related to the UI anymore because it is in maintenance mode since some time. Main development is done in OMV6 now. I think all your suggestions already apply to the new UI there because it follows the Angular Material design.

**Comment by Hukuma1** [comment]
Looks nice!

For the lazy:
<img width="795" alt="buttons" src="https://user-images.githubusercontent.com/54511555/131537118-aa977f81-20cd-4610-b9fd-d0d7fc1c83fb.png">

https://material.angular.io/components/button/overview

**Comment by votdev** [comment]
Buttons use different colors related to the context in OMV6.

![Bildschirmfoto vom 2021-09-11 15-19-56](https://user-images.githubusercontent.com/1897962/132949264-571c76eb-b550-4742-8f19-809e676a5255.png)

![Bildschirmfoto vom 2021-09-11 15-20-13](https://user-images.githubusercontent.com/1897962/132949266-cb3ff25f-09e4-452a-ba90-4145b4fd7f77.png)

![Bildschirmfoto vom 2021-09-11 15-20-39](https://user-images.githubusercontent.com/1897962/132949270-82b3db4b-1d03-4783-b59e-e08b7b326796.png)

![Bildschirmfoto vom 2021-09-11 15-20-55](https://user-images.githubusercontent.com/1897962/132949276-51300a87-6541-4ccc-935a-cf9bf68db516.png)

**Comment by votdev** [comment]
First of all thanks for your input.

> Better but i would still suggest to consider common ux patterns here.
> 
>     1. screenshot: shutdown is not a destructive action. Hence it would be common to go with blue. Also, it woman_technologist a a Common pattern to make the button actionable and naming it „shutdown“ instead of yes (as should the opposite be „cancel“ and not „no“) as the user does not have to think twice nor read the actual question in the dialogue (which no one does really). Compare macOS
>        ![image](https://user-images.githubusercontent.com/2727803/132960933-0c67f0b7-9fcf-4900-b26f-7182d3830638.jpeg)
> 

Shutting down a system, especially a NAS, might be a harmful and destructive action because data might get lost if you do it at the wrong time. Also using a red button seems not uncommon to me because Gnome desktop is also using it.

![Bildschirmfoto von 2021-09-12 02-39-52](https://user-images.githubusercontent.com/1897962/132977661-f150f00b-6be7-4485-8030-99d8a3f1ef63.png)

I have to agree to the texts on the buttons for [common actions](https://suse.eosdesignsystem.com/patterns/common-actions), this should be changed. 

>     2. cancel should be on the left of the primary action button. Just like no is on the left in the first example. Also it shouldn’t really be yellow but grey. Instead the user should be asked if they want to discard pending changes when they hit cancel but have made changes already. And the blue is probably not AA when it comes to color contrast. Maybe consider it little darker color. Can’t check it right now as I am on my phone smile

You're right with the orientation of the buttons in forms, it should be the same as for dialogs. Nevertheless i did not find anything in the Material specs that clearly mention that. The RedHat PatternFly design system is aligning the primary action button on the left side for [forms](https://www.patternfly.org/v4/components/form), but they also do that in modals. So i guess it is right to adapt the Material dialog specs to form pages.

Changes done:
- https://github.com/openmediavault/openmediavault/commit/4dbf37f92e5bf21698c0f82ef9f9c33f7e5c9025
- https://github.com/openmediavault/openmediavault/commit/7730d9e550f810ee32d83bd73f71df0a7baf4005

>     3. here the use of red ink or „danger button“ is correct as it is a destructive action. But again: changing the label to „wipe device“ is quicker to get and will prevent mistakes. Some apps even add an extra step where users have to type in the name of the device/file/project they want to delete (or a similar interrupting pattern) before being able to click the button as an extra level of safety. But that is pure taste. GitHub does something similar when it comes to deleting projects i think.

I checked how to make it possible to easily apply different button text, but because of the generic approach of the UI framework and in particular how these modal dialogs are defined, all buttons really have to be defined individually in all places where dialogs should appear. The effort seems too expensive to me; currently plugin developers simply have to specify a [template type](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/models/modal-dialog-config.type.ts#L24). I'll keep your suggestion in mind and think about how to implement that with little effort.

>     4. primary action should be blue and again I would propose to change „no“ to „cancel“ and „yes“ to „log out“.

Could you please point me to any reference.

>     5. in general: maybe consider getting rid of the question mark icon. It only interrupts the reading flow and adds an odd indent tongue headline. Google themselves also don’t use such a thing on their Material design dialogs anywhere. Probably for the same reason. Also it only takes up unnecessary space on smaller devices (smartphone).

Using Material framework does not imply that the the OMV UI will strictly follow the Material design rules. E.g. Windows also uses icons in dialogues with questions.

![windows](https://user-images.githubusercontent.com/1897962/132981301-ab11560f-3dcc-4d03-a565-ddba9c189994.png)

For me, this icon is an important visual feature that allows you to quickly grasp the type of dialogue.

**Comment by Hukuma1** [comment]
At first glance (the examples before the proposed changes), it did look a little all over the place and unfitting. I know that yellow and blue is infamous to OMV, but it just looks clashing. But I figured once OMV6 is out people can make their own theme possibly? Is this possible to do as a plugin perhaps? I wanted to take a stab at making a dark theme personally. Or should we try to make it into a theme on https://github.com/GilbN/theme.park?

Ultimately, this is just a UX/UI front end cleanup that just polishes it up. The backend is most important and hopefully that is as stable as OMV5. Have not rebooted it since I set it up. Uptime 176 days and counting. Cheers!

**Comment by votdev** [comment]
> At first glance (the examples before the proposed changes), it did look a little all over the place and unfitting. I know that yellow and blue is infamous to OMV, but it just looks clashing. But I figured once OMV6 is out people can make their own theme possibly? Is this possible to do as a plugin perhaps? I wanted to take a stab at making a dark theme personally. Or should we try to make it into a theme on [GilbN/theme.park](https://github.com/GilbN/theme.park)?
> 
> Ultimately, this is just a UX/UI front end cleanup that just polishes it up. The backend is most important and hopefully that is as stable as OMV5. Have not rebooted it since I set it up. Uptime 176 days and counting. Cheers!

Sorry, there are no plans to support theming in OMV6.

**Comment by Hukuma1** [comment]
No worries. I'm hoping this plugin can be updated for v6 and then we're off to the races: https://github.com/virgil-av/openmediavault-theme

**Comment by votdev** [comment]
> No worries. I'm hoping this plugin can be updated for v6 and then we're off to the races: [virgil-av/openmediavault-theme](https://github.com/virgil-av/openmediavault-theme)

I'm sorry, but that will not work because OMV6 is based on Angular/Material/Typescript whereas OMV5 is based on ExtJS.

**Comment by Hukuma1** [comment]
No worries. Is there a master css file that could be edited perhaps? Or are the styles spread out across a bunch of files?

**Comment by votdev** [comment]
> No worries. Is there a master css file that could be edited perhaps? Or are the styles spread out across a bunch of files?

There is a master CSS file, but it contains a hash in its name which changes with every new OMV package version. This is by nature of an Angular app. If you modify this file, you'll run in troubles because this will cause Debian APT to fail the installation of a new OMV package. This means, all files that are shipped and installed by the OMV package can't be touched and modified without running into troubles.

Including a simple `<link rel="stylesheet" href="assets/custom-theme.css"></link>` in the `index.html` file will not work because Angular will insert its styles inline after that line, so your CSS will never get applied. If this would workaround this somehow, you'll get an error in the browser if the `custom-theme.css` does not exist, which is surely the case for 99.9999% of the OMV users.

As you see, it's not trivial to add theming support. Because of that fact this useless feature has been dropped in OMV6.

**Comment by Tschoepler** [comment]
> Shutting down a system, especially a NAS, might be a harmful and destructive action because data might get lost if you do it at the wrong time. Also using a red button seems not uncommon to me because Gnome desktop is also using it.
True indeed. For a NAS this is not wrong.  Gnome probably just used it thinking that most Linux machines are servers 😄 in macOS, chromeos, Windows etc. It’s just a regular button following a confirmation dialog. 
> 
> You're right with the orientation of the buttons in forms, it should be the same as for dialogs. Nevertheless i did not find anything in the Material specs that clearly mention that. The RedHat PatternFly design system is aligning the primary action button on the left side for [forms](https://www.patternfly.org/v4/components/form), but they also do that in modals. So i guess it is right to adapt the Material dialog specs to form pages.
> 
+1 on “stick to a pattern”. 
regarding patternfly: this is a wonderful example where common patterns are ignored and thus creating user pain. Anywhere on the web, in native software or operating systems the primary action to “next”, “send”, “apply”, etc. It’s always on the very right. Because in the western world we  go from left to right through a form (consider flipping through pages of paper) and also we consider time/progress to go from left to right (when linear 😉). Hence, putting it in the right serves our mental model best. Look at SalesForce, ibm carbon, Airbnb, Photoshop, dhl, Lufthansa, iOS  … I’m certain you’ll find this pattern again. Also in the examples on the official Material design guidelines at https://material.io/components/dialogs#behavior 
>
> 
> Could you please point me to any reference related to the design specs how to colorize buttons.
> 
There isn’t one way to do it. Though red is  usually reserved for danger buttons as described above. 
all other buttons usually stick to one color and priority it’s done by using text buttons, Outline buttons (also called ghost or secondary buttons) or contained buttons (primary buttons). See Material design guidelines https://material.io/components/buttons#theming
I just took blue as it seems to be the OMV brand color. But you also make all buttons/links etc a different color. Airbnb does that for example, putting a petrol tone in contrast to their fuchsia brand color: https://airbnb.design/building-a-visual-language/

So in our example the primary action (considering the user wants to do what they clicked in the first place) is yes (or apply, save, next, etc.) and cancel (which is only an option in case the user changes their mind) a secondary action. There can be multiple secondary actions but there should be only one primary action if possible. There can also only be secondary actions. In that case text buttons are often used for both. But text button as secondary button in combination with a contained button is also common in Material design. 
> 
> For me, this icon is an important visual feature that allows you to quickly grasp the type of dialogue.
Totally agree that your own flavor of material design is ok. I just think if every dialog has that icon then it is obsolete, no? Are there other kinds of dialogs then? 
You don’t want to turn to Microsoft for good ux design really 😉 
Have a look at iOS or some good Android examples like gmail, maps or calendar. You won’t find icons. The dialog pattern itself is already strong enough these days. But this is really details 😁

**Comment by Tschoepler** [comment]
I have to admit though that windows puts the buttons usually on the right side but from left to right in priority. Meaning the primary action is on the very left. But they also don’t use a primary button which to me smells very much like they don’t care about ux and it might just be sent that is too big to change 😂

**Comment by Hukuma1** [comment]
> > No worries. Is there a master css file that could be edited perhaps? Or are the styles spread out across a bunch of files?
> 
> There is a master CSS file, but it contains a hash in its name which changes with every new OMV package version. This is by nature of an Angular app. If you modify this file, you'll run in troubles because this will cause Debian APT to fail the installation of a new OMV package. This means, all files that are shipped and installed by the OMV package can't be touched and modified without running into troubles.
> 
> Including a simple `<link rel="stylesheet" href="assets/custom-theme.css"></link>` in the `index.html` file will not work because Angular will insert its styles inline during compile time after that line, so your CSS will never get applied at runtime. If you would workaround this somehow, you'll get an error in the browser if the `custom-theme.css` does not exist, which is surely the case for 99.9999% of the OMV users.
> 
> Because of that facts this, IMO useless, feature has been dropped in OMV6.

Oh geeze! Yeah, I see. This is not feasible. Thank you for writing out the explanation! Then I guess the only solution would be browser-based re-write like Dark Reader or reverse proxy method like Theme.Park I mentioned above.
