### ISSUE TITLE
[OMV6] Not having a time zone set causes menu group buttons to reload instead of showing sub menu

### ISSUE THREAD

**Issue by jheyens** [openmediavault/openmediavault#1145]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**
*I'm sorry, but I do not have a forum account but I still thought I should report it*

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**
Not having a time zone set with openmediavault package v 6.0.2-1 seems to cause an issue with the menu. 
Clicking on some menu buttons (e.g. "Storage") briefly shows the sub menu, then reloads the page (where each menu is collapsed). Syslog then gets an entry "omv-engined[1256]: Unknown or deprecated time zone [tz=]. Please reconfigure your time zone settings."

Other menu buttons work. Luckily, "System" and "Diagnostics" are among them, so I was able to figure out the solution by reading the logs, then setting the time zone and applying the configuration.

**To Reproduce**

1. Don't have a time zone set (Timezone field in Date & Time is blank)
2. Upgrade from 6.0.1-1 6.0.2-1
3. Reboot
4. Log in with admin credentials
5. Click on "Storage" menu group in left menu bar

**Expected behavior**

Not really sure, since the system wasn't properly configured. But I think an error message would have been helpful?

**Reference to Forum**
Sorry :-(

**openmediavault Server (please complete the following information):**

- OS version: [uname -a] 
```
Linux vault239 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64 GNU/Linux
```
- openmediavault version: [dpkg -l | grep openmediavault]
ii  openmediavault                   6.0.2-1                      all

**Client (please complete the following information):**

- Device: [e.g. iPhone6] Desktop PC 
- OS: [e.g. iOS8.1] Arch Linux
- Browser [e.g. stock browser, safari] FF
- Version [e.g. 22] 94.0.1

**Additional context**

**Comment by votdev** [comment]
I don't think that the timezone is the reason because the [backend](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/env.inc) does not throw an exception which might force the UI to reload.

IMO the reason for this behavior is that the Angular app realizes that some files have been changed during the update and force a reload to get the latest files from the server. This is because the browser caches the files with a expiration time of some days to speedup the page load.

**Comment by votdev** [comment]
I think i found the reason for your issue; there was an error in the Angular app (UI) which was [caught](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/app/shared/services/global-error-handler.service.ts#L11)  and a page reload is forced, otherwise the UI hangs and that's not what the user expects.

I think i can improve the UI experience by showing the [Guru Meditation](https://en.wikipedia.org/wiki/Guru_Meditation) with an helpful message.

**Comment by votdev** [comment]
It comes out that this behaviour appears when the app data has been changed and the browser has cached obsolete data. Commit https://github.com/openmediavault/openmediavault/commit/2d86be3162b8be2e4b41bdb9a51111fdfbf947ca will show a more explaining error message.
