### ISSUE TITLE
Typo in update mailing list OMV6

### ISSUE THREAD

**Issue by sashaoshurkov** [openmediavault/openmediavault#1162]
Hello,

The letter describes that to update you need to execute the command Omv-Update, but such a command does not exist, there is a command Omv-Upgrade.

Screenshot of the problem ibb.co/J24yGn4

**Comment by sashaoshurkov** [comment]
It looks like the typos have not been fixed.

![Screenshot_20220103-083116_Gmail](https://user-images.githubusercontent.com/1682848/147912996-f5586e91-3e8c-4e77-8988-c33ba93eb902.jpg)

**Comment by votdev** [comment]
The typo has been fixed, but your configuration files have not been rebuild. Run `omv-salt deploy run cronapt` to do so. The issue was not of high priority to mark the configuration as dirty on all systems (which will lead into a rebuild of the cronapt config when the admin applies the configuration by pressing the yellow button in the UI).

**Comment by sashaoshurkov** [comment]
@votdev thanks for the clarification.
