### ISSUE TITLE
Lvm raid and snapshot gui

### ISSUE THREAD

**Issue by poohzaza166** [openmediavault/openmediavault#1176]
i would like a solution for lvm raid and snapshot manager in the gui 

since now lvm can do all of that in the command line and i have done it in the command line this will be a really useful feature for people who don't want to use madam or zfs 

and also the ablity to dynamically add and remove disk on lvm in lvm raid will be really usefull thanks

**Comment by votdev** [comment]
There is already the openmediavault-lvm plug-in. Have you tried that?

**Comment by poohzaza166** [comment]
yea this is the enhancement to it lvm have the ablity to do snapshot and raid now

**Comment by poohzaza166** [comment]
> There is already the openmediavault-lvm plug-in. Have you tried that?

um why close this?

**Comment by votdev** [comment]
Because the LVM plugin support snapshots. Never heard about someone is using LVM RAID. Please note that all OMV plugins are not designed to support all features of a software that it supports. A plugin should reflect the usual workflow of a home user.

If someone really wants to setup a LVM RAID, this is a simple one-liner in the CLI. Implementing this feature in the plugin on the other side is more cost intensive with low benefit. If you want to see it in the UI, feel free to contribute to the project.

**Comment by votdev** [comment]
According to this article [here](https://blog.programster.org/create-raid-with-lvm), LVM RAID is using mdadm under the hood. This is already fully supported in LVM. So there is absolutely no benefit re-duplicating this in the LVM plugin.

**Comment by poohzaza166** [comment]
thanks for explaing
