### ISSUE TITLE
Upgrading openmediavault package 6.0.7-1 -> 6.0.8-1 wants to remove sddm and task-kde-desktop

### ISSUE THREAD

**Issue by robvdl** [openmediavault/openmediavault#1186]
I have an existing installation of openmediavault running on Debian 11, nothing much else on there except I did pick KDE desktop during the install.

The other day the 6.0.8 package got released and I can't upgrade to it:

```
The following packages have been kept back:
  openmediavault
```

Upon closer inspection (I used 'apt install openmediavault') it tells me it wants to uninstall part of my KDE? why?

```
The following packages will be REMOVED:
  sddm task-kde-desktop
The following packages will be upgraded:
  openmediavault
```

Must be a change in the 6.0.8-1 package, 6.0.7-1 didn't have this issue. I don't understand why openmediavault wants to uninstall my current display manager sddm, it should have nothing to do with the display manager at all...

**Comment by votdev** [comment]
This is by intention. We decided to prevent users from installing OMV on desktop environments because of the huge support maintenance in the forum and all the problems that arise of this setup. OMV is not ment to be installed in parallel with a desktop environment because both try to setup the network and other problematic issues.

- https://github.com/openmediavault/openmediavault/pull/1175
- https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L30

**Comment by robvdl** [comment]
Oh my God that is annoying. I'm going to have to explain this to my friend now thanks to this stupid descision as we have a similar NAS setup. We both have running NASses and occasionally use it for a destkop. Why control HOW people use the software? This is just rediculous and controlling, I hate it, makes me want to fork! You already have to install it on Debian and not Ubuntu that is enough of a control for me and I get that. But now you can't even install it ona Desktop OS? that is control!

Think about existing installs, lots of users suddenly have to uninstall their desktop environments? they would be annoyed or even furious.

Since I have a working installation people rely on in the house, and so does my friend, I might have to lock the package version to 6.0-7 for now until I decide how to run this in a VM. I should have run it in a VM, but I had no idea I would have my desktop taken away by a piece of software!

I'm actually very annoyed at this.

**Comment by robvdl** [comment]
I didn't even know there was a support forum. I never ever clomplained about it. I have myself and my friend using it and we just been screwed over by this descision, the both of us. I'm super annoyed at this.

**Comment by ryecoaaron** [comment]
We have always recommend against installing OMV on a desktop because the desktop does things that conflict with OMV.  OMV is designed to be a headless NAS.  If you need an occasion desktop, buy an RPi.

> Why control HOW people use the software?

Because OMV can break when a desktop is installed.  If you supported OMV, you would know that.  Making sure there is no desktop installed will fix many issues.

> You already have to install it on Debian and not Ubuntu that is enough of a control for me and I get that.

This isn't control.  OMV requires certain package versions and Ubuntu and Debian use different versions.  I am a huge Ubuntu fan myself but it would be difficult to support Ubuntu and Debian.

> I didn't even know there was a support forum. I never ever clomplained about it. I have myself and my friend using it and we just been screwed over by this descision, the both of us. I'm super annoyed at this.

I'm sorry you are so angry but we do this in our free time and volunteer this time.  Not allowing a desktop will make supporting OMV just that much easier because of the hard to diagnose problems desktops have.

**Comment by robvdl** [comment]
Yep and I am about to go back to work, Tomorrow. And I have to scacrifice my free time to rectify this decision.

I guess my last word of advice would be "never break existing installations". If you want to enforce a change like "no desktop" then do it in the next major version like 7.0, don't break existing installation.

I see in the forum others are reporting this too, expect a lot more fallout in the forums from this I think. You're trying to solve a problem in the forum and it generates another.

**Comment by ryecoaaron** [comment]
OMV 6.x has not been released yet.  So, this should not have had to wait until OMV 7.x.  This is not breaking any OMV 5.x installs.  Changing frameworks breaks old plugins too but that is what happens when a product changes.  Do you yell at Microsoft when a game stops working on a new version of Windows?

You have to sacrifice a few hours.  I have "sacrificed" many, many more hours because of omv installed on desktops that users neglect to mention.

And maybe you should look at the change a little more carefully.  It is only preventing the installation of a display manager not a desktop environment.

**Comment by robvdl** [comment]
Not so easy if you have hardware that requires Debian 11, you're forced to run it 6.x then.

**Comment by ryecoaaron** [comment]
What hardware?  The standard Debian 11 kernel is the same kernel as the backports Debian 10 kernel.

**Comment by robvdl** [comment]
Fyi if people do their software updates in the GUI and the display manager gets uninstalled while it's running ... bad things happen. It can break the installation. Yes you can fix it in a command like using apt install -f, but still removing a display manager has consequences.

**Comment by robvdl** [comment]
2.5gbe realtek

**Comment by ryecoaaron** [comment]
> Fyi if people do their software updates in the GUI and the display manager gets uninstalled while it's running ... bad things happen. It can break the installation. Yes you can fix it in a command like using apt install -f, but still removing a display manager has consequences.

I know exactly what it does.  And that is because a standard debian install uses a desktop environemnt task.  Part of the task dependencies is a display manager.

> 2.5gbe realtek, but tomorrow it will be 12th gen Intel CPUs. The point is locking a version to a specific Debian version doesn't always work for people if they intend to run the latest hardware.

It is hard to support a bleeding edge desktop board with Debian since it is meant to be very stable.  The 2.5GBe realtek adapter can work with older kernels as well.  And if you think you can make OMV support multiple debian versions, please submit the pull request.  You will find it is harder than you think.  Just try to remember that Volker supports OMV by himself.  I support omv-extras plugins by myself.  There is only so much time we have without help.

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php?thread/37546-installing-rtl8156-ethernet-drivers/

**Comment by robvdl** [comment]
I have had some experience what happens when sddm gets uninstalled in the middle of a desktop session. It tears down the display manager instantly and leaves the packages in a broken state because the apt install is ended prematurely.

Anyway going a bit OT, this is a better way for rtl8156 https://github.com/awesometic/realtek-r8125-dkms

Right now I have an existing installation and it's easier to just stay on 6.0.7 or rebuild the deb.

**Comment by ryecoaaron** [comment]
Is the OMV box the only computer you have and that is why you need a desktop environment?  I'm just really trying to understand the need for a destkop environment on the OMV box.  Plenty of people use docker to install a desktop environment to RDP/VNC/browser into to do file management things.  I understand this requires a second system but it works very well.

The only option to force a display manager to not be installed is to uninstall network-manager and disable disk automount instead (these are the two biggest things that break OMV).  But I don't think people would like that either.

**Comment by ryecoaaron** [comment]
I was really just trying to understand the need here but you gave me the thumbs down.  I will stop now.

**Comment by robvdl** [comment]
It just seems like you're trying to talk me out of my setup that works for me, a setup I'm happy with. I don't have issues with network manager and automount issues I've only seen with remote drives, I don't use remote drives on the NAS itself.

**Comment by ryecoaaron** [comment]
@votdev Since I am really tired of this desktop situation already, what would you think about the following instead of display manager conflict?

- Disable udisks2 which is what is typically used to automount disks.
- Disable or hide the entire network tab if network-manager is running

**Comment by ryecoaaron** [comment]
> It just seems like you're trying to talk me out of my setup that works for me, a setup I'm happy with. I don't have issues with network manager and automount issues I've only seen with remote drives, I don't use remote drives on the NAS itself.

I'm not trying to talk you out of it.  I was trying to understand the use case and suggesting alternatives.  I was looking for a compromise that works for you AND makes my life a little easier.  Is it too much to ask for something that makes my life supporting users easier?

**Comment by robvdl** [comment]
Yeah sorry I get that. I just don't think forcing the openmediavault package to uninstall all display managers is a good answer.

**Comment by ryecoaaron** [comment]
Well then you tell me what the right solution is for someone who insists on having a desktop installed against our recommendations but has either of these problems:

If a user plugs in a new usb drive, it gets automounted.  Then the user goes to the filesystem tab and sees it is mounted.  They don't understand why they can't select that drive in the Shared Folder.

OR

A user configures their network adapter in the OMV web interface for a dhcp address.  Their system is acting weird because it has two ip addresses and dns is broken.

**Comment by robvdl** [comment]
I'm not sure because I don't do either of those. I don't connect USB drives to my NAS and I use nmtui to set the static IP address. I just feel that because some people do this, others are being punished with "no you can't have a desktop anymore ... sorry".

**Comment by votdev** [comment]
First, i'm sorry about your current situation.

> Yep and I am about to go back to work, tomorrow. And I have to scacrifice my free time to rectify this decision because my friend will be calling me up about it.

Please note that all maintenance cases because of side-by-side installations also cost the forum moderators their free time to fix issues that arise of this not supported setups.

> I guess my last word of advice would be "never break existing installations". If you want to enforce a change like "no desktop" then do it in the next major version like 7.0, don't break existing installations on people half way through.

We are doing that, OMV6 is still in beta and not official released.

**Comment by votdev** [comment]
> I'm not sure because I don't do either of those. I don't connect USB drives to my NAS and I use nmtui to set the static IP address. I just feel that because some people do this, others are being punished with "no you can't have a desktop anymore ... sorry".

You are doing that, but many other people are doing that and wonder why their setup does not work as expected. @ryecoaaron explained the problem very well in an earlier comment. From our experience with the user comments in the forum we decided to go that way for OMV6. @ryecoaaron improved the install script for SBC some time ago, i updated the Debian package 
control file later after fighting with an issue several hours until it came out that the user has a desktop environment. That was the final reason to go that route and prevent such installations.

As told, it is also our free time that gets lost when we have to maintain such user setups and try to help to fix them with their problems. 
Second, OMV is not designed to be installed in parallel to a desktop environment. Since OMV6 is in beta every user should be aware of that things might change. Maybe the communication was bad that there is a breaking change, but i have adapted to blog post immediately.

After your experience the only thing to do is to harden the upgrade path; notify users that an upgrade to OMV6 is not possible with a desktop environment installed.

**Comment by votdev** [comment]
> @votdev Since I am really tired of this desktop situation already, what would you think about the following instead of display manager conflict?
> 
>     * Disable udisks2 which is what is typically used to automount disks.
> 
>     * Disable or hide the entire network tab if network-manager is running

Disabling a service can easily be undone; finally we are in the same situation to have forum requests and tracker issues with problems that come from unsupported installations.

Adapting the UI code (+ complete backend) for unsupported setups is something i do not want to see in OMV.

**Comment by robvdl** [comment]
OK moving on, just wanted to mention I remember network manager being the default as well when I was using armbian so I think network manager possibly isn't quite exclusive to desktop but could also be on armbian? but don't quote me on that.

I think I recall once seeing that network manager issue you are talking about on armbian on my old helios4 nas, and then I just started using armbian-config to set a static IP address instead of doing it in openmediavault from that point onwards (and on debian I would use nmtui).

So I guess the networking page could either communicate with network manager itself on those network manager based installs. And on other server installs directly edit /etc/network/intefaces, but it sounds like you're not up for supporting a dual code path like that.

**Comment by ryecoaaron** [comment]
In the last few years, if you install OMV on Ambian using armbian-config or the install script, network-manager is removed - https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/install#L488

OMV uses netplan (like Ubuntu).  And while netplan can use network-manager on the backend, you could still have conflicts if someone configured things from the desktop.  OMV uses its database to store network info.  Maintaining that database while allowing changes from the desktop would be very difficult to maintain.  OMV works just fine with network configured from network-manager provided you don't setup anything in the interfaces tab.  And while you may know to do that, noobs do not.  People who know not to do that are a very small percentage.

**Comment by ken8521** [comment]
> Yep and I am about to go back to work, tomorrow. And I have to scacrifice my free time to rectify this decision because my friend will be calling me up about it.
> 
> I guess my last word of advice would be "never break existing installations". If you want to enforce a change like "no desktop" then do it in the next major version like 7.0, don't break existing installations on people half way through.
> 
> I see in the forum others are reporting this too, expect a lot more fallout in the forums from this I think. You're trying to solve a problem in the forum and it generates another.

Well, had you installed as recommended the first time, you wouldn't have any issues (it has ALWAYS been in the installation instructions not to install a desktop.. since literally the first time I installed OMV pre 1.0).  Only person to blame is yourself

**Comment by robvdl** [comment]
@ken8521 I thought we'd ended this thread but you are flaring it back up, why?

* I've never seen this note not to install it on a destkop, tell me where that statement is?
* I've never been told that 6.0.x is not stable yet, I started using it out of desperation because I had to run Debian 11

**Comment by ryecoaaron** [comment]
> Most people don't read

This is the real problem.  Unless the filename had do-install-on-desktop in it, there are still people who would never see the note.  It would take pages of notes to list all the things you shouldn't install OMV on.  In the server admin world, it is very rare to see a desktop environment installed.  It adds many more attack vectors.  The OMV iso does not install a desktop either.  https://openmediavault.readthedocs.io/en/5.x/faq.html?highlight=desktop#faq

Volker has said many times that sourceforge will show the stable version.  If you choose to look through what is available, you can not assume that is a stable version.  He does not want to put beta or rc in the filename because it could turn out to be the released version.

**Comment by mi-hol** [comment]
> "no you can't have a desktop anymore ... sorry".

@robvdl that is a wrong impression, just another installation approach (docker container) has to be used to have a GUI.
Please see https://forum.openmediavault.org/index.php?thread/41411-omv-may-have-a-desktop-environment/&postID=295507#post295507 for details

**Comment by mi-hol** [comment]
@votdev I'd fear the current warning text is misleading users.
"a side-by-side installation with graphical environments is **not supported anymore**"
From my understanding it was **never supported**  just not actively prevented.
I`d suggest a new warning text "a side-by-side installation with graphical environments is **now prevented technically**"

**Comment by mckaygerhard** [comment]
i praised this desition, OVM is a service and not a tool or a toy, have read a lot of illogical complaints arguing that they "force" it... it's ironic but i never see them abandon MACOS or Windos when M$ or Apple forces certain artifacts on their users...

have tried OMV and it is already too stupidly easy for windosers and they also want a desktop graphics session too... and for this reason, nowadays everyone thinks they are experts in computing or IT

**Comment by robvdl** [comment]
> i praised this desition, OVM is a service and not a tool or a toy, have read a lot of illogical complaints arguing that they "force" it... it's ironic but i never see them abandon MACOS or Windos when M$ or Apple forces certain artifacts on their users...
> 
> have tried OMV and it is already too stupidly easy for windosers and they also want a desktop graphics session too... and for this reason, nowadays everyone thinks they are experts in computing or IT

I get what you're coming from but the guy that had this setup was quite old and only recently passed away and I now have to help his family go through his computers left behind. It took him a while to get used to the idea of not running a desktop on his "spare" machine which was also a NAS so just leave it be.

He was not "just a windoze" user, but actually quite a keen open source fan that ran nothing but Linux machines and one Mac.

Please leave this ticket be, no need to keep commenting on it a ticket closed 2 years ago.
