### ISSUE TITLE
mount filepath differs

### ISSUE THREAD

**Issue by coelner** [openmediavault/openmediavault#1209]
This line 
https://github.com/openmediavault/openmediavault/blob/ef2c8fff6621a4d47efa5f79f2d20d82e5790c6f/deb/openmediavault/srv/salt/omv/deploy/monit/services/files/filesystem.j2#L23

causes this:
```
Restarting engine daemon ...
/etc/monit/conf.d/openmediavault-filesystem.conf:19: Program does not exist: '/usr/bin/mount'
```
the `mount` executable is under `/bin` . Maybe a `which` call could make it more flexible.

**Comment by ryecoaaron** [comment]
Your system doesn't have the usrmerge package installed.  This is probably because you upgraded the system from a previous release.  The latest version of the omv-release-upgrade utility installs usrmerge.

**Comment by votdev** [comment]
I don't know which version we are talking here (although the input mask mentions it), but i assume we can close the issue because `usrmerge` will fix the issue.

As mentioned, this will be installed in the latest [omv-release-upgrade](https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/05-install-usrmerge).
