### ISSUE TITLE
make "pop-up windows" resizable and moveable

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1248]
**Is your feature request related to a problem? Please describe.**
Update Manager opens a pop-up window that hides other content and can't be moved

**Describe the solution you'd like**
make "pop-up windows" resizable and moveable to allow for better screenshots, etc

**Additional context**
![image](https://user-images.githubusercontent.com/22799428/159515175-cf74d5b7-fc74-4d47-a202-6acaeafb01af.png)

**Comment by votdev** [comment]
The Material Design does not support moving of modal dialogs, because of that Angular Material does not support that -> OMV can't support it.

**Comment by votdev** [comment]
OK i did some research and it is somehow possible, but the overall experience is not that good because Material is not designed to support that because on a touch device it is not necessary no move or resize a dialog.

In the first demo only the coloured area is selectable to move the dialog. If it is changed to white again it is really hard to find the clickable area. It is not possible to use the whole header area. If the user moves the dialog out of the view and releases the left mouse button, the dialog is lost and the UI is frozen because 'ESC' to close dialogs has been disabled by intention in OMV. This is to keep the dialog open if the user clicks the left mouse button outside the dialog. ESC and that clicking on the backdrop are coupled in Angular Material.

![Peek 2022-03-22 19-51](https://user-images.githubusercontent.com/1897962/159554645-7c971172-c3a5-4434-8905-9687e5940ba3.gif)

Using the whole dialog for moving has also some disadvantages. You can move the dialog when clicking the action buttons. Releasing it will also fire the action => not really good.

Resumee: OMV will not support that feature.

**Comment by mi-hol** [comment]
Thanks for investing the time to find a possible solution. Appreciate it 👍
