### ISSUE TITLE
OMV6:  Plugin update date

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1289]
**Is your feature request related to a problem? Please describe.**
In the Plugin Update panel, I cannot see when the plug was last updated in the repository.

**Describe the solution you'd like**
I would like to see the date the plugin was updated.

**Comment by ryecoaaron** [comment]
Look at the changelog.  There is already a button that provides this feature.

**Comment by ryecoaaron** [comment]
I guess that button was removed on OMV 6.x

**Comment by votdev** [comment]
> In the Plugin Update panel, I cannot see when the plug was last updated in the repository.

That is technically not possible because the Debian APT package repository does not provide that information.

You can have a look into the changelog to get that information manually when the package is updated.

![Bildschirmfoto von 2022-04-25 18-54-11](https://user-images.githubusercontent.com/1897962/165136827-ba33fd8c-5c52-40e1-90ef-84cde59b2bc6.png)

**Comment by votdev** [comment]
![Peek 2022-04-25 19-11](https://user-images.githubusercontent.com/1897962/165139556-922d6d2c-5e63-4799-80c0-aee1d9fbdb13.gif)
