### ISSUE TITLE
Scheduled Task 

### ISSUE THREAD

**Issue by snakyjake1** [openmediavault/openmediavault#1294]
**Describe the solution you'd like**
I would like the output from the Scheduled Tasks to be output to Dashboard and alerts sent to Notifications.
Perhaps a simple regex parse, then routed to both/either Dashboard or Notifications.

**Describe alternatives you've considered**
Send email.

**Comment by votdev** [comment]
You can already interactively run scheduled tasks. Notifications will be sent un non-interactive mode when you select the `Send command output via email`. Doing that in interactive mode does not make sense because the user has visual feedback.

![Peek 2022-04-27 08-24](https://user-images.githubusercontent.com/1897962/165454700-f9a4dcd7-6ca9-4357-a96d-46fcab6bec28.gif)
