### ISSUE TITLE
Shared home folder remains in use by config/system/usermanagement/homedirectory when setting disabled

### ISSUE THREAD

**Issue by jrcuddy76** [openmediavault/openmediavault#1301]
If I disable the User home directory setting (Access Rights Management...Users...Settings tab) I also have to set the location to None before saving. If I don't, the shared folder will remain in use and Referenced even though home directories are disabled and I will not be able to delete the share.

Consider changing location to None once the slider is set to disabled.

**Comment by votdev** [comment]
> Consider changing location to None once the slider is set to disabled.

Thank your for pointing out this issue. However, i must disagree on the following points:

- The ui should not pretend to be intelligent and make changes to other settings.
- There are also users who temporarily deactivate a function. They would certainly be annoyed about having to reselect the shared folders afterwards.
- The previous assumption is not 100% true for the home directories. Therefore, if we were to implement the proposed approach here, the uniform behavior of the UI would be broken.
- There are other places like scheduled tasks that can be disabled to not run automatically, but there is the option to start them manually in the UI. If the shared folder would now be set to `None`, such tasks can no longer be executed manually because the configuration is invalid.
