### ISSUE TITLE
500 - Internal Server Error The DNS hostname is limited to 15 characters when using SMB/CIFS. 

### ISSUE THREAD

**Issue by xmstspider** [openmediavault/openmediavault#1304]
**Describe the bug**

Hi, I am testing the OMV6 and in my lab, I used hostname 'openmediavault-6'. When setting up the service, SMB throws the error:

500 - Internal Server Error The DNS hostname is limited to 15 characters when using SMB/CIFS. 

**To Reproduce**

1. Deploy OMV6 and use hostname with 16+ letters
2. Go to Services -> SMB/CIFS
3. Try to enable the service

**Expected behavior**

I know that 15-characters limit is due to Samba's NetBIOS dependency, but since OMV is targeting itself to not so experienced audience, there should be warning before starting the installation, e.g. text like this on the Welcome screen: 

***WARNING - if you intend to enable SMB/CIFS services, the hostname limit must be between 1-15 characters***

**openmediavault Server (please complete the following information):**

- OS version: OMV6
- openmediavault version: 6.0.26-1

**Client (please complete the following information):**

- Device: PC
- OS: Fedora
- Browser Firefox
- Version 100

Thank you

**Comment by votdev** [comment]
It is not possible to prevent the use of a hostname that is longer than 15 characters because there are 1000 ways to install OMV without the ability to prevent that in a previous step; e.g. OMV can be installed via Debian Netinst ISO + manuall package installation, via SBC images, via omv-extras.org install script, ... In all cases the user has already configured the hostname.

Because of that the issue has been solved the way it is currently implemented. 

The suggestion to display a warning banner is something i absolutely don't want to see in the UI.
