### ISSUE TITLE
Photoprism additional config options

### ISSUE THREAD

**Issue by rikki78** [openmediavault/openmediavault#1328]
Hi,
I would like to add an configuration option to photoprism but can't find where to do this. It should be included in the docker-compose file. How can I accomplish this?

**Comment by votdev** [comment]
Please ask such questions in the forum, because there the question will raise more attention.

> It should be included in the docker-compose file.

The `openmediavault-photoprism` plugin does not use Docker and Dockerfiles, podman is used instead.

> How can I accomplish this?

OMV provides [environment variables](https://openmediavault.readthedocs.io/en/stable/various/advset.html#environmental-variables) to customize things that are not available in the UI. For Photoprism, this is e.g. `OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS`. Here you can add e.g. `-e PHOTOPRISM_XXXX=YYYYY -e PHOTOPRISM_XXXXX=ZZZZZZ`.

**Comment by rikki78** [comment]
Hi thanks for your help, I will consult the forum first next time. 

I did as you suggested but when entering `omv-env set OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS "-e"` it always returns 
```
Usage: omv-env set [OPTIONS] KEY VALUE
Try 'omv-env set --help' for help.

Error: no such option: -e
```

Can you help or should I post this in the forum?

**Comment by votdev** [comment]
> Hi thanks for your help, I will consult the forum first next time.
> 
> I did as you suggested but when entering `omv-env set OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS "-e"` it always returns
> 
> ```
> Usage: omv-env set [OPTIONS] KEY VALUE
> Try 'omv-env set --help' for help.
> 
> Error: no such option: -e
> ```
> 
> Can you help or should I post this in the forum?

Oh, the click library seems to be too intelligent [here](https://github.com/pallets/click/issues/249). Please use the command 
```
# omv-env set -- OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS "-e foo -e bar"
```
