### ISSUE TITLE
Too many confirmation clicks needed

### ISSUE THREAD

**Issue by HannesJo0139** [openmediavault/openmediavault#1341]
Don't get me wrong. I'm myself more the type of a person who finds one more confirmation request better than one too few. But the new GUI is really hard. The default seems to be 3 confirmations. When I mount an fs, it's 4. Is that really necessary?

Mount fs -> Save
1. Confirmation: Click Yes
2.  Confirmation: Click Apply configuration changes
3. Tick confirm
4. Click Yes

**Comment by ryecoaaron** [comment]
Do you also click apply after ever save?

**Comment by votdev** [comment]
Die the fact that more configuration changes can be done between pressing apply every action that can damage data required a separate confirmation.

in your example the UI does not know that you didn’t have done any other action between creating the file system and applying the changes.

**Comment by HannesJo0139** [comment]
I know I know but still, applying config changes with the yellow banner itself is already kind of a confirmation. At least the new confirm checkbox before I can click the final yes has in fact no function other than being annoying. Too bad that you are not willing to discuss this but just nip it in the bud.

**Comment by votdev** [comment]
I can repeat myself again, applying configuration changes may change the complete behaviour of the system and its services; that is why I required a separate confirmation.

The same allies to creating a file system, it may destroy existing user data (which is hopefully not the case because OMV tries to prevent that).

**Comment by HannesJo0139** [comment]
Repeating this is not an argument to add even more confirmation requests on top of the already many confirmation requests we had before. Everyone who reads your statement would totally agree, as long as you omit the ridiculous number of 4 confirmations. 

What comes next? OMV7: 5 confirmations then get an activation link via e-mail, having to type in "I want to apply". In the mean-time the session has expired. Re-login. Changes are gone. Dev explains 'Yeah thats because applying config may change a lot here.' No! - Yes! - Oh!

**Comment by PapaBaer1968** [comment]
Hello, I deeply agree with Hannes.
Every now and then, when I change my config and work on the system, I don't like this "paranoid" security.
If been AD Admin / Helpdesk of an small enterprise for decades. My opinion: Even 10 confirmations does not work.
The oposite is the case, the users get used to click several times and nobody reads the message.
Don't forget, most of users here know wat they are doing, and if they lose data, they know why, even if they don't admit to. On the other hand side this is a minor problem of few people, mayby it's not worth the work. OVM is such a fine masterpiece of software, that I'm very gracefull to have it. Thank you !
I would appreciate to have the choice, but "I volontary swallow the toad" :-))

**Comment by ryecoaaron** [comment]
> most of users here know wat they are doing

After being a mod on the OMV forum for more than a decade, some do but a large amount don't.

**Comment by HannesJo0139** [comment]
> > most of users here know wat they are doing
> 
> After being a mod on the OMV forum for more than a decade, some do but a large amount don't.

Haha yes that's true and this large amount doesn't seem to read any notes or confirmation messages anyway, but just blindly click on what's probably right. 1, two or 10 confirmation checks would not wtop them from doing sth stupid :D

**Comment by PapaBaer1968** [comment]
>
Yes, sad, but I believe there is no solution to this, it's just human (or stupid).

**Comment by PapaBaer1968** [comment]
Now I'm thinking about to change, it gives the bitter taste of power abuse and domination, the opposite idea of freeware. sorry

**Comment by votdev** [comment]
> Now I'm thinking about to change, it gives the bitter taste of power abuse and domination, the opposite idea of freeware. sorry

???

Open source is not a request concert either. In the end, the developers decide for which features they invest their private time or how they imagine their software.

**Comment by PapaBaer1968** [comment]
OK. Volker, that's clear and understanable, you're the boss, I'm out.
 I've been supporting your project in forums, private help and tutos since V1 (2014/2025 I think), since you split from FreeNAS, but what you're saying is simply not true. Your paranoid "confirmation orgie" re-begun with Version 6, before nobody complaint. For me, this is wrong, a NAS is no xBox and a Admin is responsible.
I see, you're loosing my kind of spirit and its time for me to go on, 
looking what other mothers daughters are like, maybe again Free/TrueNAS.

**Comment by ryecoaaron** [comment]
Volker may be the boss but I have seen him accept requests for changes many, many times.  So, you say he has lost spirit because he doesn't back down on something that takes you fraction of a second to deal with?

**Comment by PapaBaer1968** [comment]
I don't know why you're getting into this, Aaron, but you're wrong.
If you would have looked over the whole threat you would have seen that I have no problem with the reason the confirmation built in, I just wanted to have the choice, and asked kindly to think about it. I Weren't offending anybody, I like OMV even with this "complication", and I know how much work and time you all spent for us. 
I have a problem with "I’m the boss" and you take it or leave.
Telling me others do worse is stupid reason. Even more because OMV were better than they, and I thought that’s the reason we left in 2009.
Treating me like a noob is the other side.
This said, I feel the spirit here is getting to "appled" for me.
No regrets but sorrow, I’m out.

**Comment by votdev** [comment]
> I have no problem with the reason the confirmation built in, I just wanted to have the choice, and asked kindly to think about it.

There is really no choice. The `Apply configuration` button is due to technical reasons. Building the configuration via SaltStack will take some seconds even for the smallest change. Pausing/blocking the UI every time a users clicks a checkbox or anything else is unacceptable and it is guaranteed to upset the users. To get around this, the changes are collected and deployed all at once if the user wants. A nice side effect is that it is relatively easy to undo the changes before they are deployed. Furthermore, the administrator can start the deployment exactly at the time he thinks is right.

**Comment by PapaBaer1968** [comment]
Let it go, Volker, you have your path, I have mine. 
Seems times have changed a lot.
If you ever battled with configs, and need to restart deamoms a lot, you'll know that it is a pain in the ass to click 4 times, burt as stated, I accepted that. There is no  "the admin can decide when changes are deployed" you do it now or never. On the one hand side you pretend this is a user protection feature, then you tell me it's technical nessecary then you come with administrative comfort.
I'm not bothering you nor complaining, the difficulties to go around this is a fact, but it was you who started kidding me. I'm in BSD, Darwin and Debian for about 40 years now, no need to treat me like "It's for your own safty".
You could have said nothing or simply the truth:
"It's dificult when not impossible and there much more important things to do."
I understand that completely. But saying others are worse, I'm the boss ...
is not what I thought votdev had in mind.

**Comment by votdev** [comment]
> On the one hand side you pretend this is a user protection feature, then you tell me it's technical nessecary then you come with administrative comfort.

What i told is correct in all belongs. I assume that we have talked past each other here in several respects. The `Apply config` button has technical reasons, the checkbox in various confirmation dialogs is for user safety.

> But saying others are worse, I'm the boss ...

Can't follow you. Never told that i am the boss. I only showed by example that there are more worse UIs with less UX than openmediavault. That's all.

**Comment by votdev** [comment]
To be honest, this discussion is now becoming too tiresome, time-consuming and nerve-wracking for me. I don't have to justify my design decisions in a software that I create in my free time and make available to the community for free.

It is your decision whether openmediavault meets your requirements or not. I don't have to convert or persuade anyone to do so. If it does not fulfil your needs and requirements, there are plenty of alternatives you might be happier with.

**Comment by votdev** [comment]
> I've been supporting your project in forums, private help and tutos since V1 (2014/2015 I think)

Thank you for your support so far.

**Comment by PapaBaer1968** [comment]
Me, too, as I said I apreciate the time spend with OMV, no regrets, just moving on.
Think you moved on too.
