### ISSUE TITLE
FR: disable login screen animation (the zoom on the hdd)

### ISSUE THREAD

**Issue by SamJongenelen** [openmediavault/openmediavault#1360]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to log in to a webapp and I immediately get distracted by moving imagery. 

**Describe the solution you'd like**
- no animation (and/or better no image at all) on the login screen
- a checkbox  'disable animation'

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. removing the image from the host
n/a
**Additional context**

**Comment by votdev** [comment]
> no animation (and/or better no image at all) on the login screen

I like it and most of the users seem to have no problem with it at all.

> a checkbox 'disable animation'

This is not how OMV works. The concept of OMV is to only provide the absolute necessary configuration options to the user.
If the log in animation is not wanted, the community must provide a way to customize the UI via a separate CSS file.
The OMV project will not implement it on its own because it does not fit into the concept (and the way how the UI framework works does not really support that).
