### ISSUE TITLE
Update from OMV5 to 6 ->  proxy_set_header X-Script-Name is not respected

### ISSUE THREAD

**Issue by berndbenner** [openmediavault/openmediavault#1362]
I have updated OMV5 to OMV6. The Update is working very well, ( after fixing /etc/apt/source.list , bullseye/security -> bullseye-security )
On OMV5, I have used a nginx docker as a reverse-proxy  for many docker services and also omv to map the url /omv/ to the OMV web port.
After the update to OMV6, the OMV6 web server will not note the "X-Script-Name" header data like OMV5.

```text
// omv nginx reverse-proxy settings ( working on omv5, not on omv6  ) 
location /omv/ {
        proxy_set_header X-Script-Name /omv;
        proxy_set_header Host $host;
        proxy_pass http://172.17.0.1:8089/;
        proxy_redirect off;
}
```

**Comment by votdev** [comment]
I don't know how this script was generated, but it's not managed by OMV. So i can not do anything here except pointing you to read the nginx manual or use Google to fix the issue. OMV6 is based on Debian 11 which means Debian has changed the nginx package version from Debian 10 -> 11. So maybe nginx has some changes regarding this header.

I'll close this issue because it is not OMV related.
