### ISSUE TITLE
RAID failure

### ISSUE THREAD

**Issue by MarlonSantosDev** [openmediavault/openmediavault#1367]
Goodnight! I need a hellp, in Openmediavault version 6.0.24 X64. When creating the RAID 1 (Mirror) and performing the File Systems configuration and the samba service, everything 100% working without problems. When removing a disk from the machine, the interface does not list the created RAID, I have no access to the files that were added to the disks in RAID. any tips on how to configure RQAID 1 in the tool so that, if any disk fails, access to files continues

**Comment by votdev** [comment]
Please raise this question in the forum because this is not a bug.

The problem when removing a device from a RAID is that sysfs does not provide any information anymore. The workaround this issue a human needs to put the pieces together to fix that. If there are no information that can be processed by OMV, then the UI can not display anything.
