### ISSUE TITLE
Preserve ssh access for existing user(s) on pre-installed debian

### ISSUE THREAD

**Issue by rabelux** [openmediavault/openmediavault#1381]
**Describe the bug**

I had finished setting up my debian server and then installed OMV following the [official documentation](https://openmediavault.readthedocs.io/en/stable/installation/on_debian.html). During debian-setup I enabled SSH, created a user ("eder") and disabled root access by leaving the root password empty [[screenshot of installer](https://user-images.githubusercontent.com/16120882/187036093-a249b199-2761-4ca6-b91f-29cf13dc0228.png)]. After installation SSH can't be accessed anymore.
This problem has already been confirmed by two users [here](https://github.com/openmediavault/openmediavault/issues/234#issuecomment-597183069) and [here](https://github.com/openmediavault/openmediavault/issues/234#issuecomment-639955913) so it seems OMV is indeed altering users' priviliges somehow.

**Expected behavior**

Existing users' SSH privilege persists.
I don't know how debian's installer handles SSH privilege but my guess is it adds an "AllowUser" entry to `sshd_config`, which OMV removes during setup.

**Make-a-wish solution**
Having read #779 and #234 I think it would be best if OMV would be able to migrate existing sshd_configs into the WEB-GUI without altering these. This would also prevent `root`-access from being enabled which I'm also not a fan of. I understand why you're doing it so maybe its possible to either
- detect whether SSH has already been enabled/configured, therefore expecting users to already have access

or
- detect whether OMV is being installed "as a service" (Third installation option as mentioned in the docs. "This runs openmediavault as a services on top of a Debian OS"), which needs shell access and therefore don't alter sshd_config.

**Additional information**

`Auth.log` after trying to access SSH as user "eder":
```
27.8.2022, 15:06:22
sshd[48461]: User eder from 10.1.1.35 not allowed because none of user's groups are listed in AllowGroups
27.8.2022, 15:06:22
sshd[48461]: error: Unable to load host key: /etc/ssh/ssh_host_dsa_key
```

As I tried to add the user to ssh-group via WEB-GUI and apply the changes I encountered an error.
syslog:
```
27.8.2022, 16:07:15
omv-engined[54706]: thrown in /usr/share/openmediavault/engined/rpc/usermgmt.inc on line 606
27.8.2022, 16:07:15
omv-engined[54706]: #4 {main}
27.8.2022, 16:07:15
omv-engined[54706]: #3 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('UserMgmt', 'setUser', Array, Array, 1)
27.8.2022, 16:07:15
omv-engined[54706]: #2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setUser', Array, Array)
27.8.2022, 16:07:15
omv-engined[54706]: #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
27.8.2022, 16:07:15
omv-engined[54706]: #0 [internal function]: Engined\Rpc\UserMgmt->setUser(Array, Array)
27.8.2022, 16:07:15
omv-engined[54706]: Stack trace:
27.8.2022, 16:07:15
omv-engined[54706]: PHP Fatal error: Uncaught Error: Call to a member function getAssoc() on null in /usr/share/openmediavault/engined/rpc/usermgmt.inc:606
```
The user did get added to ssh-group though according to `auth.log` and SSH login is possible:
```
27.8.2022, 16:07:15
usermod[54712]: add 'eder' to group 'eder'
27.8.2022, 16:07:15
usermod[54712]: add 'eder' to group 'ssh'
27.8.2022, 16:07:15
usermod[54712]: change user 'eder' GID from '1000' to '100'
27.8.2022, 16:07:15
usermod[54712]: add 'eder' to shadow group 'eder'
27.8.2022, 16:07:15
usermod[54712]: add 'eder' to shadow group 'ssh'
```

**openmediavault Server:**

- OS version: `5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux`
- openmediavault version: `6.0.37-1 (Shaitan)`

**Comment by votdev** [comment]
First of all i fully understand your problem, but importing pre-configured settings into the OMV database is not how it works, or only done for a small but system critical things like IP addresses or host names for the network configuration. This is by design because OMV is not [webmin](https://www.webmin.com/) where the UI reflects the content of the configuration files. OMV has been started with a total different approach where the internal database is the source of truth.

Here are my other concerns:
- The documentation does not mention anywhere that existing settings are imported.
- How should I justify breaking OMV's approach for SSH and not for others?
- Where to start and stop not becoming webmin.
- How to detect that the SSH settings are customized?
- Imagine, how to handle the situation when the default Debian sshd_config file denies root login by default and OMV imports that during installation. This will break the default behaviour (which is by intention) of enabling root to allow users to access their system during setup for maintenance or in case of broken installations. Then accessing the system via TTY to rescue it is blocked. The user has to install/flash the system again. Not a good first impression. 

Solution:
- Update the documentation and advice the user to disable root access for security reasons.
- Update the documentation to make clear NO existing settings are imported during the installation. All settings need to be done via the UI.
