### ISSUE TITLE
Notifications should include time stamp in message

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#1432]
This may be outside your control, I'm not sure what you are using to generate the messages.

The UPS shutdown emails sometimes don't get through until after the system is restarted. When received they appear as if they are happening now, not when the shutdown occurred. The text of the message should have the time in it so it is clear that it's an old message. This would probably be good for all notifications in case mail is in delay for other reasons.

**Comment by votdev** [comment]
The email is generated by nut upssched and out of the control of the OMV project.

**Comment by PrplHaz4** [comment]
It looks like upsmon controls the message and upssched the sending of the notification/email.

Does omv write/overwrite this .conf file? Or, would changing the message upstream even fix it for omv?

https://github.com/networkupstools/nut/blob/master/conf/upsmon.conf.sample.in

**Comment by votdev** [comment]
> Does omv write/overwrite this .conf file? Or, would changing the message upstream even fix it for omv?

OMV is managing that configuration file, but it does not help to change the notification messages because `upsmon` does not provide the ability to use a placeholder for the date that will be filled with the current time of the notification at runtime. Only `%s` will be replaced by the configured name at runtime. If you want that feature this must be implemented by the NUT project, but i fear that it will take ages until this feature appears in Debian package.

The best is to find out why Postfix does not send the email before the shutdown.

**Comment by votdev** [comment]
This could be interested: https://forum.openmediavault.org/index.php?thread/45897-customize-nut-notifications/&postID=335349#post335349

**Comment by dsm1212** [comment]
We just had a brief power outage so I have confirmation the OMV_NUT_UPSSCHEDCMD_EMAIL_SUBJECT  including %h showed me the date and time of the event in the subject. Thanks!!!
