### ISSUE TITLE
[snapraid-diff] WARNING! Ignoring special 'socket' file

### ISSUE THREAD

**Issue by henfri** [openmediavault/openmediavault#144]
Hello,

/usr/sbin/omv-snapraid-diff
is giving me a message 
"WARNING! Ignoring special 'socket' file" for several files.
by Mail every time.

I think that messages should not be sent, if they are not important. This one is not.
I suggest to add a filter 
> /usr/sbin/omv-snapraid-diff | grep -v "WARNING! Ignoring special 'socket' file"

in the cron-job.

One could make it more general by adding the option to the plugin to ignore all WARNINGs, but I am not sure this is a good idea.

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
This should be filed on the snapraid plugin issues page - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/issues

That change is not something I would make though since the diff script should be altered instead of piping to grep (yuck).  You are free to edit the command on the scheduled jobs if you want to do that.

**Comment by henfri** [comment]
Done.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/issues/18
> You are free to edit the command on the scheduled jobs if you want to do that.

Would this be persistent? I think that these cronjobs are created automatically. Wouldn't this modification be overwritten at some point?

**Comment by ryecoaaron** [comment]
The only time it would be overwritten is if you clicked the Scheduled Diff button again.
