### ISSUE TITLE
OMV6+ Deleting "shared folder" behavior to be reverted as in OMV5

### ISSUE THREAD

**Issue by vskatusa** [openmediavault/openmediavault#1468]
https://forum.openmediavault.org/index.php?thread/45884-deleted-shared-folder-using-cli-but-webui-shows-it/

**Comment by votdev** [comment]
I'll close this issue because deleting the content of a shared folder has been removed by intention:

- Removing all content may took a very long time
- From our experience in many years many users simply wanted to delete the shared folder configuration, but deleted their data finally. This causes many frustration.
- Alerting the user with warning messages and checkboxes before a shared folder + content has been removed does not help; users have deleted their data by mistake anyway
