### ISSUE TITLE
Apprise as main notification service

### ISSUE THREAD

**Issue by ilvise** [openmediavault/openmediavault#1521]
Hi, please consider the integration of the apprise library as main notification service in place of the mail notification service.

Apprise is a very popular, solid, lightweight notification service that can easily integrate a tons of services such as Telegram, Discord, Slack, Amazon SNS, Gotify, SNTP, SMS...

With apprise the users can integrate, for example, a telegram bot notification service in a single line such as tgram://bottoken/ChatID
Or.. A mail with mailto://userid:[pass@domain.com]

Many thanks

**Comment by votdev** [comment]
openmediavault already has a [plugin system](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/notification/sink.d) to add custom notification services.

Even if i would add your suggested service, Postfix HAS to be run in the background because email is the only interface that Linux userland apps support. Otherwise it would not be possible to get emails from monit, smartd, mdadm, ...

**Comment by votdev** [comment]
I see email is supported by Apprise and `mail` could be wrapped by a custom script. But Postfix is doing a lot more than only sending emails to the configured SNMP server, e,g sender and subject rewriting/manipulation. How to handle emails submission to normal users that are not the administrator/root account? This is all handled by Postfix. Can Apprise handle all edge cases of SNMP servers that Postfix can?

**Comment by votdev** [comment]
> HI,
> 
> Just for your information, I use [Mailrise](https://github.com/YoRyan/mailrise), a mail gateway to Apprise. Works perfectly!
> 
> Sined

Replacing Postfix by a different MTA does not make sense. Integration of Postfix is easy because it is packaged in Debian. OMV fully relies on DEB packages, so adding software that is not delivered via Debian packages is not easy or impossible.
