### ISSUE TITLE
DHCP DNS domain and search list settings not honored

### ISSUE THREAD

**Issue by meyergru** [openmediavault/openmediavault#1551]
**Problem description**

When I use DHCP network settings, I get only the DNS server from DHCP (option 6), but neither the DNS domain (option 15) nor the more modern "search list" (option 119). I have not been able to get this via DHVPv4 nor DHCPv6.

When I look at /etc/resolv.conf, there is only a "." in the search entry. When I use standard debian 11.6, these options are honored.

Also, when I try to use the search list from the GUI, it works only when I specify the DNS server, too.

This is a problem when the NAS shall execute scripts with local hostnames in it - you must always specify the (default) domain.

**Expected behavior**

DHCP options 15 and 119 should be honored and lead to a correct DNS search list.

**Reference to Forum**

https://forum.openmediavault.org/index.php?thread/47824-bug-report-dhcp-dns-domain-and-search-list-settings-not-honored/&postID=349612#post349612

**openmediavault Server (please complete the following information):**

- OS version: Linux sixwd 6.1.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1~bpo11+1 (2023-03-16) x86_64 GNU/Linux
- openmediavault version: 6.3.11-2

**Client (please complete the following information):**

none

**Comment by votdev** [comment]
openmediavault is using [Netplan](https://netplan.io) to configure the network. 
If no DNS server is configured in the UI for a specific interface, then Netplan is using the DNS servers provided via DHCP by default. If a DNS server is configured in the UI, then this behaviour is prevented, see [here](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/ethernet.j2#L49).

I'm not sure how `use-domains` is configured by default in Netplan. Setting `use-domains` to false should be necessary if the search domain is set in the UI.

By the fact that such a setup is not common in home environments (because routers and DSL modems used there do not have such features) there might be some issues in OMV.

**Comment by votdev** [comment]
Any new information from your side? To me the netplan configuration looks good; the DNS server and search list delivered by DHCP should be taken into action by systemd. If not, the problem might be in systemd.

**Comment by votdev** [comment]
Is `/etc/resolv.conf` a symlink to `/run/systemd/resolve/resolv.conf` on your system?

**Comment by meyergru** [comment]
Yes, it has. And I can see that at least the DNS server IP is coming from DHCP, but neither the search list nor the domain. The latter is unset, the former is ".".

**Comment by votdev** [comment]
I think the folliwing commits will fix the issue with `openmediavault 6.4.0`.

- https://github.com/openmediavault/openmediavault/commit/ccd4e18f18fa52c9c070c2b0d51c0c383ee7af36
- https://github.com/openmediavault/openmediavault/commit/763610607c95f7f76287b0b264754cf46e47edad
- https://github.com/openmediavault/openmediavault/commit/26d38cd7b1596ce7f93cad4b73d0c2cb9b9ce6ec

**Comment by votdev** [comment]
Has the issue been fixed with `openmediavault 6.4.0`?

**Comment by meyergru** [comment]
Yes, the search domains are set by dhcp (after upgrade, reboot and reconfiguration of the network interface).

**Comment by votdev** [comment]
OK, so `use-domains: true` is the right approach to fix the issue. Thx for testing.
