### ISSUE TITLE
file system : allow to change mount point

### ISSUE THREAD

**Issue by olaulau** [openmediavault/openmediavault#1561]
instead of /srv/[UUID], maybe user can enter a label so that it would mount on /srv/[label]
or maybe let user choose a complete mount point himself.
I know this could lead to errors, but those paths are really ugly.

**Comment by votdev** [comment]
> I know this could lead to errors, but those paths are really ugly.

You have already spotted the main problem here. I will not support things that will cause errors which results in more user support in the forum.

I know the paths are not comfortable, but they are unique, help to keep the database valid and prevent user errors. To support users the UI already provides solutions (e.g. copy the path to clipboard) that help them working with these paths. Normally the concept of OMV is that users do not come in touch with this paths, but when working with containers and Dockerfiles, this cannot be prevented.

Because of that i had to reject and close this issue.

**Comment by olaulau** [comment]
I understand, thanks for the explanations.
(and thanks for all the work on this beautiful project !)
