### ISSUE TITLE
We need better release notes.

### ISSUE THREAD

**Issue by sbe-arg** [openmediavault/openmediavault#1628]
**Is your feature request related to a problem? Please describe.**

Is dangerous to update continuously without a clear information what changes are.

**Describe the solution you'd like**

Pass the pr titles in the changelog as releases diff.

**Describe alternatives you've considered**
N/A

**Additional context**

All updates say 'various changes' without detailing the changes.

**Comment by votdev** [comment]
> All updates say 'various changes' without detailing the changes.

That's understandable, but i chose this path for the last releases because things weren't easy for laypeople to explain. This practice is not uncommon, for example when you update apps in the Apple app store, it doesn't say anything more than e.g. performance improvement or "We've fixed some bugs for you".

If users need more information they can find them in the Github commits.

> Pass the pr titles in the changelog as releases diff.

That's not possible because my workflow is different here. I also keep the changelogs very abstract so that even inexperienced users can understand them.

**Comment by sbe-arg** [comment]
Thanks for clarifying though.
