### ISSUE TITLE
Colour consolidation

### ISSUE THREAD

**Issue by ThirtySomething** [openmediavault/openmediavault#1639]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In the "Diagnostics -> Performance Statistics -> Disk I/O" in the RRD graph the colour for reading is blue and the colour for writing is red. Regarding the "Diagnostics -> Performance Statistics -> Network Interfaces" the colour for outgoing is red and the colour for incomming is blue.

Maybe I'm wrong, but I relate incomming network data with writing to disks and outgoing network data with reading from disks.

Therefore the colours should be swapped, either in the "Disk I/O" or in the "Network Interfaces" graphs to keep the intention. But this is a personal idea, maybe there are reasons for the current colour setup I don't know.

**Describe alternatives you've considered**
As alternative keep it as it is ;-)

**Additional context**
No.

**Comment by votdev** [comment]
I really do not see any connection points in here between disk and network I/O.

IMO it is clear that for the disk I/O the color red is right because you can assign disk writing with the key words expensive, dangerous, ... and then the warning color red is correct.

But for network I/O it is much more difficult because it depends on the user's view of what their priorities are here. For some of them output data is more important, for others the input.

For this reason, I will not change anything here. The color scheme is now established and will only confuse users if it is changed.

**Comment by ThirtySomething** [comment]
Okay, thanks for regarding the proposal.
