### ISSUE TITLE
Allow options like device type for smartctl to be selected in S.M.A.R.T GUI

### ISSUE THREAD

**Issue by Miyamoto72** [openmediavault/openmediavault#1667]
**Is your feature request related to a problem? Please describe.**
I run OMV on an Argon EON, which is a casing with an integrated USB-to-SATA adapter. These HDDs I put on there are accessible for storage, but SMART won't find them, because it is not set to the correct mode.
When I use `smartctl -d sat --scan` or `smartctl - d scsi --scan` I get a listing of my drives just fine, and they put out SMART info when invoked like `smartctl -d sat -a /dev/sda`

**Describe the solution you'd like**
Please make device types configurable in SMART settings GUI (and maybe more suitable options)

**Comment by votdev** [comment]
The problem is not OMV, it's located in the upstream smartmontools project. Your device is simply not in their database. The following posts are discussing that issue:

- https://docs.openmediavault.org/en/stable/faq.html
- https://github.com/openmediavault/openmediavault/issues/1619#issuecomment-1788959178
- https://forum.openmediavault.org/index.php?thread/50404-smart-statuses-are-not-being-checked-or-detected-by-omv-anymore/
- https://forum.openmediavault.org/index.php?thread/50161-after-update-from-6-9-6-1-to-2-smart-stopped-working-w-error

The solution is to:
- add your devices to the local database
- report it upstream to the smartmontools so that other users can benefit from that

The OMV project will not add the requested form field because of technical reasons (smartmontools apps are called at several places without having any knowledge about any settings in the OMV database) and it breaks the OMV philosophy of not being a webmin and only requesting the most necessary information from users; everything should be recognized automatically to make OMV accessible to non-experts.
