### ISSUE TITLE
Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist:

### ISSUE THREAD

**Issue by Dude234** [openmediavault/openmediavault#1668]
The following signatures could not be verified because their public key is not available:

OMV 6 the Last version.

The following problem has been occurring since an update this week.

According to the instructions, the following should help.

gpg --keyserver pgpkeys.mit.edu --recv-key xxxxxxxxxxxxx

gpg -a --export xxxxxxxxxxxxx | sudo apt-key add -

sudo apt-get update

The first command still works, but the second command always says unsupported file type.

Unfortunately I can't get any further despite researching here.

Do you have a solution for this?

Thanks in advance.
------------------------------------------------------------------------------------------------------------------

Folgendes Problem ist seit einem Update dieser Woche auftretend.
Laut Anleitung sollte folgender Weg helfen.

gpg --keyserver pgpkeys.mit.edu --recv-key  xxxxxxxxxxx
gpg -a --export xxxxxxxxxxx | sudo apt-key add -
sudo apt-get update

Erster Befehl funktioniert auch noch, aber bei dem zweiten sagt er immer unsupported Filetyp.
Leider komme ich trotz recherche hier nicht weiter.

Habt ihr hierzu einen Lösungsansatz?

Danke im voraus.

Fehl:12 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY xxxxxxxxxx
Fehl:9 https://download.docker.com/linux/debian bullseye InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY xxxxxxxxxx
Paketlisten werden gelesen… Fertig
W: http://ftp.uni-stuttgart.de/debian/dists/bullseye/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/custom-archive-key.gpg are ignored as the file has an unsupported filetype.
W: http://ftp.uni-stuttgart.de/debian/dists/bullseye-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/custom-archive-key.gpg are ignored as the file has an unsupported filetype.
W: GPG-Fehler: https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY xxxxxxxxxxxxxx
E: Das Depot »https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: GPG-Fehler: https://download.docker.com/linux/debian bullseye InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY xxxxxxxxxxxxxx
E: Das Depot »https://download.docker.com/linux/debian bullseye InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
root@openmediavault:~#  apt-key add /etc/apt/trusted.gpg.d/openmediavault.ky.binary.asc
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: '/etc/apt/trusted.gpg.d/openmediavault.ky.binary.asc' kann nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
W: The key(s) in the keyring /etc/apt/trusted.gpg.d/custom-archive-key.gpg are ignored as the file has an unsupported filetype

**Comment by votdev** [comment]
Are you using a 32bit image on a RasPi? There are known issues with that platform.

**Comment by Dude234** [comment]
Hello no, not that I know of. This is the normal OMV6 download image. Should probably be 64bit.

And the whole thing runs as a VM on a Vsphere 7.x

**Comment by Dude234** [comment]
Meine vermutung ist das es durch das letzte OMV extra plugin update welches die Tage rauskam verursacht wurde.

Bei meiner Maschine mit vsphere 8.x lief es ohne Probleme durch.

**Comment by ryecoaaron** [comment]
> My guess is that it was caused by the latest OMV extra plugin update that came out the other day.

Running "sudo omv-aptclean repos" should fix the docker and openmediavault-plugin-developer repos but nothing in any omv-extras plugins touch the debian repos or add the /etc/apt/trusted.gpg.d/custom-archive-key.gpg file.  I'm not sure what broke those.

**Comment by votdev** [comment]
IMO the file name `/etc/apt/trusted.gpg.d/openmediavault.ky.binary.asc` looks weird. I never saw such thing and OMV does not create file with such names.

**Comment by Dude234** [comment]
Thanks for the info...,


I hadn't noticed that with the incorrect naming of (ky) instead of key.

I'll have a look at it tomorrow and fix it myself if necessary. In the best case scenario, the updates might work again. 


I will report on the status as soon as possible.

**Comment by ryecoaaron** [comment]
The spelling isn't the issue.  omv and omv-extras aren't using any keys in /etc/apt/trusted.gpg.d/ and are explicitly referencing keys in /usr/share/keyrings/.

deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] http://packages.openmediavault.org/public/ sandworm main
deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] https://openmediavault.github.io/packages/ sandworm main
deb [signed-by=/usr/share/keyrings/docker.gpg arch=amd64] https://download.docker.com/linux/debian bookworm stable
deb [signed-by=/usr/share/keyrings/omvextras.gpg arch=amd64] https://openmediavault-plugin-developers.github.io/packages/debian sandworm main

installing the openmediavault-keyring 1.0.2-2 package and running:
omv-salt deploy run apt
omv-aptclean repos

should fix everything.

**Comment by c0ri** [comment]
I am still getting errors even after this.

When running omv-aptclean repos:

Err:10 http://httpredir.debian.org/debian bullseye-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Get:16 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:17 http://packages.openmediavault.org/public shaitan/main armhf Packages [13.6 kB]
Get:18 http://raspbian.raspberrypi.org/raspbian bullseye/contrib armhf Packages [60.2 kB]
Get:19 http://raspbian.raspberrypi.org/raspbian bullseye/non-free armhf Packages [106 kB]
Get:20 http://raspbian.raspberrypi.org/raspbian bullseye/rpi armhf Packages [1360 B]
Reading package lists... Done
W: GPG error: http://httpredir.debian.org/debian bullseye-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://httpredir.debian.org/debian bullseye-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

11. Saving current package list...

12. Updating plugin index...
Creating index of upgradeable packages ...
Creating index of plugins ...

----
root@omv:/etc/apt/trusted.gpg.d# md5sum /usr/share/keyrings/*.*
9f3702d8745994675fc9003c6e2b5b26  /usr/share/keyrings/docker.gpg
108ce460d5ebf0377dbe4f8067e9b990  /usr/share/keyrings/omvextras.gpg
bda1cfb385b749524320af719f455aad  /usr/share/keyrings/openmediavault-archive-keyring.gpg
8ce78103709148a43b57fc555c9550db  /usr/share/keyrings/openmediavault-keyring.gpg
3d17b8debcd512a5f607a9b2f6ee95c5  /usr/share/keyrings/raspberrypi-archive-keyring.gpg
d41d8cd98f00b204e9800998ecf8427e  /usr/share/keyrings/raspberrypi-archive-removed-keys.gpg
3d17b8debcd512a5f607a9b2f6ee95c5  /usr/share/keyrings/raspberrypi-archive-stable.gpg
7fd79741c7168b6a7e3fa59a2f4343cf  /usr/share/keyrings/raspbian-archive-keyring.gpg
root@omv:/etc/apt/trusted.gpg.d# ls -al /usr/share/keyrings/
total 36
drwxr-xr-x   2 root root 4096 Jun  6  2023 .
drwxr-xr-x 122 root root 4096 Apr 10  2023 ..
-rw-r--r--   1 root root 2760 Jan  1 23:28 docker.gpg
-rw-r--r--   1 root root 2289 Jan  1 23:28 omvextras.gpg
-rw-r--r--   1 root root 2256 Jun  3  2023 openmediavault-archive-keyring.gpg
-rw-r--r--   1 root root 1206 Jun  3  2023 openmediavault-keyring.gpg
-rw-r--r--   1 root root 1183 Jan 13  2022 raspberrypi-archive-keyring.gpg
-rw-r--r--   1 root root    0 Jan 13  2022 raspberrypi-archive-removed-keys.gpg
-rw-r--r--   1 root root 1183 Jan 13  2022 raspberrypi-archive-stable.gpg
-rw-r--r--   1 root root 1233 May 29  2012 raspbian-archive-keyring.gpg

Any ideas?

**Comment by ryecoaaron** [comment]
> I am still getting errors even after this.

It looks like you have a 32 bit RPi install.  You should disable backports (button to do it in omv-extras).

**Comment by c0ri** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

That did the trick, thanks!
