### ISSUE TITLE
S3 plugin: incorrect port

### ISSUE THREAD

**Issue by marmack95** [openmediavault/openmediavault#1701]
When you enable S3 plugin, OMV create startup scripts: /etc/systemd/system/container-minio-app.service and /etc/systemd/system/pod-minio.service ...

When you do not use certificate (https), the script /etc/systemd/system/container-minio-app.service use port console 9001, as it show in webUI.
When you used a certificate, the same script use port console 8080, but webUI indicate 9001.

In the Minio documentation port 8080 is the default port for HTTP and port 9001 is for HTTPS.

If you take a look to the file /var/cache/salt/minion/files/base/omv/deploy/minio/files/container-minio-app.service.j2, you will found the mistake:
`ExecStart=... --console-address ":{{ ssl_enabled | yesno('8080,9001') }}" {{ cmd_args }}`

As WebUI does not make difference between HTTP/HTTPS, /var/cache/salt/minion/files/base/omv/deploy/minio/files/container-minio-app.service.j2 script could not use port 8080.

You can replace:
`--console-address ":{{ ssl_enabled | yesno('8080,9001') }}"`

with:
`--console-address ":9001"`

If you decide to manage the case of HTTP (:8080) / HTTPS (:9001) in WebUI, you must just reverse the ports notation:
`--console-address ":{{ ssl_enabled | yesno('9001,8080') }}"`

**Comment by votdev** [comment]
When HTTPS is enabled, then there is a [Caddy2 reverse proxy container](https://github.com/openmediavault/openmediavault/blob/a5370c388210b20a893c8912fc5073cc23861e02/deb/openmediavault-s3/srv/salt/omv/deploy/minio/files/Caddyfile.j2#L7) running in the pod. This is communicating on port 8080 unencrypted within the minio pod. This has been done so that the proxy and the minio container do not interfere with the same ports. Which port is used inside the pod is totally irrelevant, it could be 1234 as well.
