### ISSUE TITLE
checkboxes and reset to dashboard

### ISSUE THREAD

**Issue by govwin** [openmediavault/openmediavault#1729]
**Is your feature request related to a problem? Please describe.**
1. I am always frustrated when the OMV throws me to the dashboard whenever I install a package. Let the UI stay where it is.
2. I am always frustrated when the OMV needs too many click to install packages. Need checkboxes and then install many at once.

**Describe the solution you'd like**
1. Let the UI stay wherever it is. Update only the exact content that was modified. For example, if I installed a package, do not update the entire page and throw the UI to the dashboard page. Update only that one option to show the change to "installed".
2. Provide checkboxes to let me choose whatever plugins I need and then batch install.

**Describe alternatives you've considered**
One liner apt install package1 package2 ....... but I don't know the exact package names.

**Additional context**

**Comment by votdev** [comment]
> Let the UI stay wherever it is. Update only the exact content that was modified. For example, if I installed a package, do not update the entire page and throw the UI to the dashboard page. Update only that one option to show the change to "installed".

The page reload is exactly doing that, it updates the UI with the latest changes that are happened due to the package installation. There is no other way.

> Provide checkboxes to let me choose whatever plugins I need and then batch install.

This was possible in previous versions but has been removed with reason because it makes users confused what they have to install and what not. Power users can go to the CLI if they want to selectively install updated packages.

I'm closing this issue because the current approach of the issues mented here will not be changed.
