### ISSUE TITLE
Create file system candidates includes zfs members

### ISSUE THREAD

**Issue by rmstrait** [openmediavault/openmediavault#1735]
When creating a new file system disks from a zfs pool are listed as candidates.

1. Create a ZFS pool on available disk/s
2. Select Storage, File Systems, Create and mount a file system.
3. Select file system type
4. Click on "Select a device ..."
5. Observe disk members from zfs pool listed in drop down menu.

**Expected behavior**
Disks which are in use and blkid shows are of "TYPE="zfs_member" ought to be excluded from the candidate list when creating new filesystems. https://forum.openmediavault.org/index.php?thread/51955-create-new-fs-shows-zfs-pool-disks/&postID=386030#post386030
![Untitled](https://github.com/openmediavault/openmediavault/assets/71531321/f04fadf2-a1a7-4c0d-8c12-a3741a65a7a1)

[URL link to forum post]
(https://forum.openmediavault.org/index.php?thread/51955-create-new-fs-shows-zfs-pool-disks/&postID=386021#post386021)

- OS version: Linux 6.1.0-18-amd64 Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
- openmediavault version: 
- ii  openmediavault                       7.0.4-2                              all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                7.1.2                                all          backup plugin for OpenMediaVault.
ii  openmediavault-cputemp               7.0                                  all          cpu temperature plugin for openmediavault
ii  openmediavault-diskstats             7.0-2                                all          openmediavault disk monitoring plugin
ii  openmediavault-iperf3                7.0.1                                all          OpenMediaVault iPerf3 plugin
ii  openmediavault-kernel                7.0.3                                all          kernel package
ii  openmediavault-keyring               1.0.2-2                              all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-kvm                   7.0.11                               all          kvm plugin for OpenMediaVault.
ii  openmediavault-locate                7.0                                  all          locate plugin for OpenMediaVault.
ii  openmediavault-mounteditor           7.0.1                                all          openmediavault mount editor plugin
ii  openmediavault-omvextrasorg          7.0                                  all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-remotemount           7.0                                  all          Remote mount plugin for OpenMediaVault.
ii  openmediavault-resetperms            7.1                                  all          Reset Permissions
ii  openmediavault-sharerootfs           7.0-1                                all          openmediavault share root filesystem plugin
ii  openmediavault-symlinks              7.0                                  all          OpenMediaVault symlinks plugin
ii  openmediavault-wetty                 7.0-2                                all          openmediavault WeTTY (Web + TTY) plugin
ii  openmediavault-zfs                   7.0.5                                amd64        OpenMediaVault plugin for ZFS

**Client**
- Browser: Chrome

**Comment by votdev** [comment]
The ZFS plugin is responsible to collect the disks that are used by ZFS and report them back to the core system which then filters the available disks based on that info.

**Comment by votdev** [comment]
@ryecoaaron Can you confirm that problem when the ZFS plugin is installed?

What i can say is that if the ZFS plugin is NOT installed, then OMV does not know anything about ZFS. That is with reason because ZFS is no nativ Linux file system and not official included in the kernel. So OMV ignores it, but can handle it correct if the ZFS plugin is installed.

**Comment by ryecoaaron** [comment]
I will have to look.  I don't remember how a backend should mark a drive as used or referenced.

**Comment by votdev** [comment]
> I will have to look. I don't remember how a backend should mark a drive as used or referenced.

The [FileSystemMgmt::getCandiate](https://github.com/openmediavault/openmediavault/blob/48a6b291079183bf03eb072caa4c5e8c4fe2d3b6/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L539) RPC gets a [list of all existing file systems](https://github.com/openmediavault/openmediavault/blob/48a6b291079183bf03eb072caa4c5e8c4fe2d3b6/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L548) and a list of [all storage devices](https://github.com/openmediavault/openmediavault/blob/48a6b291079183bf03eb072caa4c5e8c4fe2d3b6/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L545) that are not used by any MD, LVM, ...
The diff of those devices is the list of devices that can be used to create a new file system because those are not used by a MD, LVM, RAID or already have a file system on it that is supported by OMV.

**Comment by ryecoaaron** [comment]
This might be very complicated to fix since the zfs plugin looks like it is using the filesystem name for the devicefile.  I don't know zfs well enough nor the zfs backend to feel comfortable figuring out what needs to be changed.

**Comment by rmstrait** [comment]
Maybe it would help if ZFS wasn't a plugin and could be selected as a file system like BTRFS or EXT4.

**Comment by votdev** [comment]
> Maybe it would help if ZFS wasn't a plugin and could be selected as a file system like BTRFS or EXT4.

ZFS is not official part of Debian nor the Linux kernel because of licensing issues. That's why it will never be supported officially by OMV.
