### ISSUE TITLE
Allow arbitrary UID/GID in rsync module.

### ISSUE THREAD

**Issue by LnLcFlx** [openmediavault/openmediavault#1767]
**Is your feature request related to a problem? Please describe.**
I have data on a drive with UID 1000 but no user on the OMV host with that UID.
I still want to write to that directory with that UID over rsyncd, but I can only select users that exist on the host.

**Describe the solution you'd like**
I would like to be able to just type in text / the UID (and GID) in the "User" and "Group" field when creating an Rsync module.

**Comment by votdev** [comment]
I think you can use the user import feature to create such a user with the specified UID/GID.

**Comment by LnLcFlx** [comment]
Thank you for the answer and this nice piece of software!

I do think this is quite tedious especially if you lots of different UIDs.
But I am new user and don't know if that's just the OMV philosophy of handling users (every linux user on the host must be also in OMV).

But the Rsync tab also shows you system internal linux users that are not shown in the OMV User Management tab.
In that context, I think, typing in raw UIDs should be possible as well.
Or, to to stay consistent, only OMV users, which would be even more tedious IMO.

**Comment by votdev** [comment]
> But I am new user and don't know if that's just the OMV philosophy of handling users (every linux user on the host must be also in OMV).

That's the philosophy. You can use LDAP if you have a centralized user management. In the SoHo area where OMV is located, however, there should not be so many users in my opinion. In addition, the rsync user is only the owner of the files, the rights in the shared folder can be adjusted so that other users can also access this data.

> But the Rsync tab also shows you system internal linux users that are not shown in the OMV User Management tab.

OMV is respecting the settings in `/etc/login.defs` which specifies the ranges of system and normal users. You can adapt that variables to configure the bahaviour.
