### ISSUE TITLE
Feature Request: Virt-manager and kvm

### ISSUE THREAD

**Issue by jdainen** [openmediavault/openmediavault#222]
Virt-manager would add vm's straight to the omv menu with one click.  Kvm is more powerful and adaptable than virtualbox which is currently available in omv extras.

**Comment by brando56894** [comment]
Understood, installing via apt is pretty easy but it would be neat to have it available in the GUI. 

In my opinion installing Cockpit is sort of redundant since it provides nearly the same features that OMV provides (RAID management, user management, docker management, etc...) it's just slightly more built out.

Would it be possible to utilize code from Proxmox since both projects are based off of Debain?

**Comment by ryecoaaron** [comment]
You can install cockpit from the gui if you use the apttool plugin.

It is redundant if you install all of the cockpit packages.  If you just install the machines packages, there is very little that is redundant.  The point is that it is maintained and works well.  No dev has time (or possibly desire or experience with kvm) to implement this plugin.

kvm stuff is integrated thoroughly through the proxmox interface and has custom scripts/programs to make working with kvm easier.  Using code from proxmox would be very difficult.  Personally, I virtualize OMV on VMware and proxmox.  So, I have no need for a virtualization plugin on OMV.
