### ISSUE TITLE
Unable to create vlan interface on Raspberry Pi

### ISSUE THREAD

**Issue by bdk907** [openmediavault/openmediavault#230]
Hardware: RaspberryPi 3
OMV: 4.1.14-1

When creating a vlan interface, syslog shows an error message:

```
Dec  8 11:53:12 nas-pi ifup[4116]: Error: argument "enxb827eb1e62b3.42" is wrong: "name" too long
```

Raspberry PI's predictable interface name is 15 bytes long. I believe that the max length per the kernel is 16 bytes,

```
root@nas-pi:~# ip link
2: enxb827eb1e62b3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:1e:62:b3 brd ff:ff:ff:ff:ff:ff
root@nas-pi:~# 
```
Can OMV allow us to input custom name for a vlan interface such as 'vlan.X' or 'eth0.X'?

The 'Name' field, when creating a vlan interface is marked 'readOnly' in /var/www/openmediavault/js/omv/module/admin/system/network/Interfaces.js.

I've commented out the 'readOnly' line in Interfaces.js, reloaded the nginx, added a vlan using 'eth0' as the name and saved the config but the predictable name + '.vlan' shows up when displaying the interfaces.

I've worked around the issue for now by creating a vlan_fix file that uses 'ip' commands and running the script via rc.local. It would be preferable to use the OMV UI.

**Comment by votdev** [comment]
Allowing the user to edit the interface name does not match the OMV philosophy and design. Using bios device names is not a good decision because they can change. Thus OMV ONLY uses predicable device names everywhere.
Your problem seems to be a bigger issue which MUST be fixed upstream, it's not the job of OMV.

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1567744
https://github.com/systemd/systemd/issues/2407
https://lists.ubuntu.com/archives/ubuntu-devel/2016-April/039302.html
