### ISSUE TITLE
Feature Request:  Add togle switch to automatically keep OMV and plugins Up to date

### ISSUE THREAD

**Issue by Samuel12321** [openmediavault/openmediavault#274]

**Comment by ryecoaaron** [comment]
Why?  This can be dangerous.  If you really want to do this, create a scheduled job from the omv web interface with the command omv-update run as root.  But don't say I didn't warn you...

**Comment by Samuel12321** [comment]
I dont want to seem rude, but you dont have to turn it on.
Some people may want to setup their server and leave it without having to update it every week manually, and its better thatr they keep up to date for security reasons than not.
How is it be dangerous, i understand that there could be buggy releases or incompatability issues, but not to the degree you are suggesting.
I have created a sceduled task to do precisely that, and it has been running without issues for over a year.

**Comment by h45rd** [comment]
People who would even want to consider unattended server upgrades should really know what they are doing. And actually have an eye on the changelogs. This is no a _set and forget_ type of thing.

For them, adding a simple cronjob should not pose a problem.
In my book stability would trump any 0-sec security concerns when it comes to a possibly infrastructure-relevant server - often administrated by laymen - that in best/most cases should only be reachable from within their LAN.

If there's a checkbox, people are going to use it. And then come crying when e.g. their system suddenly does not boot anymore because of a rare kernel bug in upstream.. 20 updates ago.. They are just noticing now, because of the first server reboot in a month... And of course they can't recover, because they do not have a backup routine in place.. Good luck debugging that :D

Just my 2c..

**Comment by ryecoaaron** [comment]
@Samuel12321 Actually there are plenty of upgrades that are as dangerous as I am suggesting.  I have personally supported many, many systems on the forum that have broke due to kernel upgrades, virtualbox upgrades, zfs upgrades, docker upgrades, and just about anything else that compiles a module.  

How would you like to be running a system with virtualbox VMs running on a zfs filesystem where the kernel was upgraded to a version not supported by virtualbox or zfs breaking everything?  This has happened almost every time there is new major kernel version released in backports (default for OMV).  Sure, people "shouldn't" enable it but they will.  Some because they don't know how things work but auto updates "sounds" good.

I use automatic updates on almost a hundred Ubuntu systems at work (and it works well) but they are quite simple compared to some peoples OMV installs with tens of services.  I'm not the one who be implementing this.  I was just giving my opinion.  If I remember correctly, Volker has shot this down a few times.

**Comment by Samuel12321** [comment]
good points, will close this.
thanks for the suggestions.
