### ISSUE TITLE
WiFi won't work on download

### ISSUE THREAD

**Issue by HarryET** [openmediavault/openmediavault#275]
When I first boot the is I can't use my WiFi card and I don't have any ethernet ports/wires to use to update it to the latest stretch version ... What's the solution or is it a bug with the raspbian version ?

**Comment by ryecoaaron** [comment]
The official OMV installers and the ARM board images don't support wireless for install.  I don't think the official Debian installer does either.  Why can't you temporary give it a network port for install? Otherwise, you will need to look at a wireless bridge.

**Comment by HarryET** [comment]
Yes but I don't have any ethernet cables but I have a wireless adapter ... Can I not use that ?

**Comment by ryecoaaron** [comment]
No.  You will have to buy a cable I guess.

**Comment by HarryET** [comment]
Fixed ... https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html .. follow the steps

**Comment by mxj4** [comment]
@votdev The latest OMV 6.x installer can configure wifi networks, however, the configuration is not written to the installed OS, resulting in an OS without network, if the machine running OMV has no ethernet interface. Can we reopen this issue?

**Comment by votdev** [comment]
> @votdev The latest OMV 6.x installer can configure wifi networks, however, the configuration is not written to the installed OS, resulting in an OS without network, if the machine running OMV has no ethernet interface. Can we reopen this issue?

Which configuration is not written? Is the `/etc/network/interfaces` file not written or is the content of this file not [synced](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/confdb/populate.d/40interfaces.sh) into the OMV database?

**Comment by ryecoaaron** [comment]
I'm guessing this is related to the install script not OMV.  The install script only supports wifi in a very limited set.  Guessing this is an rpi and wifi was configured with the rpi imager?  Please start a thread on the forum.

**Comment by mxj4** [comment]
I tried installing the OS again and here is what I found.

Looks like the installation process is using a program called debian-installer, there is a 10 year-old upstream thread complaining d-i netcfg package does not write wireless config to `/etc/network/interfaces`: https://groups.google.com/g/linux.debian.maint.boot/c/IKfBlMq8_mI in the thread, someone mentioned a workaround:

> Before tearing down the WiFi interface at the very end of
> the installation, the d-i should simply copy the existing
> /target/etc/network/interfaces file to /target/root/, perhaps
> named as etc-network-interfaces-at-installation, with its
> permissions set to 600.
> 
> When the machine is rebooted, it is now straightforward for
> the sysadmin to login and simply:
> 
>  \# mv /root/etc-network-interfaces-at-installation /etc/network/interfaces
>  \# ifup w\<TAB\>\<RETURN\>
> 
> to give themselves WiFi connectivity (using sudo if necessary). 
Not sure why this is a workaround, if `/target/etc/network/interfaces` already has wireless config in it, isn't d-i already updating `/etc/network/interfaces` of the installed OS properly?
And I did check `/target/etc/network/interfaces` near the end of the installation, it does have wireless configurations in it as expected.
I also checked d-i netcfg package source code, it does have logic to copy `/etc/network/interfaces` from installer environment to `/target/etc/network/interfaces`: https://salsa.debian.org/installer-team/netcfg/-/blob/1.140/base-installer.d/40netcfg

My understanding is, `/target` is where d-i mount the installation destination root, so if `/target/etc/network/interfaces` is written, it means `/etc/network/interfaces` of the installed OS is written. But after the first reboot, `/etc/network/interfaces` of the installed OS becomes the default value, which only has loopback interface!

Is `/target` actually something else rather than the installation root? Why would someone in the upstream thread suggest copy `/target/etc/network/interfaces` to another file so that later admin can copy the file back to `/etc/network/interfaces`, if `/target/etc/network/interfaces` in the installer environment and `/etc/network/interfaces` in the installed environment are the same file?

Or is it possible that debian do some other magic at first boot, like reset `/etc/network/interfaces` to its default value?

**Comment by flmaxey** [comment]
While the following opinion doesn't address the technical issue with Debian and the R-PI imager:

From a support standpoint, there's the question of whether it's a "good idea" to build an OMV server over a **wireless link**.  I don't believe it is.  It adds too many variables for PC Novices and new OMV users to fail that will, inevitably, end up on the forum.  

If the first OS boot and OMV installation are done over a wired connection, along with logging into the GUI for the first time, configuring the wireless interface is a simple matter.  This approach is consistent with the current build process and existing documentation.  
(Adding a build doc that includes the R-PI imager, using a _wired_ connection, is in progress.)
