### ISSUE TITLE
Proposal: Allow execute on shared folders (mount w/out noexec)

### ISSUE THREAD

**Issue by y2k4life** [openmediavault/openmediavault#290]
I did not know I had an issue with executing on a docker container using a shared folder. The reason I believed I could execute is because when changing the ACL for a share the options are read/write/execute. Interesting enough when you add a share the GUI only shows read/write. If you change the privileges you don't see execute. To further the confusion after adding a share and looking the ACL, execute is set and it is an option in the drop downs.

Part of this is due to my (mis)understanding of execute bit at the file/folder level and what execute or noexec means on the mount point. 

Some of these suggestion might be off, but I think the point I'm getting at can be understood. Again I don't understand the overlap between noexec and the execute bit and why you have noexec and yet the bit turned on. @ryecoaaron explained a little bit, I will do more research.

Here are some suggestions

1. The ability to set/remove the noexec in the GUI. Maybe in advance settings. Instead of hacking config file, environment variables and fstab.
2. If this is a security concern than express there is a concern with security when turning it off.
3. Add some consistency to the sharing parts of the GUI. Some actions show execute as an option while others don't.
4. If noexec is set then don't show execute on ACL. Otherwise add execute to the drop down options and to the grids.

I know with data you don't need to execute, but I think by expanding OMV to have docker, the growth and acceptance of docker the doors are opening to more possibilities for OMV beyond just data. When I first set out on my NAS journey I thought all I was going to have was storage. Now I have a development server, awesome! I can bring the cloud into my development shop! Next it will be multiple OMVs and Kubernetes!

Before I could do anything though I had to spend two hours figuring out why I see execute turned on in the ACL, but I can't execute.

**Comment by MoralCode** [comment]
in trying to solve a `noexec` related issue, I have found other people with similar issues across different software like plex, nextcloud, mariadb etc.


Plex's transcoder doesnt like to run under noexec: https://forums.plex.tv/t/transcoder-crashing-unknown-decoder-h264/205798/4
The installation video for nextcloud specifically guides people to edit the config files to turn off noexec: https://youtu.be/T_2csDJFa2k?t=289 https://www.youtube.com/watch?v=f1aOiFtBG3Q
This affects a potentially large number of containerized applications https://discourse.linuxserver.io/t/error-in-every-linuxserver-docker-container/1357/7 and some people have reported issues with their RAID arrays after this sort of manual editing of config files https://forum.openmediavault.org/index.php?thread/30083-raid-issues-after-noexec-plex-fix/

Since this seems to be a fairly standard usecase for openmediavault, I agree that it would be really nice to have the ability to change some of the more advanced mounting options (particularly `noexec`) for the more advanced use-cases, even if it's only to ensure that anyone who wants to make a change to their config like this has to click through an "advanced settings" section and/or a warning about potentially breaking their system when changing mounting options

**Comment by mi-hol** [comment]
@votdev is this an enhancement worth to be considered for 6.x?

**Comment by votdev** [comment]
With [openmediavault 5.5.10](https://github.com/openmediavault/openmediavault/commit/a5451055c465639e3ff4efb8a4ff66c8763b4f94#diff-ee482718d82bac62202881c062b16b09829f650d2850bed6c4c109be2ab4107e) the `noexec` mount option has been removed.
