### ISSUE TITLE
AMD iGPU driver broken.

### ISSUE THREAD

**Issue by murphyDeffa** [openmediavault/openmediavault#296]
Screen buffer is junok when try to use AMD Ryzen 2400G. All is ok on install timer window, after that all screen is scrambled.
![51814885_322046871762720_8741357542375948288_n](https://user-images.githubusercontent.com/47643467/52812893-35ae6400-30a1-11e9-9ff8-88f377013a65.jpg)

**Comment by votdev** [comment]
I'm sorry to say but this issue is out of range of the project. OMV uses the official Debian package repository and kernels and does NOT maintain it's own packages.

Have you tried to install Debian via netinst ISO images and manually install OMV afterwards? Check out https://forum.openmediavault.org/index.php/Thread/21234-Install-OMV4-on-Debian-9-Stretch/ how to install OMV on a previously installed Debian. This is the only workaround that we can provide.

If you use an image based on Raspian, please contact them because they maintain the images that are used to install OMV.
