### ISSUE TITLE
Disk I/O tab in system information is missing filesystem labels

### ISSUE THREAD

**Issue by godfuture** [openmediavault/openmediavault#341]
The disk usage tab shows filesystem labels aside of its device name "/dev/dm-x" which helps a lot to identify the data. But unfortunately these labels are not shown in the disk i/o tab. It would be a lot easier, if the labels were shown in the disk i/o tab, too.

OMV 4.1.22.1

**Comment by votdev** [comment]
The disk usage tab shows information about the filesystem, so the label is known. The disk i/o tab shows information from the raw device, there is now knowledge about the filesystem, thus no label is known and can be displayed. Keep also in mind that a device can contain multiple filesystems, so, which label should be displayed if it would be possible to retrieve the information easily without huge costs.

Because of that this feature request can't be implemented and will be closed.
