### ISSUE TITLE
What's the official way to keep OMV up to date?

### ISSUE THREAD

**Issue by alugowski** [openmediavault/openmediavault#358]
The install .iso is 4.1.3, so about a year or 18 versions old. What's the best way for a user to get an up to date installation, and how to keep it up to date?

This should ideally be explained on the website download instructions. Especially since the new version announcement announces a version that is not available to download.

**Comment by alugowski** [comment]
Should the user manually update the openmediavault package? Is that enough?

**Comment by ryecoaaron** [comment]
The first thing I do after installing is visit the Updates tab in the web interface.  This is why the ISO doesn't need to be updated all the time.  Keeping the system up to date requires a periodic visit to the Updates tab.

**Comment by hegyre** [comment]
Hello,
Had the same issue yesterday.

To me it should be auto-updated after the first boot so we don't even have to care.

However, since it's not the case yet, I enabled ssh, logged as root, and did this command:
`omv-update`

**Comment by ryecoaaron** [comment]
Unless you use the Debian netinstall ISO, even Debian doesn't auto update on first boot.  Some people with slow or no connection may not want this.  You have to login to the web interface to configure the system, why not just go to the Update tab and fully update the system?  No need to use the command line.

**Comment by alugowski** [comment]
Ah, so all three of us did it differently. I did `apt-get upgrade`.

I ask for the *official* method to avoid problems when everyone does it differently and systems diverge over time.

**Comment by alugowski** [comment]
I agree with @ryecoaaron that it shouldn't auto-update. I do think that the GUI could cheaply *check* for updates, and offer a single button to perform the update that would bring everything OMV to the latest version.

I didn't know `omv-update` exists, so it sounds like there could be a big giant "Update OMV" on the Updates page that tells you your version, the latest version, and simply calls that command.

**Comment by alugowski** [comment]
> why not just go to the Update tab and fully update the system?

Because that tab is simply a list of apt packages, most of which are things the user should never touch or worry about. A long-time Linux user will understand, but to anyone else it's not immediately clear what to do. I assume you mean the user is expected to know to select all and update, or are they expected to find just the openmediavault package and update only that?

**Comment by votdev** [comment]
OMV will n ever support auto-update because packages may break the system. Updates MUST be triggered after a review of the admin. 
If someone wants auto-update, there is a Debian package that will do that. There is also a email sent when packages are available after notification is enabled.

**Comment by alugowski** [comment]
@votdev this is asking what the official way to trigger an update is.

**Comment by votdev** [comment]
Use the omv-upgrade CLI command or the UI. Alternatively use the Debian way 
‘’’
# apt-get update
# apt-get upgrade
‘’’

**Comment by smokku** [comment]
We have a Dashboard, which is displayed after admin logs in.
It has a System Information widget. We could extend this widget with _system update_ row, showing whether the system is up to date and giving a simple link to update otherwise.

This is how OPNSense does it:
![Zrzut ekranu z 2019-05-03 09:21:11](https://user-images.githubusercontent.com/147687/57124132-d4835c00-6d84-11e9-9014-62802eecc0f0.png)

**Comment by hegyre** [comment]
@votdev ,
about these commands:

```
apt-get update
apt-get upgrade
```

The [documentation here](https://openmediavault.readthedocs.io/en/latest/various/apt.html?highlight=update) says that the command used by `omv-update` are:
`apt-get update && apt-get –yes –force-yes –fix-missing –auto-remove –allow-unauthenticated –show-upgraded –option DPkg::Options::=“–force-confold” dist-upgrade`

What is the best command to use then ? the omv-update wrapper or the debian usual apt commands ?

Regarding the auto-update I told above, I was just saying that there is no auto-update on the **first** boot.
And yes I always used the netinstall version of Debian which auto-update itself on first install.

Even Windows 10 installation will auto-update during the initial install if you are connected to Internet.


To me it's clear to not auto-update a system once it has been configured, but since it's 1st boot, we have nothing to lose and could be better for user experience...

However I did not want to open a debate here, this is not the topic...

**Comment by ryecoaaron** [comment]
omv-update is meant to run without user interaction and prevent people from choosing the wrong option.  apt-get update/upgrade will be fully interactive.

first boot or not, the system shouldn't auto update in many discussions we have had about this.  netinstall doesn't autoupdate, it gets its files from the servers.  It doesn't actually update.  Its files are just up to date because it retrieves them at install time.  A NAS has less reasons to be fully updated than a Windows desktop which has browsers and user interaction.

**Comment by votdev** [comment]
omv-upgrade does everything non-interactively, the Debian way might require user interaction. Simply use the command of your choice, both will finally do the same.

**Comment by donhwy** [comment]
apt-get upgrade vs apt-get dist-upgrade? Most other projects I use recommend dist-upgrade. I have often used that with OMV without issue. I also use the web ui  from time to time, so maybe I have just been lucky?

**Comment by ryecoaaron** [comment]
@donhwy  I always use dist-upgrade myself

**Comment by alugowski** [comment]
Doesn't `apt-get dist-upgrade` potentially upgrade the kernel? That would be a risk if using ZFS since the module may not work with the new kernel.

**Comment by ryecoaaron** [comment]
With Debian, the only time there is a kernel upgrade that would break zfs is when the backports kernel is still stabilizing.  The regular kernel always stays the same major and minor version.  And lately, you really want kernel updates because there are security fixes in it.  The possible zfs break is avoided if you use the proxmox kernel.

Do you never upgrade the kernel?

**Comment by alugowski** [comment]
> With Debian, the only time there is a kernel upgrade that would break zfs is when the backports kernel is still stabilizing. 

Can this ever happen if one uses `dist-upgrade`?

> Do you never upgrade the kernel?

Yes. That was one of the things I upgraded upon first install of OMV, since the kernel in the .iso was old. The upgrade went from 4.14 to 4.19 if I recall correctly. The ZFS plugin was unable to build the kernel module. So honestly, I've no idea what the expectations for upgrades are, hence asking this question.

**Comment by ryecoaaron** [comment]
> Can this ever happen if one uses dist-upgrade?

I don't understand what you are asking?  Other than the initial 4.14 to 4.19 upgrade (that you saw), the 4.19 kernel has stabilized on Buster.  So, stretch-backports should never get a newer kernel.  Just fixes.

> The ZFS plugin was unable to build the kernel module.

The ZFS plugin doesn't build the kernel module.  The zfs-dkms package does.  So, if it fails, there is little the plugin can do about this.

> So honestly, I've no idea what the expectations for upgrades are, hence asking this question.

The official way to keep OMV up to date is the same as the official way to keep Debian up to date - [link](https://www.debian.org/doc/manuals/debian-faq/ch-uptodate.en.html).  I do think there should be a button to execute omv-update in the Updates tab instead of selecting all the packages but they basically do the same thing.

**Comment by D3ltorohd** [comment]
So i installed Omv 5.0.5. After this i go to the shell and type apt update and apt dist-upgrade. After this, i make an reboot, omv seems to be working. But when i go to messages i become the following error ..

`Fehler #0:
OMV\Json\SchemaValidationException: : The value is not an object. in /usr/share/php/openmediavault/json/schema.inc:391
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(285): OMV\Json\Schema->validateObject(Array, Array, '')
#1 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(Array, Array, '')
#2 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate(Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(179): OMV\Rpc\ParamsValidator->validate('[]')
#4 /usr/share/openmediavault/engined/rpc/notification.inc(149): OMV\Rpc\ServiceAbstract->validateMethodParams(Array, 'rpc.common.obje...')
#5 [internal function]: Engined\Rpc\Notification->get(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#8 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Notification', 'get', Array, Array, 1)
#9 {main}`

So i should never use this, only over updates in the GUI ? I will have the latest debian version.

**Comment by ryecoaaron** [comment]
clear your browser cache. updating either place is fine.

**Comment by D3ltorohd** [comment]
Thanks, after crtl+F5 it works again, no error !! Fine thanks
