### ISSUE TITLE
While updating, the window shows "TypeError: 'NoneType' object is not callable" messages

### ISSUE THREAD

**Issue by Wikinaut** [openmediavault/openmediavault#407]
### Description of issue/question
When I use the Aktualisierungsverwaltung on one of my OMV systems, I notice 
```TypeError: 'NoneType' object is not callable```
messages.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
![grafik](https://user-images.githubusercontent.com/1151915/60765004-a1668d00-a093-11e9-80f5-5eab9a140691.png)

**Comment by votdev** [comment]
This is a known issue which can be ignored.

https://forum.openmediavault.org/index.php/Thread/22805-OMV-4-Python-error/
https://github.com/openmediavault/openmediavault/issues/138
https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?postID=155621#post155621

**Comment by Julian-O** [comment]
Just to elaborate so others with the problem can understand:

**The errors can be ignored.**

[There was a bug](https://bugs.python.org/issue29519) in Python which caused these spurious errors.  This bug was fixed across a range of Python versions in 2017. In the Python 3.5 series it was fixed in Python 3.5.4.

However, OMV doesn't directly install Python, but instead relies on Debian distributions. As of late 2019, the [latest Python 3.5 available on Debian](https://packages.debian.org/search?keywords=python3.5) is 3.5.3. 

If/when Debian release a new package with a newer version of Python 3.5, this problem will go away, which is why this issue has been closed.

(Alternatively, when OMV is eventually updated to support Python 3.6, 3.7 or 3.8.) 

There is a [workaround](https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?postID=164703#post164703) you can apply if the problem bothers you, or the errors can just be ignored.

**Comment by ryecoaaron** [comment]
This is not an issue on OMV 5.x that uses Debian Buster which uses Python 3.7.3.
