### ISSUE TITLE
Make table items selectable

### ISSUE THREAD

**Issue by Julian-O** [openmediavault/openmediavault#494]
### Description of issue/question

The Web UI for openmediavault contains a number of tables with useful information that would be nice to copy-and-paste into other documents.

e.g.:
* Disk models and serial numbers in the Disks table
* System logs
* Kernel and Version information from the System Information page.

However, via various CSS (see `theme-triton-all_1.css`) and HTML (`unselectable="on"`) mechanisms required for each of the major browsers, selectability has been turned off.

This makes it unnecessarily hard to copy-and-paste useful information, for no benefit.

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

* Open the System Information web-page. 
* Double click on the Kernel version to select it, in prepapration to copy it. 
* Note it is not selected.

### Versions report

4.1.26-1 (Arrakis)
^ I had to type this in by hand, like a chump! :-)

**Comment by votdev** [comment]
This is a default by ExtJS and with reason, don’t forget touch device users. I think making tables text selectable will break the touch capability.

Second, I don’t plan to make changes to the ExtJS code anymore because of working on the new UI.

Because of that don’t expect this feature before OMV6 that will ship a new UI.

**Comment by Julian-O** [comment]
Thanks for the response.

I had heard a UI upgrade was in the works, which is why I didn't try to submit my own fix.

I'm not clear on why text selectability might impact on touch ability - there is plenty of selectable text in many tables on many web-sites and tablets work fine, but perhaps I am missing some point here.

**Comment by PrplHaz4** [comment]
Agree it's pretty annoying not being able to select text.  Since the log viewer table is not interactive at all, it shouldn't cause issues with touch to enable text selection.

A quick google seems to reveal there have been on and off issues with `enableTextSelection: true` in the 6.x versions of ExtJS.  I tried a few quick hacks locally but wasn't able to get it working.

ref:
https://stackoverflow.com/questions/7277752/making-extjs-4-grid-content-selectable
https://www.sencha.com/forum/showthread.php?308143-classic-enableTextSelection-not-working-in-ExtJS-6-0-2-nightlies

**Comment by mi-hol** [comment]
@votdev, this seems already implemented, right?

**Comment by votdev** [comment]
Done in OMV6
