### ISSUE TITLE
Incorrect hosts file generated

### ISSUE THREAD

**Issue by cryptobank** [openmediavault/openmediavault#510]
### Description of issue/question

I've setup dnsmasq in OMV and while checking that my hosts correctly resolve, I noticed that running dig on the hostname of the OMV box returns loopback address.

;; ANSWER SECTION:
blob.			0	IN	A	192.168.1.200
blob.			0	IN	A	127.0.1.1

Then I had a look at /etc/hosts and found this:

127.0.0.1 localhost
127.0.1.1 blob.mydomain.com blob

This is incorrect as my host blob has a proper IPv4 and IPv6 address.

### Versions report
5.0.14

**Comment by votdev** [comment]
And how should the OMV scripts know that dnsmasq is installed? Ok, could check that, but this is not how OMV works.

**Comment by cryptobank** [comment]
As per Debian documentation (https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution)

_For a system with a permanent IP address, that permanent IP address should be used here instead of 127.0.1.1._

OMV being a server will usually have a permanent IP address.

**Comment by yuchenshi** [comment]
I've noticed that this issue is happening again after #1045. Namely, if a static IP address is configured, OMV now generates 2 (or more) lines with the FQDN:

```
127.0.1.1 {{ fqdn }} {{ alias }}
{{ interface.address }} {{ fqdn }} {{ alias }}
```

According to the Debian documentation quoted and linked above, we can (and should) remove the first line so that the permanent address(es) is used _instead_, not _in addition_ to `127.0.1.1`. I've tried this locally and confirmed that `hostname -f` returns FQDN correctly too, giving us the best of both worlds.

@votdev would you accept a PR for such a fix? If so, I can get started on CLA and the changes.

**Comment by yuchenshi** [comment]
I just verified that this works perfectly on openmediavault 6.0.29-1. Thanks!
