### ISSUE TITLE
List filesystems inside a LXC Containers

### ISSUE THREAD

**Issue by JonasZ95** [openmediavault/openmediavault#514]
### Description of issue/question
Part 1:
If you open the filesystems page in the webui you get an error that blkid returned 2 here: https://github.com/openmediavault/openmediavault/blob/86e45d763fdf3921b815e8e675599c137fc3da47/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/backend/manager.inc#L211
According to the manpage of blkid this is wrong behaviour because exit code 2 means no devices found. If I understood It right we can set Command quiet and then check the exit code for 0 or 2.

Part 2:
LXC mounts are not listed because there's no backend which can find them.

### Steps to reproduce issue
1. Create a Debian Buster Container in Proxmox 6
2. Install OMV 5 Packages
3. Click Filesystems in the webui

**Comment by ryecoaaron** [comment]
It isn't hard to write a backend for a filesystem.  Here is a plugin I wrote that just adds nilfs2 as a backend - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-nilfs2

**Comment by JonasZ95** [comment]
I think Part 1 is a bug. However, I think Part 2 requires some discussion. My idea is that we have a config file where we can list 'imported filesystems'. Like /etc/openmediavault/external_filesystems:
/mnt/share
/mnt/backup
So we could use findmnt to grab the information we need for the interfaces for the specified mount. I could also try to implement this but I'm not sure If there is any stepping stone with this design I'm overseeing. I'm still a PHP beginner but as @ryecoaaron  mentioned It's quite easy to write a backend so I'd like to give It a try.

**Comment by votdev** [comment]
> My idea is that we have a config file where we can list 'imported filesystems'. Like /etc/openmediavault/external_filesystems:

Bad idea, too complicated. Everything must be resolved at runtime.

**Comment by votdev** [comment]
> According to the manpage of blkid this is wrong behaviour because exit code 2 means no devices found. If I understood It right we can set Command quiet and then check the exit code for 0 or 2.

What about the root filesystem? I'm wondering why `blkid` shouldn't find at least this filesystem.

**Comment by JonasZ95** [comment]
@votdev I'm no expert regarding LXC but It seems the root filesystem just is a mount:
`
rpool/data/subvol-102-disk-0 on / type zfs (rw,noatime,xattr,posixacl)
rdata/share/subvol-102-disk-0 on /mnt/share type zfs (rw,xattr,posixacl)

The man page states this: blkid - command-line utility to locate/print block device attributes, which doesn't really implicate that block device must exist to have a root filesystem right?
`

**Comment by votdev** [comment]
> I'm no expert regarding LXC

Me too.

Seems to be correct to handle the exit code in this case.

**Comment by fgma** [comment]
@JonasZ95 Is it possible to run OMV in an lxc container using bind mounts for shared folders with this patch?

**Comment by JonasZ95** [comment]
> @JonasZ95 Is it possible to run OMV in an lxc container using bind mounts for shared folders with this patch?

No you need a backend to find the mounts and use them. I tried to write a backend but I realized most internals in OMV expect that each filesystem is on a real block device so you end up with a lot of errors.

**Comment by fgma** [comment]
@JonasZ95 @votdev Would it be possible to support shared folders in bind mounts with reasonable effort or would it brake many other parts of the system?

**Comment by votdev** [comment]
I have too less information about your scenario and the problems in LXC containers to give a solid statement.

**Comment by votdev** [comment]
After thinking about it it should be possible to support this. You need to implement a new filesystem backend:

- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/backend/backendabstract.inc
- https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesysteminterface.inc

I think the mentioned list of `imported filesystems` may be a good starting point. But this list must be maintained by the admin manually, thus i really do not see a way to integrate this into OMV core, but as plugin it would make sense. You need to write a wrapper around the block device implementation. This should be possible because the filesystem backend is implemented to allow exactly this. If you have questions, then feel free to ask, but you have to implement it on your own.

**Comment by fgma** [comment]
Thanks for the explanation! So sum it up: 

1. It is possible to implement a plugin that supports adding shared folders to an already mounted filesystem. This filesystem might be a bind mount in lxc or just a random folder somewhere in the filesystem.

2. This folder would not need an fstab entry for lxc because it is already mounted through the host system. The filesystem would not have a valid blockdevice etc. but this could be ignored or emulated with a dummy.

Are these assumptions correct?

I'd really like to run OMV inside lxc because it would be so easy to just add an OMV instance for small systems without the need for virtualization. Right now I'm lacking the time to research it further but holidays are coming. ;-) If anyone else is is going to implement this just let me know so we don't waste any time.

**Comment by ryecoaaron** [comment]
Allowing this would solve the problem where people want one server with lots of storage (ie Proxmox) and want OMV to be able to share the storage instead of making large virtual hard drives OR passing through hard drives (reducing proxmox's available storage).

My only concern running OMV in LXC is that a lot of the power management, networking, monitoring, docker (potentially), virtualization (potentially) may not work correctly.  And if it works in LXC, people are going to try it in WSL (yuck).

As for the questions, it would be nice if @votdev would explain his vision on how that would work a bit more?  Would the plugin add folder that would appear as filesystems in the filesystems tab (but automagically show as mounted)?  Or would the folder just show as available sources for shared folders?

**Comment by ryecoaaron** [comment]
And @votdev , if you write the backend, I will write plugin... :)

**Comment by JonasZ95** [comment]
@votdev I implemented my own backend by inheriting BackendAbstract and then return the mounted paths via enumerate with my own Filesystem implementation. If I remember right I had some problem in OMVRpcServiceFileSystemMgmt where a valid path to a block device was required. Buy maybe I just overlooked something because I can not find this kind of verification in this class right now. The problem is I deleted the container and the code.

**Comment by votdev** [comment]
I'm sorry, i do not have the time to investigate here more, you're on your own.

**Comment by votdev** [comment]
Running OMV in a container makes most of the features useless, so i don't think it makes sense for OMV.

**Comment by ryecoaaron** [comment]
People want a web interface to configure ssh, cron, samba, nfs, users, etc.  It would still do that just fine.

**Comment by votdev** [comment]
I thin webmin or alternatives are the better solution for that.

**Comment by votdev** [comment]
OMV is designed for running on real hardware in SOHO environments.

**Comment by fgma** [comment]
@votdev My use case fits OMV perfectly for 90% of what I do. For the rest I installed plugins/custom software etc. which messes up the system. Ideally I want to keep a clean OMV installation in an lxc container without any changes to the base system and run everything else in a different container/vm/etc. To do so in a cost and energy efficient way lxc is an ideal solution for me.

@ryecoaaron  I just played around with an installation inside a VM (not lxc!). The remotemount-plugin does almost what I need. If one would add a new filesystem of type "local" which just creates all folders and necessary infrastructure for OMV without actually mounting anything to the folder one would end up with an folder with a cryptic name inside /srv/. After creating the folder one could add a bind mount to the lxc-container for the /src/$UUID folder and reboot the system. So far I did not try it inside a real lxc container, just a VM. Maybe this is an easy solution but I might miss something because its just a theoretical idea at the moment.

**Comment by ryecoaaron** [comment]
@fgma Not mounting anything is actually the problem.  The old remoteshare plugin used to bind mount remote mountpoints to an existing shared folder.  That would work in lxc if you could create sharedfolder in the first place.  I can look to see if the backend is flexible enough where I can override enough things to make OMV think it is a real filesystem but I'm guessing it might break somewhere.  We should move this to the forum as well.
