### ISSUE TITLE
Storage not found after simulated disk failure

### ISSUE THREAD

**Issue by FuntKlakow** [openmediavault/openmediavault#640]
My setup is as follows:
- an SSD containing OMV (AMD64, Debian Buster)
- two 2TB harddisks configured as RAID-1

The setup can be booted and runs just fine.

I tried to simulate a drive failure by powering down the machine, then disconnecting the SATA cable off one of the HDs and powering up the machine.

There is no RAID-1 mounted any longer. There is no /dev/mdstat. Scanning for disks and RAIDs using the web interface delivers no results.

If I log in to the machine via SSH, I can start the degraded RAID by mdadm -R.
But should this not be done in any case?
Possibly mounting the degraded RAID read-only?
At least issue some sort of warning?
Show he degraded state in the web interface instead of not finding the RAID at all?

**Comment by votdev** [comment]
OMV will not do any automatic RAID repair, because this will surely fail. This is something the administrator must do manually.

> There is no RAID-1 mounted any longer. There is no /dev/mdstat. Scanning for disks and RAIDs using the web interface delivers no results.

If there is no `/proc/mdsat`, how do you expect should a software know that there is a RAID.

> But should this not be done in any case?

No, see above.

> At least issue some sort of warning?

If you have enabled email notifications, then mdadm should notify you.

> Show he degraded state in the web interface instead of not finding the RAID at all?

OMV does not store any information about RAIDs in the database, all is detected at runtime. If there is no `/proc/mdstat` or and device node in `/proc/partitions`, then OMV is not able to show you anything.
