### ISSUE TITLE
Domain Offline

### ISSUE THREAD

**Issue by kellcomnet2** [openmediavault/openmediavault#641]
### Description of issue/question
openmediavault.org is returning default domain landing pages.
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

- visit openmediavault.org
- visit packages.openmediavault.org
- visit forum.openmediavault.org

**Comment by ryecoaaron** [comment]
Looks like it is working again except for the forum.

**Comment by kellcomnet2** [comment]
Confirmed for openmediavault.org and packages.openmediavault.org

**Comment by votdev** [comment]
A f**king spammer abused the forum to send emails to other forum members. Because of that the whole domain was blocked by the webhoster. For now i disabled the feature that allows members to send emails to other members.

**Comment by MathijsKooij** [comment]
Hi, is there a way to view the forum. I have a problem and R2D2 (sorry I forgot his name) posted a solution but I cannot read it now

**Comment by votdev** [comment]
> Hi, is there a way to view the forum. I have a problem and R2D2 (sorry I forgot his name) posted a solution but I cannot read it now

No, the forum is shut-down for the moment until the new software is up and the database has been migrated successfully.

**Comment by kellcomnet2** [comment]
@votdev Thank you for jumping on this so quickly and sorry from the community for the behavior of a few bad apples.

**Comment by ryecoaaron** [comment]
@MathijsKooij What problem?  I'm the R2D2 :)

**Comment by MathijsKooij** [comment]
Thank you! I messed up my upgrade. You suggested a line with dpkg to remove plex and some other old plugins (normal purge did not work) but when I was ready to try the forum was gone and did not remember the lines

**Comment by ryecoaaron** [comment]
dpkg -P openmediavault-plexmediaserver openmediavault-openvpn openmediavault-letsencrypt

there was one other plugin that needs to be removed but I don't remember the list.

**Comment by MathijsKooij** [comment]
Thank you, what was the command to view the installed plugins again, then it is just repeating with that plugin.

**Comment by ryecoaaron** [comment]
dpkg -l | grep openm

**Comment by MathijsKooij** [comment]
Thank you, but still no go. I have only now; openmediavault 5.3.8-1, apttool, clamav and keyring.

Instellen van openmediavault (5.3.8-1) ...
Creating configuration database ...
Migrating configuration database ...
  Running migration conf_5.0.0
WARNING: The node 'timemachine' already exists at XPath '/config/services/smb/shares/share'.
  Running migration conf_5.0.3
  Running migration conf_5.2.0
Setting up Salt environment ...
Processing system modifications ...
dpkg: fout bij verwerken van pakket openmediavault (--configure):
 subproces van pakket openmediavault werd script post-installation geïnstalleerd gaf de foutwaarde 1 terug
Fouten gevonden tijdens verwerken van:
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)


I hope you have one last good idea, otherwise I am just going to reinstall. No fancy config, so maybe safer. If I disconnect the drives with the data can will they be found again? Or do I need to get the data of and copy back.

**Comment by votdev** [comment]
Sorry for the delay, the migration of the database will take some time. I don't expect it will be online before beginning of next week.

**Comment by mi-hol** [comment]
With forum back & running, this issue should be closed now
