### ISSUE TITLE
Clamav "Specified path /var/lib/clamav/main.cvd does not exist"

### ISSUE THREAD

**Issue by dt64** [openmediavault/openmediavault#646]
### Description of issue/question

installing Clamav and starting service fails with "Specified path /var/lib/clamav/main.cvd does not exist"

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

install clamav from OMV GUI.

see logfile attached
[clamav_omv5_output.txt](https://github.com/openmediavault/openmediavault/files/4334812/clamav_omv5_output.txt)

**Comment by votdev** [comment]
The problem seems to be that freshclam can't download the virus pattern files. Make sure your network is working.

**Comment by dt64** [comment]
so it's probably similar to #614.
Network was up and running all the time but with small bandwith only. After a few more retries it eventually sorted itself out but that's not reflected in OMV's GUI. GUI says outstanding config change. (yellow banner on top of page).
Probably some room for improvement.

**Comment by votdev** [comment]
> GUI says outstanding config change. (yellow banner on top of page) plus emails from OMV saying "Pending configuration changes" "The configuration has been changed. You must apply the changes in order for them to take effect."

The deployment of the configuration gives freshclam 5 minutes to download the patterns, otherwise the process might run forever in a bad situation. If the download does not finish within this time the deployment aborts. Because of that the deployment is still not finished, thus displaying the 'Please apply ...' information in the UI is still correct.
