### ISSUE TITLE
OMV 4 partitioner reserves too much space for swap

### ISSUE THREAD

**Issue by andongn** [openmediavault/openmediavault#66]
I have HP Microserver Gen10. When installing OMV 4 the partitioner reserves 13,6GB for swap on the 16GB USB stick, which make the installation fail as there is not enough space left on /target (857MB) to copy all the files needed. 
The server have 32GB RAM, so reserving anything over 4GB for swap seems unnecessary to me.

Same configuration with OMV 3 installs and works fine.

**Comment by Ansem93** [comment]
Swap by default should be the same size of the RAM. This is important if you want to hibernate your NAS. 
I see nothing wrong with it.
Also some source for the standard Swap partition size:
If you go by Red Hat’s suggestion, they recommend a swap size of 20% of RAM for modern systems (i.e. 4GB or higher RAM).

CentOS has a different recommendation for the swap partition size. It suggests swap size to be:

Twice the size of RAM if RAM is less than 2 GB
Size of RAM + 2 GB if RAM size is more than 2 GB i.e. 5GB of swap for 3GB of RAM
Ubuntu has an entirely different perspective on the swap size as it takes hibernation into consideration. If you need hibernation, a swap of the size of RAM becomes necessary for Ubuntu.

Otherwise, it recommends:

If RAM is less than 1 GB, swap size should be at least the size of RAM and at most double the size of RAM
If RAM is more than 1 GB, swap size should be at least equal to the square root of the RAM size and at most double the size of RAM
If hibernation is used, swap size should be equal to size of RAM plus the square root of the RAM size
Source:  https://itsfoss.com/swap-size/

**Comment by mzhboy** [comment]
swap should define by user.when I install omv 4.x on pve, the swap is totally unnecessary.
the script use a lots of space for swap and “Install the system” failed, I have to use a debian image to install debian first and then install omv manually.

**Comment by andreapx** [comment]
I think that a flag to ask to personalize the swap partition.
I was installing OMV on a DL380 gen8 (with Proxmox) that has 64GB or RAM and I had to assign to OMV only 2GB of RAM to have a small HD.
Me and I think a lot of other person will never hibernate the NAS.

**Comment by mi-hol** [comment]
4.x is EOL, is it an issue affecting 5.x?

**Comment by mi-hol** [comment]
@votdev are there plans to change current behavior?

**Comment by mi-hol** [comment]
Closing because this should be addressed at the team owning Debian installer

**Comment by ws-tech-mgr** [comment]
> I was installing OMV on a DL380 gen8 (with Proxmox) that has 64GB or RAM and I had to assign to OMV only 2GB of RAM to have a small HD.

I had to use this workaround for OMV 5.5.11-1, on ESXi 7.0.  After installation completed, I bumped the allocated memory back up, and it seems to be working just fine on a test box.
