### ISSUE TITLE
Feature request: Define --backup-file for mdadm grow

### ISSUE THREAD

**Issue by N0rdmann** [openmediavault/openmediavault#675]
As discussed [on the forums](https://forum.openmediavault.org/index.php?thread/31449-location-of-mdadm-backup-file-raid-grow/) it would be great to have a backup file in place for growing Raid.
mdadm --grow /dev/mdX --level=X --raid-devices=X **--backup-file=**

[how to ](https://unix.stackexchange.com/questions/311051/how-to-continue-an-mdadm-grow-after-a-reboot)restart a grow after a clean reboot:
mdadm --stop /dev/md...
mdadm --assemble --backup-file location_of_backup_file  /dev/md...
it should restore the work automatically

**Comment by mi-hol** [comment]
@votdev how to deal with this reqest?

**Comment by votdev** [comment]
Leave it open for user contributions.

**Comment by N0rdmann** [comment]
Mhm what further user contribution is expected here?

Basically the **mdadm --grow** command behind growing UI task just needs to be extended with **--backup-file=$omvtemp/blabla** which would prevent catastrophic data loss, esp. with big raids where extension runs for days...

**Comment by votdev** [comment]
Here are some more question:
* Can the file be deleted after `mdadm --grow` has been executed?
* What happens in case of an power failure. Does any additional command needs to use this file.
* Which command is executed after an power loss? `mdadm --grow` again?
* What happens when `mdadm --grow` is executed after an power loss. If the command is implemented a generic way, the backup file will contain the device file as identifier, so the previous file will be overwritten. How to handle that?
* Using /tmp is no idea because this will be cleaned out on reboot. So it will be not available after power loss when the machine reboots.
* ...

As you see, it's never trivial to enhance something that looks easy.

The best would be if someone (you) provides a full pull request including all necessary changes and which is ideally already tested. Based on that PR more discussion can be started to prevent regressions and other side-effects.
