### ISSUE TITLE
Cron-Apt sends too much information

### ISSUE THREAD

**Issue by henfri** [openmediavault/openmediavault#712]
(remark: labels on the right side are not visible to me when creating an issue. When created, I see them, but cannot edit)
### Description of issue/question
I work in aviation. Here we follow the lights-out philosophy in the cockpit. No light=all good. A light indicates a failure
OMV does not follow this. I get too many mails every day, even if everything is normal. Consequently, I tend to delete them.

My proposal would be to change /etc/cron-apt/config
`MAILON="error"`

### Steps to reproduce issue
Have cron-apt active and tell OMV your mail address

### Versions report
(I suggest in the template for the issues to show the command to get the Versions report)

**Comment by votdev** [comment]
You know that this suggestion will break the intention of cron-apt to notify you about new package updates? I don't want to get emails from cron-apt only when something breaks badly. Because of that i will close this issue due the fact that cron-apt works as wanted in OMV.

**Comment by henfri** [comment]
Hello,

but do you think that a mail every day is reasonable?
Or do I mis-understand something/use it wrongly?

Regards,
Hendrik

**Comment by votdev** [comment]
cron-apt checks for new updates and sends the result via email. There is no way to tell this app to do not send an email if there are no new updates available. Checking for new updates once a week is not an option because of security reasons. Because OMV will never install updates unattended there is no way around to check everyday for new updates.
