### ISSUE TITLE
DNSSD and NetBIOS names are different for same device

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#718]
Hi there, a KDE dev recommend I report this bug to you. I'm not sure yet whether it could be considered an OMV bug or a Linux bug, or both. But here goes:

My NAS is running the latest OMV packages on an up-to-date Buster installation. The NAS is named "OpenMediaVault", and under Dolphin `smb://` it normally appears as "OpenMediaVault - SMB/CIFS". But recently on some cutting-edge Linux distros it started appearing twice as:
**OpenMediaVault - SMB/CIFS**
**OPENMEDIAVAULT**
They both lead to the exact same Zeroconf host-- `smb://openmediavault.local/`
I tried temporarily renaming my NAS to "OMV", but it still showed twice:
**OMV - SMB/CIFS**
**OMV**

The first one is the DNSSD name, and the second is the NetBIOS name. It the KDE dev's opinion, it doesn't make sense for these two to be different. I am also attaching KIO and libsmbclient logs from my openSUSE Tumbleweed KDE system that shows the duplicates, and from the openSUSE Leap 15.2 beta KDE that does _not_ show duplicates. Please let me know if you need anything else. Thanks for the help!

Relevant KDE bug report: https://bugs.kde.org/show_bug.cgi?id=422001

[KIO_log.txt](https://github.com/openmediavault/openmediavault/files/4677604/KIO_log.txt)
[NO-DUPES_kio.log](https://github.com/openmediavault/openmediavault/files/4677605/NO-DUPES_kio.log)
[NO-DUPES_smbclient.log](https://github.com/openmediavault/openmediavault/files/4677606/NO-DUPES_smbclient.log)
[libsmbclient_log.txt](https://github.com/openmediavault/openmediavault/files/4677607/libsmbclient_log.txt)

**Comment by votdev** [comment]
`OpenMediaVault - SMB/CIFS`is the Zeroconf announcement (used Linux systems)
`OPENMEDIAVAULT` may be the WSDD announcement (required by Windows systems)

If KDE nowadays supports both types then this will end up in showing the system twice.

**Comment by geckolinux** [comment]
@votdev Thanks for the reply. What about just setting them to the exact same name for both Zeroconf and WSD, and using the same upper/lower case letters? (In my OMV network settings the hostname is set to `OpenMediaVault`)

**Comment by votdev** [comment]
> @votdev Thanks for the reply. What about just setting them to the exact same name for both Zeroconf and WSD, and using the same upper/lower case letters? (In my OMV network settings the hostname is set to `OpenMediaVault`).

That's not possible by default because the Avahi (Zeroconf) configuration is `%h - SMB/CIFS`, so Avahi is handling how it replaces `%h`with the hostname. And for WSD this is done by WSD daemon (wsdd).

You can customize the Zeroconf string manually to whatever you want, but there is no WebUI to do that (and there is no plan to support that again after it has been removed in OMV5). To do so add the environment variable `OMV_SAMBA_ZEROCONF_NAME` to /etc/default/openmediavault and recreate the [Avahi configuration](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/avahi/services/smb.sls#L27) with `omv-salt deploy run avahi`.
