### ISSUE TITLE
Improve dashboards

### ISSUE THREAD

**Issue by tooomm** [openmediavault/openmediavault#724]
### Description of issue/question
- The `System Information` widget in the dashboard only shows "Yes/No" for available updates.
It would be very helpful if there would also be an button to go to the update page, update from there or display a hint next to the version value in the version row for omv updates as the "Updates available" row is at the very bottom.
Displaying some more details like how many packages or what kind of updates (debian, omv, plugins...) are available might also be a nice addition.

- It is not possible to select and copy information from the dashboards at all.
Things like omv/kernel version, ip address or hdd label might be values one would like to copy flawless to use elsewhere.
In other sections in the UI it's similar. Does this change with the redesign in OMV 6?

### Versions report
OMV 5.3.9-1 Usul

**Comment by votdev** [comment]
> It would be very helpful if there would also be an button to go to the update page

The OMV5 UI does not have routes, because of that it is not possible to go from one page to another.

> Displaying some more details like how many packages or what kind of updates (debian, omv, plugins...) are available might also be a nice addition.

Not possible and this was not the intention of this feature.

> It is not possible to select and copy information from the dashboards at all.

This is a ExtJS behavior that you can not copy text. This can't be fixed easily and i really do not want to touch the ExtJS code anymore. OMV6 will handle this different and will not have this limitation.

**Comment by votdev** [comment]
Various issues are fixed in OMV6.

**Comment by tooomm** [comment]
Happy to hear these should be less of an issue with the next main release.
