### ISSUE TITLE
Feature suggestion: Automount USB and SMB/CIFS integration

### ISSUE THREAD

**Issue by geckolinux** [openmediavault/openmediavault#733]
Hi there, I think that it would be very useful to offer an out-of-the-box method to automount USB drives. It's a pretty common usage scenario on a NAS to connect external USB storage to either push or pull a backup. I researched a ton of ways to do this on Linux without a ton of additional dependencies, and I found this elegant solution using systemd that I have manually applied to my OMV server:

https://serverfault.com/a/767079
It only has 3 components:
1. A simple `usb-mount.sh` shell script
2. A systemd service that runs `usb-mount.sh`
3. Two rules in `/etc/udev/rules.d/99-local.rules`  to make systemd react on plug/unplug events

It's quick and easy and unbloated. It mounts the device on `/media/DEVICELABEL`, including drives with multiple partitions/labels. Quite slick.

There also another option [here](https://serverfault.com/a/960102) that uses `pmount` instead of the `usb-mount.sh` shell script, but the disadvantage is that it doesn't mount it with the device label name, just "`sdX`".

From there, I symlinked `/media` into my Public SMB share and made it accessible via SMB/CIFS via the extra conf options described in #732. It might be nice to have a toggle in OMV to enable a similar configuration too for accessing automounted USB drives via SMB/CIFS.

**Comment by votdev** [comment]
I don't like this idea directly integrated into OMV because it does not follow the philosophy of OMV. But if this would be implemented as plugin, then i'm fine.

**Comment by votdev** [comment]
You can use `openmediavault-usbbackup` to sync data from an external device into the NAS as an alternative solution.

**Comment by yuriw** [comment]
@votdev I'd like to understand better the philosophy of OMV.
I use only USB connected drives.  Is this considered not a standard use case ?

**Comment by votdev** [comment]
> @votdev I'd like to understand better the philosophy of OMV.

The concept of OMV is NOT to allow the user to do everything what is possible, the concept is to provide a simplified workflow that matches the needs for 99% of the users. The design and concept was done by intention, made of experiences at my job and while developing FreeNAS. I see OMV like Apple's iOS, you do not have full control of everything, but it works. If you don't like that, there is Android. Same is for OMV, there are other competitors out there that might match the users needs more.

> I use only USB connected drives. Is this considered not a standard use case ?

The `openmediavault-usbbackup` is exactly the tool to use to sync external data to and from the NAS. Temporary plugged devices are not supported for shared folders because this makes handling of filesystems, shared folders and services that consume those folders extremely difficult.

**Comment by dr-leo** [comment]
I must admit that even mindful of the "philosophy" exhibited above, I estimate that far more than 1% of users would benefit from a less ambitious feature than suggested here, namely a clean way to re-establish a share after unplugging the referenced USB drive. Unplugging may happen unintentionally, by force majeure etc. Yet, the only way to repair any share on it is a reboot. OMV can and should be more foregiving without prejudice to its philosophy.

**Comment by Monacoslo** [comment]
I agree. Having the possibility to automaticaly mount USB drive if it was unplugged is very usefull. I use many portable usb drives that I ocassionally need to have them available throug the network so I just plug them in and I would like to see the files.
