### ISSUE TITLE
[Issues- arm64] some plugin was not show on Webgui left tree node when install success

### ISSUE THREAD

**Issue by bjwrkj** [openmediavault/openmediavault#74]
# Environment Info
- OMV Version: 3.0.86 
- Plugin Name: openmediavault-shellinabox, openmediavault-shairport , third party plugin;
- System: Debian jessie on arm64

# Descripation
I am porting OMV3.X to arm64 board and success running it.
After I install shellinabox plugin, the plugin was install success, but the plugin was not show on OMV left tree node. 

# Procedure
-  dpdk -s openmediavault-shellinabox (on x86_64), find the depends package;
- apt-get install shellinabox (on arm64);
- dpkg -c openmediavault-shellinabox.deb or dpkg -L openmediavault-shellinabox, package list;
- copy package list file to arm64 board;
- add node in config.xml;
- clean brower cookie/cahce and refresh brower;
- login 
- can be found the service is  exist, but OMV left tree node was not show;

# Screenshots
x86_64 (normal)
![image](https://user-images.githubusercontent.com/8447585/38075196-19e66cf8-3364-11e8-8f35-01fcaf582009.png)

arm64(abnormal)
![image](https://user-images.githubusercontent.com/8447585/38075207-21455a54-3364-11e8-92e7-13c4688006b8.png)

Who can help me with this issue?
Thanks;

**Comment by votdev** [comment]
Why do you make it so complicated? You can install the plugins on every platform. If you've installed OMV code you can install the plugins via WebUI. Manually copying the files from one platform to another does not work because some Debian package triggers are not executed in that case. And that's the reason for the missing entries in the WebUI.

You should get it working if you execute the following command:
```
# rm -f ${OMV_CACHE_DIR}/cache.*.json
```
But this is the incorrect way to do it. Install the packages via WebUI or CLI. As ``shellinabox`` is available for ARM64 there is no need to do this crazy workaround to install the [plugin](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-shellinabox/blob/master/debian/control).

**Comment by bjwrkj** [comment]
Hi Volker ,

I am very happy to receive your reply, thanks a lot;

Maybe as your say, but I only want to this plugin as an example;

That Great Volker;

Best Regards,
Keven
