### ISSUE TITLE
Feature Request: deactivate login page 

### ISSUE THREAD

**Issue by menotuu** [openmediavault/openmediavault#776]
It would be nice, to have a keep logged in feature / deactivate login startpage after restart.

I am a LAN single user, not needed to login every time after a restart (its slow on a Raspi4).

https://forum.openmediavault.org/index.php?thread/33726-deactivate-login-page/

**Comment by votdev** [comment]
That's not possible because the UI and the backend require session information to authenticate the requests. You will be able to login without a new authentication if your browser does not clear cookies on close. After a reboot of the system it is always necessary to login again because the session data is lost during reboot.
