### ISSUE TITLE
OMV installation enables ssh-access for root

### ISSUE THREAD

**Issue by llutz** [openmediavault/openmediavault#779]
The installation of OMV5 on top of a plain Debian Buster modifies /etc/ssh/sshd_config without notification to allow ssh-access for root - even with password

The default sshd_config of debian-systems doesn't contain any active "PermitRootLogin" lines, so "PermitRootLoign without-password" as default is used.
Default /etc/ssh/sshd_config
```
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem       sftp    /usr/lib/openssh/sftp-server

```
The OMV-installer adds (besides other options)

```
AllowGroups root ssh
PermitRootLogin yes
PasswordAuthentication yes

```
This will open ssh-access for the root-user without any notification. That is a serious security-flaw and should be fixed. There is no need for root having ssh-access, least of all with password-authentication, to a system.

Debian Buster - Linux omv 4.19.0-10-amd64
- openssh-server 1:7.9p1-10+deb10u2
- openmediavault 5.5.6-1

**Comment by votdev** [comment]
> There is no need for root having ssh-access

There are indeed scenarious where a root access is required for `root`. Imagine your installing OMV on a headless system, so how can you access the system if the installation fails and you can not enable SSH root access via WebUI?

**Comment by llutz** [comment]
Therefor one has a non-priviledged user who can gain root using "su -". Thanks for adding at least a hint.

**Comment by votdev** [comment]
> Therefor one has a non-priviledged user who can gain root using "su -". Thanks for adding at least a hint.

After installation there is no `non-priviledged` user available that can be used for that (at least this is for the OMV ISO image).

**Comment by llutz** [comment]
imho you'd think about changing this and use such a user for maintenance. 
root access with password is a no-go (sorry, my opinion after 20yrs linux-administration).

**Comment by votdev** [comment]
I think two different attitudes meet here. I will keep the existing implementation.

**Comment by llutz** [comment]
your decision - no offense intended.

**Comment by llutz** [comment]
Problem with novice users is, that they are going to expose their boxes to the internet. And that has severe consequences.

**Comment by votdev** [comment]
> Problem with novice users is, that they are going to expose their boxes to the internet. And that has severe consequences.

That's true.

But fixing this issue in OMV will surely break installations of Raspbian and other ARM images that provide OMV support. This is out of the scope of the OMV project and must be fixed by the maintainers of other projects. Changing this will also make many howtos unusable. It's a small fix with huge consequences.

**Comment by llutz** [comment]
Sure, but it's also a flaw with huge consequences - at least, when admin's aren't aware of that changed sshd_config. Which covers most of the "novice users", those aren't admins.

**Comment by votdev** [comment]
Another problem is the migration. Imagine you have a running system and the latest update will remove SSH support for `root`. The user needs to create a new user, add them to the `SSH` group and this new user must be added to the sudoers file. This is something that will never work for novice users. It is not possible to automate this because i don't know which existing user should be used.

The be honest, this is too critical to me to change the current workflow. There are too many imponderables and external dependencies that the OMV project cannot influence. I will not take over the risk to break installations and force users to reinstall their systems from scratch. 

If there is someone encouraged to provide a rock solid solution i will take a look into the contribution, but for now it is to risky.

**Comment by votdev** [comment]
A [note](https://github.com/openmediavault/openmediavault-docs/commit/9c6c8426a109484bf9e49b53e95332d1d721b9ce) has been added to the documentation.

**Comment by ryecoaaron** [comment]
The raspberry pi images direct from the Raspberry Pi foundation have the pi user set with passwordless full sudo. I’ve been a Linux admin for over 20 years myself and we have root with password enabled via ssh at work (large enterprise). The root password is very complex and the boxes are not exposed directly to the internet. If a user chooses to expose their system to the internet and use a weak password, that is their choice. The option to disable it is there and we have plugins like fail2ban to help. As Volker said, there is no other user to give sudo privileges to and some boards (odroid-hc2) cannot even have a monitor connected to use root locally.

**Comment by ryecoaaron** [comment]
Another note is that Armbian does have you change the root password, creates a user with full sudo, and disables root login via ssh. The problem is that it mentions you can hit ctrl-c to skip creating the sudo user. So I cant really disable root login via ssh in the install script.
