### ISSUE TITLE
Disks not shown in Encryption List

### ISSUE THREAD

**Issue by MarcS1975** [openmediavault/openmediavault#781]
### Description of issue/question
After upgrading to latest OMV 5.5.6-1, not all of my LUKS encrypted disks do not show up in the list of encrypted disks.
The 2 missing disks have a JMicron controller but they do show up under OMV-Disks and under OMV-SMART

The disks worked fine as encrypted under previous OMV 5.

Where is the OMV "Encrypted" tab looking for the disks? I guess the block device was not properly generated.

### Steps to reproduce issue
Reboot
blkid command also does NOT show the disks

**Comment by votdev** [comment]
Does this also happen with `openmediavault 5.5.7`?

**Comment by MarcS1975** [comment]
yes. it also happens in 5.5.7

**Comment by votdev** [comment]
I can only guess, but with `5.5.6` the devicefiles for devices that use a JMicron have been changed to fix a problem with those controllers. The LUKS configuration (and OMV database) might contain the old devicefiles which will cause the current problem.

The old devicefile contains the serial number of the controller instead of the harddisk/SSD/... This will cause problems because ALL disks attached to such controllers will have the same device file then. This was fixed by https://github.com/openmediavault/openmediavault/commit/3ffa2d89ec2647b8c811f9adfbc53c07a4450f0b

**Comment by MarcS1975** [comment]
Ok.thst makes sense. HOw do I update the LUKS configuration to use the new
files? Is there anything to reset?

**Comment by votdev** [comment]
You should raise that question [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). As mentioned, i do not know or use the LUKS plugin, so only the maintainer of that plugin can answer the question.

**Comment by MarcS1975** [comment]
Ok. I have swapped the controllers away from JMicron and now there is no
problem. I really love your OMV product so maybe let people know that they
should just stay away from JMicron equipment as it is just not compatible.
Saves a lot of time and headache and a new controller only costs £5.0
Thanks
