### ISSUE TITLE
2 Network Cards error

### ISSUE THREAD

**Issue by SupperCraft5000** [openmediavault/openmediavault#79]
When i add 2 Network Cards then i become an error - https://youtu.be/NB5t23_nljE

**Comment by votdev** [comment]
After the first error all tests are irrelevant because the network has not been started correct and is in an unknown state as you may have noticed bacause of the unexpected behaviour.

**Comment by Dewil2018** [comment]
I had the same situation. Look under root under ssh configuration _Ip address_.

 IP address command. after that, delete one interface and restart the system. To hang the second address, I used a router and a hard binding to the MAC address. On the other failed. But share traffic as I wanted to me so and not managed

**Comment by unquietwiki** [comment]
Possibly related to #149 ?

**Comment by simpletasks** [comment]
Two issues have same origin. That is that default gateway can be set only once in `/etc/network/interfaces` file. Configuring second interface, if done without gateway x.y.c.v, will not produce error (must apply warning) but all traffic will go through one interface. If you unplug that interface - no traffic through second interface. Traffic for both IP goes through one interface. Even if warning want go away you have working configuration. But partially to be exact. And when you delete just added interface (from GUI) it will disappear from GUI, but if you check `/etc/network/interfaces`, `ip route show` and `ip a` it is still there. You must delete those entries to go back to initial state.
Gui is simple, just forward interface definition to debian.
For proper two interface configuration on single subnet first create second interface through GUI without gateway entry because you already have default gateway defined with first interface.
Then you must go to debian terminal and perform several network configuration commands.

1. Add two new table names into `/etc/iproute2/rt_table` 
    1 enp0s3t
    2 enp0s8t
2. ip routing configuration example:
```bash
ip route add 192.168.84.0/24 dev enp0s3 src 192.168.84.152 table enp0s3t
ip route add table enp0s3t default via 192.168.84.1 dev enp0s3
ip route add 192.168.84.0/24 dev enp0s8 src 192.168.84.155 table enp0s8t
ip route add table enp0s8t default via 192.168.84.1 dev enp0s8
ip rule add table enp0s3t from 192.168.84.152
ip rule add table enp0s8t from 192.168.84.155
sysctl net.ipv4.conf.default.arp_filter=1
```
Now we have two interface configuration (HA type) on subnet.

So for this we must dig debian networking, Gui can not solve that use case (for now).
I would like to see that behavior in OMV interfaces GUI - when adding multiple interfaces for single subnet.
BR
