### ISSUE TITLE
After fresh install OMV doesn't gets IP from DHCP.

### ISSUE THREAD

**Issue by the4anoni** [openmediavault/openmediavault#807]
### 
0. Pi is connected to router via ethernet.
1. Set static IP for Raspberry Pi on router.
2. Setup fresh 2020-08-20-raspios-buster-armhf-lite.img on SD Card.
3. Run it (at this point it gets IP from DHCP server which is 192.168.1.11)
4. Run setup script
5. After reboot Pi IP is 192.168.1.25 (while it still should be 192.168.1.11)

![20200906_101416](https://user-images.githubusercontent.com/13403084/92321462-6f034780-f02a-11ea-9208-f1d827e7bfec.jpg)
(Look at the My IP address is 192.168.1.25 line).
Pi at 192.168.1.11 is unreachable.

**Comment by votdev** [comment]
It's a known issue that the displayed IP address sometimes does not reflect the real one. This is because of timing issues when the systemd network unit takes longer thatn the issue unit which generates the welcome message.

IMO the IP address problem is not related to the OMV system, your router simply assigns the `.25` instead of the `.11` address. OMV uses systemd-networkd to configure the system, i don't think there is a bug.

**Comment by the4anoni** [comment]
> It's a known issue that the displayed IP address sometimes does not reflect the real one. This is because of timing issues when the systemd network unit takes longer than the [issue unit](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/openmediavault.openmediavault-issue.service) which generates the welcome message.
> 
> IMO the IP address problem is not related to the OMV system, your router simply assigns the `.25` instead of the `.11` address. OMV uses systemd-networkd to configure the system, i don't think there is a bug.

My router assigns .11 without any problems to my raspberry pi when clean raspbian is installed.

**Comment by ryecoaaron** [comment]
The install script switches the networking system to netplan/systemd-networkd.  Something with your router thinks this is a different system.  I would guess it gives out a different ip address because the static entry is "in use".  I would shutdown the RPi and clear both address in your router.  Then start the rpi again.  There is nothing the script can do to fix this.

**Comment by the4anoni** [comment]
OK, I'll try to assign static IP after I'll install OMV.

Maybe my router is just piece of crap...

**Comment by the4anoni** [comment]
Set static ip on pi and now it's ok.
