### ISSUE TITLE
Error after OMV update 

### ISSUE THREAD

**Issue by crescent94** [openmediavault/openmediavault#822]
version: 4.1.36-1(arrakis)
Linux 4.19.0-0.bpo.9(AMD64)

Performed an update in late September of OMV.  Now when I attempt to update, I get the following:
Repairing failed installation does not work.  
Reinstalling python3 does not help.

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up openmediavault (4.1.36-1) ...
Updating configuration database ...
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 23, in <module>
    import openmediavault
ModuleNotFoundError: No module named 'openmediavault'
dpkg: error processing package openmediavault (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openmediavault
Traceback (most recent call last):
  File "/usr/sbin/omv-mkaptidx", line 38, in <module>
    import openmediavault
ModuleNotFoundError: No module named 'openmediavault'
E: Sub-process /usr/bin/dpkg returned an error code (1)

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up openmediavault (4.1.36-1) ...
Updating configuration database ...
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 23, in <module>
    import openmediavault
ModuleNotFoundError: No module named 'openmediavault'
dpkg: error processing package openmediavault (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openmediavault
Traceback (most recent call last):
  File "/usr/sbin/omv-mkaptidx", line 38, in <module>
    import openmediavault
ModuleNotFoundError: No module named 'openmediavault'
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by votdev** [comment]
Is it possible that the installation failed before?

**Comment by crescent94** [comment]
I have had this installation running for over two years now (since version 4 release).  This issue occurred after an update attempt in September 2020.

All features seem to work but I have to force the web gui to respond via CLI.  If there is a way to either perform an inplace re-install or save all configs and perform a new install that would be helpful.   An upgrade patch to 5 would also be helpful, but from what I have read, that is not supported and was not created.

**Comment by ryecoaaron** [comment]
It somewhat looks like something you did uninstalled the openmediavault package.  If it purged the database, you might as well install OMV 5 fresh.  Otherwise, there is a script to help with the upgrade to OMV 5.x but it may not work with the errors you have right now - https://forum.openmediavault.org/index.php?thread/27909-omv-5-0-finally-out/&postID=219830#post219830

**Comment by votdev** [comment]
You may try `apt-get install --reinstall openmediavault` to fix the problem.

**Comment by crescent94** [comment]
I get the following when trying to reinstall

> E: Internal Error, No file name for openmediavault:amd64

**Comment by serial8killer** [comment]
Hi, I also have a similar problem, now I cannot install any packages because of this.
My error message is this

`root@openmediavault:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up openmediavault (4.1.36-1) ...
Updating configuration database ...
sed: can't read /usr/sbin/omv-mkgraph: No such file or directory
run-parts: /usr/share/openmediavault/mkconf/collectd.d/sensors exited with return code 2
dpkg: error processing package openmediavault (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@openmediavault:~#
`
when I do a OMV-update , apt upgrade, etc, the result is always the same.

Also already tried the fix apt-get install --reinstall openmediavault ,and I get the same problem as crescent94:

E: Internal Error, No file name for openmediavault:amd64

Please help!

**Comment by mi-hol** [comment]
@serial8killer please use the forum at https://forum.openmediavault.org to get support

**Comment by HeyBreezeYang** [comment]
this is my fault 
Processing triggers for php7.4-cgi (7.4.33-1+deb11u4) ...
Errors were encountered while processing:
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 76, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 72, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/update.py", line 60, in execute
    db.set(obj)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 301, in set
    query = openmediavault.config.DatabaseSetQuery(obj)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 784, in __init__
    super().__init__(obj.model.id)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 314, in __init__
    os.stat(self._database_file)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/openmediavault/config.xml'
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 76, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 72, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/populate.py", line 50, in execute
    openmediavault.procutils.check_call([script_path])
  File "/usr/lib/python3/dist-packages/openmediavault/procutils.py", line 58, in check_call
    return subprocess.check_call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/share/openmediavault/confdb/populate.d/20hostname.sh']' returned non-zero exit status 1.
[2023-09-04 08:56:02+0100] [omvinstall] openmediavault package failed to install or is in a bad state.
