### ISSUE TITLE
/srv/dev-disk-by-label-xxxx is not a mountpoint

### ISSUE THREAD

**Issue by AWHubGit** [openmediavault/openmediavault#825]
I installed OMV 5.5.12-1 (Usul) on RP 4 with Raspberry OS 2020-08-20-raspios-buster-armhf-lite.img. Fresh installation yesterday.

Log is full of:
raspinas monit[1000]: Filesystem '/srv/dev-disk-by-label-raspinas' not mounted
raspinas monit[1000]: 'filesystem_srv_dev-disk-by-label-raspinas' unable to read filesystem '/srv/dev-disk-by-label-raspinas' state
raspinas monit[1000]: 'filesystem_srv_dev-disk-by-label-raspinas' trying to restart
raspinas monit[1000]: 'mountpoint_srv_dev-disk-by-label-raspinas' status failed (1) -- /srv/dev-disk-by-label-raspinas is not a mountpoint

What does OMV5 use for referencing drives/disks? Classic method with "/dev/sda" or by UUID? How/why is "/dev/disk/by-label/...." used and how decision for this is made?

**Comment by votdev** [comment]
> What does OMV5 use for referencing drives/disks? Classic method with "/dev/sda" or by UUID? How/why is "/dev/disk/by-label/...." used and how decision for this is made?

OMV uses predictable device names because everything else might cause problems. `/dev/sda` may change depending on timing issues, `/dev/disk/by-uuid` is bad if you use BTRFS, so the only possible device name that is predictable is `/dev/disk/by-label` and `/dev/disk/by-id`.

You can find the code here:
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/blockdevice.inc#L199
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/block.py#L83

**Comment by mi-hol** [comment]
@AWHubGit could you please change issue title to "BTRFS: use predictable device name in OMV"

**Comment by AWHubGit** [comment]
Meanwhile I am not using OMV anymore. I can't remember exactly, but I think the disks weren't formatted with BTRFS if BTRFS means [https://btrfs.wiki.kernel.org/index.php/Main_Page](https://btrfs.wiki.kernel.org/index.php/Main_Page).

I wanted to follow this project
[https://www.heise.de/select/ct/2020/12/2005114065511783950](https://www.heise.de/select/ct/2020/12/2005114065511783950)
It recommends ext4.

BTRFS is not the cause.

What do you want me to put in the title now?
