### ISSUE TITLE
error updating open media vault machine

### ISSUE THREAD

**Issue by rwkane** [openmediavault/openmediavault#837]
### Steps to reproduce issue
(Include debug logs if possible and relevant.)

### Versions report
[debianopenmediavaulterror.txt](https://github.com/openmediavault/openmediavault/files/5440543/debianopenmediavaulterror.txt)

**Comment by votdev** [comment]
Really, Debian 6 (Squeeze) is OMV 0.5 which was released 7 years ago and is EOL since ages. I don't know whether Debian is still maintaining this version with security updates. ... You can find info at https://wiki.debian.org/DebianSqueeze, but this page says 'Security updates are not provided anymore.'. You should really consider to upgrade to the latest version.

The problem of your `apt-get update` is that the package repository of Squeeze has been relocated to archive. You should check https://www.debian.org/distrib/archive if you really consider to use your system.

I will close this issue because it is not bug and should be discussed in the [forum](https://forum.openmediavault.org).

**Comment by rwkane** [comment]
Thanks for the quick response~



Thank You,

Ryan Kane

APSB Data Center

Ryan.Kane@apsb.org

Desk – (225)391-7181

Mobile – (504)250-5653



*From:* Volker Theile <notifications@github.com>
*Sent:* Monday, October 26, 2020 1:39 PM
*To:* openmediavault/openmediavault <openmediavault@noreply.github.com>
*Cc:* rwkane <ryan.kane@apsb.org>; Author <author@noreply.github.com>
*Subject:* Re: [openmediavault/openmediavault] error updating open media
vault machine (#837)



Really, Debian 6 (Squeeze) is OMV 0.5 which was released 7 years ago and is
EOL since ages. I don't know whether Debian is still maintaining this
version with security updates. ... You can find info at
https://wiki.debian.org/DebianSqueeze, but this page says 'Security updates
are not provided anymore.'. You should really consider to upgrade to the
latest version.

The problem of your apt-get update is that the package repository of
Squeeze has been relocated to archive. You should check
https://www.debian.org/distrib/archive if you really consider to use your
system.

I will close this issue because it is not bug and should be discussed in
the forum <https://forum.openmediavault.org>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openmediavault/openmediavault/issues/837#issuecomment-716746836>,
or unsubscribe
