### ISSUE TITLE
Virtual hosts file out of date? - Unable to use multiple virtual hosts similar to #620

### ISSUE THREAD

**Issue by JugglerMaster** [openmediavault/openmediavault#848]
I just installed 5.5.16-1 on my NAS and trying to setup my self hosted sites on the same box with nginx. I found that nginx said " nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)" and searching online I found that this method that omv currently uses to bind to the port is outdated and doesn't allow other virtual hosts on the same port. More about this issue here: https://chrisjean.com/fix-nginx-emerg-bind-to-80-failed-98-address-already-in-use/

The docs still suggest using "[::]:80" but only "80" works

I changed the config to this and it worked
```
listen 80 default_server;
listen 443 default_server ssl deferred;
```
I don't use ipv6 so I did remove the part about ipv6 on the listen line.

The issue is like to #620 but likely due to nginx updates.

**Comment by votdev** [comment]
To get nginx configured as you would like to see you simply need to fully disable IPv6 on your system. Please check out the Debian documentation how to do that.

Reference:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/nginx/files/site-webgui.j2#L51

I will close this issue because OMV actually configures nginx the suggested way if IPv6 is disabled.
