### ISSUE TITLE
Provide S.M.A.R.T. information in OMV 5 GUI for NVMe SSD

### ISSUE THREAD

**Issue by pokrzys** [openmediavault/openmediavault#851]
**Description of issue/question**

SMART Information window in OMV GUI does not provide any SMART data for NVMe drive.
Device model field is blank, despite being correctly recognized in SMART->Devices table.
Smartctl gives correct output for `smartctl -x /dev/nvme0n1` command so it seems that there is a problem in GUI reading does values correctly. 

**Steps to reproduce issue**

Installing any NVMe drive in OMV 5 and checking it's SMART data.

**Versions report**
OMV 5.5.16-1 using smartmontools 7.1.1

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php?thread/31080-useless-smart-error-is-being-alerted-for-nvme-drive/

**Comment by pokrzys** [comment]
No correlation between issue and the topic. I am not getting any smart alerts or warnings in the logs.
If I understand correctly, OMV uses smartctl to get SMART data from the drives. So if smartctl is giving correct output and OMV GUI does not, there problem is with reading those values. 
Please correct me if I wrong.

**Comment by pokrzys** [comment]
Adding few screenshots from OMV GUI

![1](https://user-images.githubusercontent.com/11903254/99297410-863f8c00-2848-11eb-826a-d7fa52d42ed3.jpg)
![2](https://user-images.githubusercontent.com/11903254/99297412-8770b900-2848-11eb-9faf-c3c67ecb5224.jpg)
![3](https://user-images.githubusercontent.com/11903254/99297414-8770b900-2848-11eb-951b-aba8bb22bd01.jpg)
![4](https://user-images.githubusercontent.com/11903254/99297416-88094f80-2848-11eb-8c73-a08e05a6a757.jpg)

**Comment by votdev** [comment]
One of the reason might be that you are using a smartmontools version that is not shipped by Debian. Debian 10 (Buster) is shipping [smartmontools 6.6](https://packages.debian.org/buster/smartmontools), and OMV only supports the version that comes with the stable release.

**Comment by votdev** [comment]
As far as i remember, NVMe devices to not support SMART attributes, thus they can't be displayed in the UI if there are non to read-out.

**Comment by votdev** [comment]
OMV does not read device vendor and serial number using smartmontools because of performance issues. Those values are retrieved via UDEV or sysfs. If these values are not available there, then the device is not correctly supported by the kernel or something else is not working correctly. If you want to get them displayed in the UI, then you can create a custom UDEV rule to read-out the value manually and update the UDEV database which is used by OMV as mentioned above.

**Comment by votdev** [comment]
> Device model field is blank, despite being correctly recognized in SMART->Devices table.

As mentioned above, OMV uses UDEV and sysfs to retrieve various information because of performance reasons. The SMART dialog instead shows the data retrieved by smartmontools. Because you are using smartmontools 7.1 OMV can not read the value because 6.6 shows the information named as `Device Model` whereas 7.1 is using `Model number`. Because of that reason OMV only supports the version that is shipped by Debian stable.

**Comment by votdev** [comment]
I've opened the feature request https://github.com/openmediavault/openmediavault/issues/852 for OMV6 that will hopefully help to allow users to use unsupported smartmontools versions.

**Comment by mi-hol** [comment]
@pokrzys  did openmediavault 5.6.22 resolve the issue?
