### ISSUE TITLE
Filesystem backend efficiency

### ISSUE THREAD

**Issue by subzero79** [openmediavault/openmediavault#88]
I've been just recently trying to patch some issues we have with the zfs plugin. Among those issues is the one that happens when you use docker in conjunction with zfs as a storage driver. So my idea is to add some filtering to those clones, snapshots and filesystems that docker creates.

When fiddling around with the code i just noticed by adding a debug print in the zfs enumerate function from the backend, that this one is called 12 times,  the pool only has 5 datasets (including the pool). 12 is actually the number of filesystems rendered in the default omv fs section (all fs).

Just to be sure I did the same with remote-mount plugin enumerate function and the same happens. I also did this with the default omv enumerate function and also the same is called as many fs are present.

So i don't if there is room to improve the code? because i would though that enumerate is called by type, then it returns the an array of fs of that given type just once, not for every FS.

If we add more backends (via plugins), and then we add and they have at least one fs, the more it slows down.

A single pool with 5 datasets and the omv fs grid renders in about 2 seconds, the more containers/images you add the more it slows down.

This is the debug log, where you can see the debug print, returning the zfs filesystems array 12 times.

https://paste.debian.net/1021631/

**Comment by votdev** [comment]
I've identified the bottle neck, but i don't know if this can be fixed/improved because of file system plugins for BTRFS and ZFS. Because of those plugins it's necessary to always get the specialized backend class for a file system because various methods may be overwritten by these classes.

If you get the file system list the RPC [FileSystemMgmt::getList](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L282) calls [enumerateFilesystems](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L63) which gets a list of all existing file systems. This is the first time [\OMV\System\Filesystem\Filesystem::getFilesystems()](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesystem.inc#L800) is called. The FileSystemMgmt::getList now processes all found file systems and wants to know if they are [configured/mounted via OMV](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc#L112). To do so the database is checked for ``mntent`` entries. 
The [FsTab::getByFsName](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/fstab.inc#L165) RPC now needs to know ALL device file names of the file system to find the database entry. To do so the \OMV\System\Filesystem\Filesystem object for the file system is get via [Filesystem::getImpl()](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesystem.inc#L840). The implementation of this method must get the backend class of the file system, thus it enumerates all file systems again.

While writing this comment i think i've an idea how to improve it a little bit. But the core problem still exists, everything must be generic to make the FS plugins happy and independent.

It's a little bit difficult to explain the problem and behavior, so i hope it's almost clear what happens here.
