### ISSUE TITLE
Change /etc/fstab to Use UUID instead of /dev/name

### ISSUE THREAD

**Issue by nn10nn10** [openmediavault/openmediavault#922]
Occasionally having issues if a drive is removed or dies randomly. OMV uses drive names (ie. /dev/name) and then states can't find this drive after an issue. Using drive UUID is preferred and would prevent issues.

**Comment by ryecoaaron** [comment]
OMV uses the device path which may be uuid or device label.  These should not change (label might if you change it).  UUID does not work for some filesystems (btrfs and vfat).

**Comment by votdev** [comment]
openmediavault always uses predictable device files. If there is something like /dev/xxx, then UDEV does not provide alternative device files for your drive.

* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/blockdevice.inc#L199
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesystem.inc#L454
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/block.py#L93
* https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py#L181

I close this issue because there is nothing wrong with openmediavault.
