### ISSUE TITLE
Detach execution process of scheduled jobs from the OMV GUI

### ISSUE THREAD

**Issue by yuriw** [openmediavault/openmediavault#927]
I will use an example of a scheduled job.

I use `rsync` as a scheduled job (I know I can do it via the OMV GUI, but prefer the Scheduled Jobs option).
When I manually run such job a progress window is displayed and if that window is closed by mistake or otherwise, the job process is killed as well.

Please consider an option when this behavior would change  and Scheduled Jobs run regardless OVM GUI status.

(The open question is- what it will look like at the end?  If the general idea is accepted we can discus it)

**Comment by votdev** [comment]
The behavior to kill a process when the UI window is closed is by intention to prevent freaking out processes. Conceptually it is not possible to attach a window to a running background job, so there is no way to stop such infinite running processes. Because of that reason the current implementation and workflow will not change.

**Comment by votdev** [comment]
By the way, the shell or additional commands provide features to decouple a process from their parent, thus the child process will not be terminated when the OMV backend kills the shell process that is executing the scheduled jobs script (started from within the UI).

**Comment by yuriw** [comment]
Sure, I can use term command line interface to accomplish it.
The goal was to improve user experience using the OMV GUI.
Thx
