### ISSUE TITLE
When changes are pending, can we see what those changes are, or were?

### ISSUE THREAD

**Issue by yllekz** [openmediavault/openmediavault#948]
**Describe the solution you'd like**
Sometimes I will log into the OMV control panel for the first time in a while, and a pending changes banner is displayed at the very top. I either have a bad memory of what I did before or wasn't the one to place the pending changes, so I'm always a bit wary of applying or reverting them. It would be super nice if we could actually see the queued tasks before deciding what to do with them.

In VMware vCenter there is an expandable/collapsable "recent tasks" pane at the bottom of the UI that chronicles changes made. Maybe that could be used as inspiration for an OMV 6.x feature where there could be such a panel that displays not only pending changes, but shows the past changes as well?

**Comment by votdev** [comment]
It's technically not possible what changes are done an easy way, because of that it is not possible to view the changes in the UI. 

I do not want to display that information in the UI because it does not fit in the concept of OMV (which is 'hide the user from nearly everything technical related') and it is an irrelevant information for most of the users, too. Those who really want to know it can use `omv-firstaid` to do so.

![Bildschirmfoto vom 2021-01-22 22-22-05](https://user-images.githubusercontent.com/1897962/105548908-8c4a6100-5d00-11eb-87a7-c66b07b8ec4d.png)

![Bildschirmfoto vom 2021-01-22 22-22-23](https://user-images.githubusercontent.com/1897962/105548931-91a7ab80-5d00-11eb-8d2f-5037dc8f727c.png)

![Bildschirmfoto vom 2021-01-22 22-22-38](https://user-images.githubusercontent.com/1897962/105548949-9704f600-5d00-11eb-9822-02bb3b959cc8.png)

A list of modules that are dirty and to be deployed can be listed by
```
root@omv5box:~# cat /var/lib/openmediavault/dirtymodules.json 
[
    "rsync"
]
```

**Comment by votdev** [comment]
I'll keep this issue open for external contributors, but don't expect this is implemented by the project itself because of the reasons explained above.

**Comment by nettings** [comment]
Nice workaround, though - can I suggest you create an issue label "workaround provided" or something? That way, these handy tricks are found more easily.

**Comment by votdev** [comment]
> Nice workaround, though - can I suggest you create an issue label "workaround provided" or something? That way, these handy tricks are found more easily.

Done, see https://github.com/openmediavault/openmediavault-docs/commit/b24ad1a8dac53939dc490d63b12f6cfad9308f1b

**Comment by votdev** [comment]
> Is there a log output/file of what has changed?

You can do a manual diff of the configuration files.

```
root@omv6box:/home/vagrant# ls -alh /etc/openmediavault/
total 128K
drwxr-xr-x  2 root root                  4.0K Apr 25 16:37 .
drwxr-xr-x 92 root root                  4.0K Apr 25 16:37 ..
-rw-rw----  1 root openmediavault-config  24K Apr 25 16:37 config.xml
-rw-------  1 root root                   24K Apr 25 16:37 config.xml.0001
```

or use `omv-firstaid`, use `restore configuration backup` and have a diff:

![Bildschirmfoto vom 2022-04-25 18-39-18](https://user-images.githubusercontent.com/1897962/165134486-60c8a61a-39a2-49da-adc0-7dc35c83cd91.png)
