### ISSUE TITLE
Optional soft link to shared folder

### ISSUE THREAD

**Issue by dsm1212** [openmediavault/openmediavault#953]
**Is your feature request related to a problem? Please describe.**
I soft link a more functional set of folders to the shares so that I'm not using the dev disk identifiers everywhere in my system. Maybe this is not so common, but since i set up my own docker compose files and use SSH a lot, I get sick of the long named mount points which have nothing to do with what I'm running.

**Describe the solution you'd like**
When I create a shared folder I'd like to optionally choose a location to soft link to the shared folder.

So, I'm adding media to /srv/dev-disk-by-label-data and I also get to specify that I want this soft linked at /media on the host. 

The nice thing about putting this in the configuration is that 1) I'm not using the shell. 2) it saves/deletes with the config for consistency and recovery. 3) moving libraries of stuff from another system to openmediavault can be easier. 

**Describe alternatives you've considered**
I do this by hand using bash

**Comment by votdev** [comment]
This feature is already in OMV since v4 but has been [disabled some time ago](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/changelog#L427) because it made more troubles than it helps. You can enable it manually via the environment variable `OMV_SHAREDFOLDERS_DIR_ENABLED`.
Please check https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables how to use env vars.

**Comment by ryecoaaron** [comment]
There is a symlinks plugin in the omv-extras repo that at least lets you manage the symlinks from the web interface.

**Comment by dsm1212** [comment]
Super, two options, thanks!
