### ISSUE TITLE
if we change the host name, the third network config will lost

### ISSUE THREAD

**Issue by fennien** [openmediavault/openmediavault#963]
I have a AX200 wifi card. When I change the host name by "System - Net work - Host name", I will lost my netplan configure file of my wifi,  /etc/netplan/30xxx.yaml. Then I have edit this file again, and reboot to let my wifi work again.

**Comment by votdev** [comment]
This is a normal behavior because OMV is the master of the configuration files it controls and will always override them. If you want to apply custom configuration, then create a new yaml file in the netplan.io config directory. netplan.io will merge all files, thus your custom config will be applied, too. If you want to override OMV settings, then you need to use the [environment variables](https://openmediavault.readthedocs.io/en/5.x/various/advset.html#environmental-variables) to do so.
