### ISSUE TITLE
Add an option to increase PHP memory/truncate Execute window output to avoid Rsync GUI bug

### ISSUE THREAD

**Issue by havenoskills** [openmediavault/openmediavault#972]
Problem: When running Rsync (dry run) in the Execute window, a PHP memory will occur when displaying the output from a filesystem that has a lot of files. In my case, 650,000 files. The logged error message is: _omv-engined[1155]: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 33554440 bytes) in /usr/share/php/openmediavault/functions.inc on line 573_
This is a repeatable bug, and you can make it bomb on a slightly smaller file system by increasing rsync verbosity. An ordinary user isn't going to know to edit php.ini -- I only did so after seeking forum help (thanks!).

Two possible solutions:
A. Editing _/etc/openmediavault/php.ini_ to change the memory limit from 128M to -1 fixed the problem for me, but the desired solution would be to add an option for advanced users to check a box to set it at 256M or 512M or fill in a box with an arbitrary amount. 

B. Truncate the output of the Execute window. In my case, it bombed after 685,305 lines (54,516,618 bytes) were displayed. If only 500,000 lines were displayed, the bug would be fixed. This also solves a browser-related issue. For me, Firefox stopped displaying the output after reaching a certain point, so it appeared like OMV failed when the rsync task did complete successfully using a higher memory limit. Vivaldi displayed everything, though copying that much text makes the browser glitchy and unresponsive. In other words, having the complete output is kinda useless -- even on a fast machine with ram to spare. It'd be nicer to truncate and pipe the full output to a logfile.

**Comment by ryecoaaron** [comment]
I disagree that this is a "bug".  Using more resources than your system has is not a bug.  This php setting is not maintained by OMV and therefore, you can change if you are doing things that use significantly more resources than a normal user (never seen the problem myself).

Truncate by lines would not work because you don't know how long the lines are.  Maybe it would fix rsync in your case.  I didn't write it but I don't think the execute button was designed for running really long things.  Just testing initial setups.

**Comment by votdev** [comment]
> Truncate by lines would not work because you don't know how long the lines are. Maybe it would fix rsync in your case. I didn't write it but I don't think the execute button was designed for running really long things. Just testing initial setups.

Right, that was the intention.

**Comment by votdev** [comment]
I'm wondering why this happens, because the output window only requests only the latest appended output (lines) from the backend, so it should not request 650k of lines at once.

References:
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/exec.inc#L107
https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/var/www/openmediavault/js/omv/window/Execute.js#L356

**Comment by havenoskills** [comment]
> I disagree that this is a "bug". Using more resources than your system has is not a bug.

The bug has nothing to do with system resources. Tested on a vm with 40gigs of ram assigned -- overkill just to be sure.

> This php setting is not maintained by OMV and therefore, you can change if you are doing things that use significantly more resources than a normal user (never seen the problem myself).

By this logic, OMV shouldn't exist because everything can be done in the command line. This kind of bug is going to be more 'normal' as drive capacities go up. Also, how does an abnormal user (someone with lots more files than you have) know which setting to change? THAT is the problem. My proposal is to add a setting _in the GUI_ to address a bug _in the GUI_. I think we agree, here?

The /etc/openmediavault/php.ini file in question has an OMV-specific section at the end, so it appears already  to have been edited by OMV.

> I didn't write it but I don't think the execute button was designed for running really long things. Just testing initial setups.

Agreed. That's precisely what I was doing. A dry run of a backup. Only way to know if it will work is to go through the whole thing. I've had command line rsync bomb in the past over filename problems (none of those here, by the way). Only takes a few minutes to run once the memory limit is raised.

As for the viability of truncating and the root cause of the issue, that's above my head. My not-a-programmer theory is the script is sending data in excess of 128m to a UTF-8 conversion php function that formats the output for display in the execute window, and that exceeds the arbitrarily set 128m memory limit.

**Comment by ryecoaaron** [comment]
> The bug has nothing to do with system resources. Tested on a vm with 40gigs of ram assigned -- overkill just to be sure.

System resources does not mean ram.  A php setting is a system resource.

> By this logic, OMV shouldn't exist because everything can be done in the command line. This kind of bug is going to be more 'normal' as drive capacities go up. Also, how does an abnormal user (someone with lots more files than you have) know which setting to change? THAT is the problem. My proposal is to add a setting in the GUI to address a bug in the GUI. I think we agree, here?

No, just because OMV does not maintain a setting doesn't mean it shouldn't exist.  There are MANY settings that are not exposed to the web interface.  Volker's philosophy has always been keep it simple.  People will not understand how to set php max memory and it will cause more problems than it fixes (and no lots of people will change it because it is there).  So, I do not think it should be a web interface setting.  Drive capacity going up shouldn't be that big of a factor.  I have never seen this in 12 years of using OMV and people could very easily have millions of small files on a 1TB drive.

> The /etc/openmediavault/php.ini file in question has an OMV-specific section at the end, so it appears already to have been edited by OMV.

OMV creates it once but no code will change it if you need to modify it for your rather unique issue.

I'm not the maintainer of OMV and not the one who needs to be convinced.  But I am one who supports a lot of people and has for years.  I know what kind of settings would trip people up.  So, I am just giving my two cents.

**Comment by havenoskills** [comment]
> I have never seen this in 12 years of using OMV and people could very easily have millions of small files on a 1TB drive.
This is the first time I've used OMV. After setting up the drives -- very easy -- the first thing I did was go to rsync to see if OMV backup would work. It didn't. I could have uninstalled and moved on without posting anything on the forum. I imagine that happens a lot. In fact I've moved on from other software after running into a fatal bug, googling the issue, and seeing devs get "you're the problem, not the code" about fixing them. I'd hope the interest here would be to have code that doesn't bomb, even in edge cases. From googling I found someone hit OMV's php mem limit in 2012 doing something else in the GUI, so I'm not alone.

> People will not understand how to set php max memory and it will cause more problems than it fixes (and no, lots of people will change it because it is there). 
And do you think someone with a lot of files (perhaps filename length and directory depth are also part of the problem) is going to know the fix is in editing /etc/openmediavault/php.ini when the log error message doesn't point that way? Having a lot of files doesn't make you a programming genius. In fact, I am proof of that.  I'd settle for an error message in the Execute display saying "you've exceeded the memory limit set in /etc/openmediavault/php.ini, edit the file to change it." 

I have already fixed the problem for myself. I think this should be changed so _other users_ don't run into it, get frustrated, and give up.

**Comment by ryecoaaron** [comment]
> seeing devs get "you're the problem, not the code" about fixing them

I never said the value shouldn't be increased in the config.  I just said I don't think it is a bug and the setting shouldn't be in the web interface.  It just needs to be made carefully since there are a lot of RPi users with 1 GB of ram.  And these are the exact users that wouldn't know how or when to change it (and probably do it wrong or for no reason) even if it was in the web interface and hitting the problem you are having.

> And do you think someone with a lot of files (perhaps filename length and directory depth are also part of the problem) is going to know the fix is in editing /etc/openmediavault/php.ini when the log error message doesn't point that way? Having a lot of files doesn't make you a programming genius. In fact, I am proof of that. I'd settle for an error message in the Execute display saying "you've exceeded the memory limit set in /etc/openmediavault/php.ini, edit the file to change it."

I would argue that is what the forum is for.  There are infinite problems that could happen from the web interface and OMV could never tell you all solution to fix.  I'm not even sure the error could be customized in this situation to do what you are asking.

> From googling I found someone hit OMV's php mem limit in 2012 doing something else in the GUI, so I'm not alone.

that is so old that OMV could have been using a lower setting or not even setting it in the first place.  I would say two cases out of the tens of thousands of OMV users is pretty good.  Windows sure as hell can't say that.

**Comment by votdev** [comment]
This issue is a good example why it is so difficult to fix issues with suggestions from the community. Users only see their problem, not the whole thing. The problem here seems to be a memory limit in PHP, and the easiest solution for users is to simply increase a configured limit. And that is the absolute wrong solution and direction. The correct way to fix this issue is to ensure that the request to get the command output only reads up to a specified number of lines or size (e.g. 1024B or 1MiB per request). So we are sure not to reach any resource limit, predictable.

**Comment by havenoskills** [comment]
> The correct way to fix this issue is to ensure that the request to get the command output only reads up to a specified number of lines or size (e.g. 1024B or 1MiB per request). So we are sure not to reach any resource limit, predictable.

That's was what I was clumsily trying to accomplish with "truncate the output" suggestion. That would be a neat solution if it's possible.

**Comment by votdev** [comment]
`openmediavault 5.6.1` has been released, please give it a try and report back if the issue has been solved finally.

**Comment by havenoskills** [comment]
I reset /etc/openmediavault/php.ini to the default 128M, rebooted and updated to 5.6.1. Since my files are in sync, I ran rsync -vv to create a flood of output in the execute window.  I could see it sending data in chunks, but when the output reached an arbitrary point, the output stopped. 

So, the error is gone, and the task completes (great!), but from a functionality standpoint the user is left hanging. The user doesn't actually _know_ that the command completed successfully or why the display just stopped. There is a rsync completion message in the log. Seems to me it would be appropriate to add some kind of message in the window like "display limit reached" or give the rsync exit result as completed/failed/whatever. Definitely fixes the main issue, though.

**Comment by votdev** [comment]
Seems the browser does not like that much of text, maybe a queue will help to fix that by throwing out older lines.

**Comment by havenoskills** [comment]
Yes, sorry. I forgot firefox just stops outputting the text once it reaches a certain amount. Let me try other browsers --

**Comment by havenoskills** [comment]
Ah, there's definitely an issue. The Execute window greys out the "stop" button and enables the "start button" while the output is still being sent to the browser. This happens really early in the process and likely would affect normal users. 

All the Chrome variant browsers after a while stop scrolling and print the output on a single line, overtyping into a solid black bar. Very odd. I copied the output, and it had 923,964 lines saying "Done ..." at the end. Though I think that was just one of three main folders in the operation. Rsync -vv is brutal. So the code is indeed sending everything, the browsers just don't like it.
