### ISSUE TITLE
harden OMV against unintentional modification of configuration files by package management commands run via shell

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#986]
**Is your feature request related to a problem? Please describe.**
OMV maintains a list of configuration files via GUI and expects to have "exclusive" control over them but doesn't make this fact visible to the standard package management tools (i.e. apt, dpkg). 
OMV official documentation and many tutorial in the internet still document to use the standard package management tools.

For the use case that a tool revision also includes a configuration update, the user gets prompted for a decision.
Depending on a number of factors the user may  take the wrong decision causing later issues with OMV.
The forum shows many such cases.

**Describe the solution you'd like**
In [this ](https://forum.openmediavault.org/index.php?thread/38515-apt-run-via-shell-asks-for-user-decision-on-changed-configuration-files-includin/&postID=270381#post270381) forum thread, @dleidert proposed to "lock" OMV maintained configuration files via  flagging  them as "deviation". 
This seems to be the best approach because it prevents users from making errors unintentional, reduces the number of forum posts, but still allows experts to change them intentionally.

On top of technical change, OMV documentations should be revised as suggested in same thread.

**Describe alternatives you've considered**
alternative solution ideas (i.e. alias for apt)  got commented as having severe drawbacks and are not considered further

**Comment by dleidert** [comment]
As a Debian developer I disagree with this statement. The configuration files in question are maintained by a third party tool (omv-salt) for another third party tool (omv). omv-upgrade doesn't take "care" of it, it simply suppresses the configuration file dialogs which would be shown by debconf and dpkg.

The diversion would be the right technical solution here, because the configuration files in question are indeed not controlled by the user nor the original package. They are controlled by omv. By using dpkg-divert to create a renamed diversion for the original configuration file, the package manager would be made aware of that fact and package updates for e.g. samba only affect the renamed file, while dpkg won't care anymore about the configuration file produced via omv-salt. **Even the dpkg-divert manual page lists your case:** "System administrators can also use it to override some package's configuration file, .. [..]" which is exactly what you are doing.

**Comment by votdev** [comment]
> As a Debian developer I disagree with this statement. The configuration files in question are maintained by a third party tool (omv-salt) for another third party tool (omv). omv-upgrade doesn't take "care" of it, it simply suppresses the configuration file dialogs which would be shown by debconf and dpkg. That is not "taking care", that is "working around the symptoms".
> 
> The diversion would be the right technical solution here, because the configuration files in question are indeed not controlled by the user nor the original package. They are controlled by omv. By using dpkg-divert to create a renamed diversion for the original configuration file, the package manager would be made aware of that fact and package updates for e.g. samba only affect the renamed file, while dpkg won't care anymore about the configuration file produced via omv-salt. **Even the dpkg-divert manual page lists your case:** "System administrators can also use it to override some package's configuration file, .. [..]" which is exactly what you are doing.

Thanks for confirming that it should work that way.

**Comment by votdev** [comment]
Now someone has to provide a list of files that have to be processed that way.

If we have a list, i can provide a Salt state that can be used to mark such a file wherever needed. IMO that is the most elegant solution to do that programmatically, but i'm open for suggestions.

Example:
```
configure_ssh_sshd_config:
  file.managed:
    - name: "/etc/ssh/sshd_config"
    - source:
      - salt://{{ tpldir }}/files/sshd_config.j2
    - template: jinja
    - context:
        config: {{ config | json }}
    - user: root
    - group: root
    - mode: 644

divert_ssh_sshd_config:
  omv_dpkg.divert:
    - name: "/etc/ssh/sshd_config"
```

**Comment by mi-hol** [comment]
> Now someone has to provide a list of files that have to be processed that way.

Could the list be derived from OMV's "configuration database"?

**Comment by votdev** [comment]
> > Now someone has to provide a list of files that have to be processed that way.
> 
> Could the list be derived from OMV's "configuration database"?

No. I don't know if there is a magical internal Debian tool that can provide that information, so i guess someone has to check manually which files are overwritten by OMV. Deploying a service and reinstalling the package might help here, because i hope DPKG will raise the question to overwrite a file when it is installed by the package (and previously overwritten by OMV). In that case it is confirmed that this file has to be handled by dpkg-divert.

**Comment by votdev** [comment]
Done. You can simply do that yourself the next time with the following lines.
You can find the commit id in the commit [history](https://github.com/openmediavault/openmediavault-docs/commits/master/plugins.rst) by clicking on the `Copy to clipboard` button. 
```
 ~/git/openmediavault-docs   5.x ✔  $ git checkout -b backport_issue_69
Zu neuem Branch 'backport_issue_69' gewechselt
 ~/git/openmediavault-docs   backport_issue_69 ✔  $ git cherry-pick -x --signoff --no-commit 21397da77888f0da54c8bd141ca11c0e68e6cb2b
```
Now commit the changes and push the branch. Finally create a PR out of that branch.

**Comment by votdev** [comment]
@dleidert Could you please review the command line and make sure this is correct?

https://github.com/openmediavault/openmediavault/pull/1048/files#diff-4b850705b7466171f015b1dd092efca0da90b5d7236f1d1db8c30869c46aeb93R41

<details>
<summary>Details</summary>



</details>

**Comment by votdev** [comment]
Sadly this is another example of a low-hanging fruit issue that could have been fixed easily by a community contribution, but it seems i have to do everything myself to make it correct.

**Comment by dleidert** [comment]
@votdev: Give me a few days. I'm currently swamped. But I get back to you.
