### ISSUE TITLE
Let OMV act as Windows Domain Controller

### ISSUE THREAD

**Issue by the-Arioch** [openmediavault/openmediavault#992]
Microsoft NT Domain / Active Directory provides for single sign-on, time sync, roaming user profiles and other features.

From home use of NAS appliances single sign on is the immediately seen problem. Creating new user or changing password should be repeated on every single device. Fragile and boring.

Microsoft desktop operating systems are prohibited from becoming "domain controllers".

However SAMBA has domain controller functionality. It is limited (for example Russian AstraLinux FAQ says once domain was created in Samba it can not be renamed, only deleted and created anew) and might be obsolete, but it would be enough at least for having centralized users database for all the family.

https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller

**Comment by votdev** [comment]
I will keep this issue open in case someone tries to implement this feature as plugin, but OMV core will never act as AD controller. Everyone who wants to act as AD should use Zentyal or equivalent solutions.

**Comment by the-Arioch** [comment]
````
Native compatibility with MS Active Directory
Mail Server
Gateway & Infrastructure Server
REQUEST FREE TRIAL
````

Sounds like overshooting for home use. 

BTW, do OMV Extra have separate bugtracker / sources repo ?
Their bootstrap is integrated into OMV, but they seem to be somewhat falling apart already (omv extra common package issues all around tracker and forum and reddit).

**Comment by votdev** [comment]
> ```
> Native compatibility with MS Active Directory
> Mail Server
> Gateway & Infrastructure Server
> REQUEST FREE TRIAL
> ```
> 
> Sounds like overshooting for home use.
> 
> BTW, do OMV Extra have separate bugtracker / sources repo ?
> Their bootstrap is integrated into OMV, but they seem to be somewhat falling apart already (omv extra common package issues all around tracker and forum and reddit).

You make me smile. AD isn't overshooting for home use?

**Comment by the-Arioch** [comment]
AD would be overshooting if Windows had any different single sign-on engine. Okay, they now have, Microsoft cloud built.... on top of NT Domains. But i did not hear anyone ported PAM to Windows, so there is not a lot of choice.

**Comment by ryecoaaron** [comment]
> BTW, do OMV Extra have separate bugtracker / sources repo ?
Their bootstrap is integrated into OMV, but they seem to be somewhat falling apart already (omv extra common package issues all around tracker and forum and reddit).

What is falling apart?? There is an issue track for each plugin - https://github.com/OpenMediaVault-Plugin-Developers

**Comment by the-Arioch** [comment]
1. OMV's WebUI stops working after extras are installed. Because no one bothers to install omvextras-common package

Just google for **OMV\Exception: Failed to open include file 'js/omvextras/window/RootFolderBrowser.js**

2. I think apt-get window stuck after apt-get stopped running (i think i saw last lines being "Done" and "done.") with no normal way to close it. The close button was still disabled. I do not have clear detailed memory of that moment, but i think it was related to Extras. Usually other apt-get windows in WebUI were closed normally.

3. and i wonder if extras are solving the "Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021." - there is no even mention of it on omvextras site

**Comment by ryecoaaron** [comment]
> OMV's WebUI stops working after extras are installed. Because no one bothers to install omvextras-common package

The webui should not stop working after omv-extras is installed.  We would have thousands of people with issues otherwise.  omvextras-common is not needed by most omv-extras itself.  It is needed by a handful of plugins that should install it just like any other dependency when you install the plugin.  If that isn't happening, something is wrong with apt on the system.  Even if it isn't installed and a plugin needs, it doesn't break the web interface.  It only breaks the folder browser.

> Just google for OMV\Exception: Failed to open include file 'js/omvextras/window/RootFolderBrowser.js

Once again, I have helped many people on the forum with this and have no idea what is deleting the files.  If something is removing that package, there isn't much I can do about that.  Re-installing the package does fix the issue.

> I think apt-get window stuck after apt-get stopped running (i think i saw last lines being "Done" and "done.") with no normal way to close it. The close button was still disabled. I do not have clear detailed memory of that moment, but i think it was related to Extras. Usually other apt-get windows in WebUI were closed normally.

Without more details, I'm not sure what is causing this.  omv-extras is just using a normal exec window and executing a simple apt-get command.  It would be interesting to have more details. If you can't close the window, you can alway refresh the page.  omv-extras is using low level extjs stuff.  Just the normal omv supplied components.

> and i wonder if extras are solving the "Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021." - there is no even mention of it on omvextras site

omv-extras moved to github repos on Feb 9th.  I posted about this on the forum - https://forum.openmediavault.org/index.php?thread/37980-omv-extras-repos-moving-to-github/&postID=266046&highlight=bintray#post266046 and the changelog says that - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/debian/changelog#L63 

So, all of these "issues" means omv-extras is falling apart??
