### ISSUE TITLE
In File Systems: Mount Point Column "On" by Default

### ISSUE THREAD

**Issue by flmaxey** [openmediavault/openmediavault#997]
**Is your feature request related to a problem? Please describe.**
**No**

**Describe the solution you'd like**
As of OMV 5.2.20 Data Drives are mounted by **UUID**.  However, in File Systems, drive **Mount Point**s are not viewable by default.
It would be beneficial for users to see drive UUID's, by default, to associate UUID's with device names and drive labels.  

As a secondary preference, the mount point column would be moved left, next to the drive label column.  The column would not, necessarily, have to be wide enough to accommodate the full UUID name by default.  Users could expand column width to reveal the full name, if needed.

![mountpoint](https://user-images.githubusercontent.com/42286890/112999820-43b68600-913d-11eb-9f2d-d638ef29de69.jpg)

**Comment by flmaxey** [comment]
> Is it OK to make this happen in OMV6 only?

If OMV 6 is coming out relatively soon (in months - less than 1 year), I believe that would be OK.   

Since UUID has the appearance of a random string of numbers, that are impossible to memorize, the idea is to cross reference srv/dev-disk-by-uuid-* to something meaningful to the user.   Thanks

**Comment by votdev** [comment]
> It would be beneficial for users to see drive UUID's, by default, to associate UUID's with device names and drive labels.

Are users really use UUID's to identify their file systems? I mean, this is a really unhandy number to identify.

Isn't it enough to allow the user to enable/disable columns on demand? These changes are stored in cookies, so the settings are persistent as long as the cookie has not been deleted. Columns can also be moved, this is also stored in the cookie. With this features i think the user has all needed to customize the look of the datatable. If these datatable features are not known, then we need to enhance the documentation instead of changing the UI, right?

Just for information, in OMV6 the user can add a comment for identification issues to a file system that is mounted. Please see https://github.com/openmediavault/openmediavault/pull/999.

**Comment by flmaxey** [comment]
> **Do users really use UUID's to identify their file systems? I mean, **this is a really unhandy number for identification**.**

I 100% agree.  UUID's are not user friendly.  I don't know why the path to data disks was changed from "by label" to "UUID" because UUID is random, very l-o-n-g, and very difficult to type for CLI operations.  Further, making this change midstream, while 5.X is in progress, results in the following:


![UUIDVLABEL](https://user-images.githubusercontent.com/42286890/113508276-1abb3a00-951d-11eb-864e-142ba7a634ae.jpg)



> **Isn't it enough to allow the user to enable/disable columns on demand?**

This is what most would call an "undocumented feature".  Most users, new and experienced alike, accept the file system page presentation as it is.  Without hovering a mouse over the column heads (and there's no reason to do this), the drop down arrow is not visible.  Further, there's no reason for users to assume or believe that columns are "drag and drop".  
I didn't discover these features, myself, until a couple years after I started using OMV.  I found them while searching for a way for beginner's to create "easy to setup" backup, that's simple to restore, without getting on the CLI.  That section of the New User's Guide is Full Disk Mirroring -> [here](https://openmediavault.readthedocs.io/en/5.x/new_user_guide/newuserguide.html#full-disk-mirroring-backup-with-rsync) 

Drives by UUID will change the following rsync command line:
**rsync -av --delete /srv/dev-disk-by-label-DATA/ /srv/dev-disk-by-label-RSYNC/**
To something like this:
**rsync -av --delete /srv/dev-disk-by-uuid-924731f2-ed8f-4c4f-ab98-3d922c9ba258 /srv/dev-disk-by-uuid-56821182-9b74-437f-8fa1-05c992a276d2**

Beyond being nearly impossible to type accurately, drives by UUID may create more drive-to-drive copy mishaps by users confusing the source with the destination and entering them backward.  The following file system presentation would, at least, make an association between the UUID and the drive device name / drive label to given an indication to the user which drive they're dealing with.

![Columns](https://user-images.githubusercontent.com/42286890/113510151-5ce97900-9527-11eb-8aef-0d6696da2d07.jpg)

> **If these data table features are not known, then we need to enhance the documentation instead of changing the UI, right?**

I have already added a graphic and an explanation of how to reveal drive [mount points](https://openmediavault.readthedocs.io/en/5.x/_images/61_rsync.jpg), as part of the rsync backup section.  That won't be of much help to users who don't read through the guide which, I suspect, are the majority.  A default presentation would work for all.
________________________________________________________________________________________

Beyond the above rsync command line, there will be numerous follow on effects of switching drive paths to UUID.  Anything that requires a CLI path to a storage location, such as server add-on's, Dockers, etc., will be affected.

While I can deal with the change, in this issue, I'm acting as a NOOB advocate.  My preference for new users would be:
1. Go back to drives "by-label" for the remainder of OMV5's life.  
If UUID's are essential, that might mean abstracting drive UUID's into the background while presenting "by-label" to users in the GUI and on the CLI.  (Which might be useful for OMV6 as well.)
OR
2. Modify the File System page so that an association between a drive UUID and the device name or label can be made, similar to the graphic above, **by default**.

I'll assume there are very good, almost critical, reasons for switching drives to UUID.  On the other hand, the secondary effects to users are worth close consideration as well.  

Thanks for your time and consideration.

**Comment by rabelux** [comment]
@votdev is there a way to restore the old "*by-label*"-behaviour? And are there any downsides, assumed that I make sure every drive has its own unique label?

As I'm using the terminal regularly to navigate to my drives, the uuid-paths bother me quite a bit.
I tried to change the mountpoint in `/etc/openmediavault/config.xml` and altered the `<mntent>`->`<dir>`-entry.
Then I ran `omv-salt deploy run fstab` but somehow broke it completely. Thought I was being smart.
The result was a missing filesystem in the web-ui and I had no access to my drive anymore.
Unplugged the drive, deleted the filesystem in the web-ui, and remounted. That fixed it, I'm back to uuid-path.

**Comment by votdev** [comment]
> @votdev is there a way to restore the old "by-label"-behaviour? And are there any downsides, assumed that I make sure every drive has its own unique label?

No, there is no way to do that. Label support has been completely removed in OMV6 because `/dev/disk/by-label/` device files are absolutely not predictable. For the user, it shouldn't matter which device files are used under the hood, so OMV only looks to ensure error-free functionality.

**Comment by rabelux** [comment]
> For the user, it shouldn't matter which device files are used

Totally agree. What I'm trying to accomplish though is a more user-friendly mount-point.
Wouldn't it be possible to keep the old mount-path `/srv/dev-disk-by-label-xxx` for drives with unique labels?

As an alternative, is there a way to change the default mount-path?

Some scenarious require providing absolute paths and the uuid-representation makes this quite hard and the path really long.

Anyhow, thank you for providing OMV!

**Comment by votdev** [comment]
> > For the user, it shouldn't matter which device files are used
> 
> Totally agree. What I'm trying to accomplish though is a more user-friendly mount-point.
> Wouldn't it be possible to keep the old mount-path `/srv/dev-disk-by-label-xxx` for drives with unique labels?
> 
> As an alternative, is there a way to change the default mount-path?
> 
> Some scenarious require providing absolute paths and the uuid-representation makes this quite hard and the path really long.
> 
> Anyhow, thank you for providing OMV!

I'm sorry to say but OMV is not using labels for device files any more and this can't be disabled via a magic switch. The device file and mount point should be somewhat irrelevant for the user because by default the user should never see or work with them (from the OMV perspective). I know you have to deal with them when using Docker, but running the system without problems is the main focus, not having nice device files and mount point paths.

**Comment by rabelux** [comment]
One last question, then I'll stop bugging you:
How come filesystems mounted prior to 5.5.20-1 keep their by-label-mountpoint?
That leaves me thinking that it's still possible somehow.

And please don't see this as an invitation to change said behaviour. I'm glad it didn't change.

Sidenote:
I need absolute paths for plex libraries and rsync jobs that have my nas as a target.

**Comment by votdev** [comment]
> How come filesystems mounted prior to 5.5.20-1 keep their by-label-mountpoint?

All information is stored in the database and OMV does not touch or change that. In the latest version OMV prefers `/dev/disk/by-uuid` and `/dev/disk/by-id` over `/dev/disk/by-label` device files for new mounted file systems. So if you have a file system mounted with an old OMV version the configuration will not be changed until you press the umnount button in the UI. When you re-mount the file system then a new configuration is generated based on the new rules.

**Comment by ryecoaaron** [comment]
> I need absolute paths for plex libraries and rsync jobs that have my nas as a target.

Just create symlinks of the mount point.  This is a one time pain and there is even a plugin to create and maintain the plugins.  Then you will have a human readable path.

**Comment by rabelux** [comment]
Ok I'll go with symlinks then. Thanks to both of you for your responses.

**Comment by Wil-Storch** [comment]
From a user perspective I think this case is valid - with the new disk by UUID as default (a completely warranted change) it makes it difficult to find where the mount point for a file system now is.
Having this column visible by default I believe will help clear up these issues.
I was about to open a enhancement request to have this as a column before finding this issue and realizing that additional columns can be shown via the drop down arrow.

 I am **not** advocating for a return to mount by label, I believe that UUID makes sense, and once users know to expect this it will be a non-issue. Power users can setup symlinks if shorter paths are required, the majority of users will just be working via the UI, or copy pasting from place to place during some initial setup stages.

> Do users really use UUID's to identify their file systems? I mean, this is a really unhandy number for identification.

In simple single disk mount and shares perhaps not, but in more complex multidrive setups having an easy way to view the identifier is helpful. In something like a mergerfs setup, the individual disks don't matter unless they are being changed out, so just having auto generated UUID is fine as long as it can occasionally be mapped to label/device.

> If these datatable features are not known, then we need to enhance the documentation instead of changing the UI, right?

Potentially, however I see most of the questions related to this to be directly UUID related, which is a "difficult" search on the forum as the text "UUID" appears a lot due to being in paths, meaning it is difficult to filter through the noise. Searching for something like "file system display UUID mount point" is unlikely to be fruitful.
I imagine that the majority of questions will stem from mapping file system to UUID/mount location, so adding this column as default may go a long way toward stemming that. 
In addition, toggling a column default behavior is likely to be easier to modify vs full new documentation on the datatable features (or even more difficult, getting the majority of users to read it!)

If no UI changes are desired prior to 6, maybe just an addition to the FAQ, similar to that in the rysnc section:
"**How do I know where a file system is mounted?**" 
"If a user requires knowing the mount point/UUID of a file system, the hidden column '**Mount Point**' can be shown on the file system screen by hovering over a column header, selecting the drop down arrow, selecting the column entry and ticking the box next to 'Mount Point' to display this column. This will be saved in user cookies and persist over user sessions."

**Comment by mi-hol** [comment]
@votdev was this minor change with big usability benefit already implemented or could be done soon?

**Comment by votdev** [comment]
The `Mount Point` column is still not enabled by default because it requires too much space. But in OMV6 enabling/disabling columns is much more intuitive than in OMV5, so hiding this column stays the default.

And from the point of view and concept of OMV this information (the mount point) is not important and something the user should never come into contact. 

![Peek 2021-07-01 12-49](https://user-images.githubusercontent.com/1897962/124112873-0f6ba200-da6b-11eb-9df2-08c68f2805b4.gif)
